-- First-party enrichment for the core Gemini 3.x comparison models.
-- Google AI / DeepMind sources checked 2026-09-06. Current promotional prices are stored where applicable.

WITH verified_patches AS (
  SELECT * FROM jsonb_to_recordset($patches$
[
  {"slug":"gemini-3-1-pro","family":"Gemini 3.1","ga_date":null,"access":"proprietary","comparison_data":{"Developer":"Google DeepMind","Release date":"2026-02-19","API model ID":"gemini-3.1-pro-preview","Context window":"1M tokens","Max output":"64K tokens","Knowledge cutoff":"Jan 2025","Reasoning / effort":"Thinking supported","Input / 1M tokens":"$2 <=200K / $4 >200K","Cached input / 1M":"$0.20 <=200K / $0.40 >200K","Output / 1M tokens":"$12 <=200K / $18 >200K","Long-context surcharge":">200K prompts use the higher input/output/cache tier","Text input":"Yes","Image / vision input":"Yes","Audio input":"Yes","Video input":"Yes","Text output":"Yes","Image output":"No","Audio output":"No","Video output":"No","Tool / function calling":"Yes","Computer use":"No native computer-use tool documented","API access":"Preview","Product access":"Google AI Studio + Gemini API","Weights / license":"Proprietary"},"sources":[{"title":"Gemini 3.1 Pro Preview model docs","url":"https://ai.google.dev/gemini-api/docs/models/gemini-3.1-pro-preview"},{"title":"Gemini API pricing","url":"https://ai.google.dev/gemini-api/docs/pricing"}],"notes":"Preview model; custom-tools endpoint is also available for bash/custom-tool agent workflows.","metadata":{"launch_stage":"preview","verification_pass":"gemini-core-2026-09-06"}},
  {"slug":"gemini-3-1-flash-lite","family":"Gemini 3.1","ga_date":"2026-05-07","access":"proprietary","comparison_data":{"Developer":"Google DeepMind","Release date":"2026-03-03","API model ID":"gemini-3.1-flash-lite","Context window":"1M tokens","Max output":"64K tokens","Knowledge cutoff":"Jan 2025","Reasoning / effort":"Thinking supported","Input / 1M tokens":"$0.25 text/image/video / $0.50 audio","Cached input / 1M":"$0.025 text/image/video / $0.05 audio","Output / 1M tokens":"$1.50","Batch / flex discount":"Batch: $0.125 text/image/video, $0.25 audio input; $0.75 output","Text input":"Yes","Image / vision input":"Yes","Audio input":"Yes","Video input":"Yes","Text output":"Yes","Image output":"No","Audio output":"No","Video output":"No","Tool / function calling":"Yes","Computer use":"No","API access":"Yes","Product access":"Google AI Studio + Gemini API","Weights / license":"Proprietary"},"sources":[{"title":"Gemini 3.1 Flash-Lite model docs","url":"https://ai.google.dev/gemini-api/docs/models/gemini-3.1-flash-lite"},{"title":"Gemini API pricing","url":"https://ai.google.dev/gemini-api/docs/pricing"},{"title":"Gemini deprecations","url":"https://ai.google.dev/gemini-api/docs/deprecations"}],"notes":"Preview launched March 3; stable endpoint reached GA May 7, 2026.","metadata":{"launch_stage":"preview_then_ga","verification_pass":"gemini-core-2026-09-06"}},
  {"slug":"gemini-3-5-flash","family":"Gemini 3.5","ga_date":"2026-05-19","access":"proprietary","comparison_data":{"Developer":"Google DeepMind","Release date":"2026-05-19","API model ID":"gemini-3.5-flash","Context window":"1M tokens","Max output":"64K tokens","Knowledge cutoff":"Jan 2025","Reasoning / effort":"minimal / low / medium / high thinking","Input / 1M tokens":"$1.50","Cached input / 1M":"$0.15","Output / 1M tokens":"$9","Batch / flex discount":"Batch: $0.75 input / $4.50 output","Text input":"Yes","Image / vision input":"Yes","Audio input":"Yes","Video input":"Yes","Text output":"Yes","Image output":"No","Audio output":"No","Video output":"No","Tool / function calling":"Yes","Computer use":"Yes (Preview)","API access":"Yes","Product access":"Gemini app + Google AI Studio + Gemini API + Antigravity + Gemini Enterprise","Weights / license":"Proprietary"},"sources":[{"title":"Gemini 3.5 Flash launch","url":"https://blog.google/innovation-and-ai/models-and-research/gemini-models/gemini-3-5/"},{"title":"Gemini 3.5 Flash model docs","url":"https://ai.google.dev/gemini-api/docs/models/gemini-3.5-flash"},{"title":"Gemini API pricing","url":"https://ai.google.dev/gemini-api/docs/pricing"},{"title":"Gemini 3.6 Flash model card","url":"https://deepmind.google/models/model-cards/gemini-3-6-flash/"}],"notes":null,"metadata":{"launch_stage":"ga","verification_pass":"gemini-core-2026-09-06"}},
  {"slug":"gemini-3-5-flash-lite","family":"Gemini 3.5","ga_date":"2026-07-21","access":"proprietary","comparison_data":{"Developer":"Google DeepMind","Release date":"2026-07-21","API model ID":"gemini-3.5-flash-lite","Context window":"1M tokens","Max output":"64K tokens","Reasoning / effort":"Thinking supported","Input / 1M tokens":"$0.30 text/image/video/audio","Cached input / 1M":"$0.03","Output / 1M tokens":"$2.50","Batch / flex discount":"Batch/Flex: $0.15 input / $1.25 output","Text input":"Yes","Image / vision input":"Yes","Audio input":"Yes","Video input":"Yes","Text output":"Yes","Image output":"No","Audio output":"No","Video output":"No","Tool / function calling":"Yes","Computer use":"Yes (Preview)","API access":"Yes","Product access":"Google AI Studio + Gemini API","Weights / license":"Proprietary"},"sources":[{"title":"Gemini 3.5 Flash-Lite model docs","url":"https://ai.google.dev/gemini-api/docs/models/gemini-3.5-flash-lite"},{"title":"Gemini API pricing","url":"https://ai.google.dev/gemini-api/docs/pricing"},{"title":"Gemini API release notes","url":"https://ai.google.dev/gemini-api/docs/changelog"}],"notes":null,"metadata":{"launch_stage":"ga","verification_pass":"gemini-core-2026-09-06"}},
  {"slug":"gemini-3-6-flash","family":"Gemini 3.6","ga_date":"2026-07-21","access":"proprietary","comparison_data":{"Developer":"Google DeepMind","Release date":"2026-07-21","API model ID":"gemini-3.6-flash","Context window":"1M tokens","Max output":"64K tokens","Reasoning / effort":"Thinking supported","Input / 1M tokens":"$0.75 introductory through Dec 31, 2026","Cached input / 1M":"$0.075 introductory through Dec 31, 2026","Output / 1M tokens":"$3.75 introductory through Dec 31, 2026","Text input":"Yes","Image / vision input":"Yes","Audio input":"Yes","Video input":"Yes","Text output":"Yes","Image output":"No","Audio output":"No","Video output":"No","Tool / function calling":"Yes","Computer use":"Yes (Preview)","API access":"Yes","Product access":"Google AI Studio + Gemini API + Gemini Enterprise","Weights / license":"Proprietary"},"sources":[{"title":"Gemini 3.6 Flash model docs","url":"https://ai.google.dev/gemini-api/docs/models/gemini-3.6-flash"},{"title":"Gemini 3.6 Flash launch","url":"https://blog.google/innovation-and-ai/models-and-research/gemini-models/gemini-3-6-flash-3-5-flash-lite-3-5-flash-cyber/"},{"title":"Gemini 3.7 Flash model card","url":"https://deepmind.google/models/model-cards/gemini-3-7-flash/"},{"title":"Gemini API pricing","url":"https://ai.google.dev/gemini-api/docs/pricing"}],"notes":"Current $0.75/$3.75 pricing is introductory through December 31, 2026; standard $1.50/$7.50 begins January 1, 2027.","metadata":{"launch_stage":"ga","verification_pass":"gemini-core-2026-09-06"}},
  {"slug":"gemini-3-7-flash","family":"Gemini 3.7","ga_date":"2026-08-13","access":"proprietary","comparison_data":{"Developer":"Google DeepMind","Release date":"2026-08-13","API model ID":"gemini-3.7-flash","Context window":"1M tokens","Max output":"64K tokens","Knowledge cutoff":"Mar 2026 (some domains Jan 2025)","Reasoning / effort":"low / medium / high; medium default","Input / 1M tokens":"$0.75 introductory through Dec 31, 2026","Cached input / 1M":"$0.075 introductory through Dec 31, 2026","Output / 1M tokens":"$3.75 introductory through Dec 31, 2026","Text input":"Yes","Image / vision input":"Yes","Audio input":"Yes","Video input":"Yes","Text output":"Yes","Image output":"No","Audio output":"No","Video output":"No","Tool / function calling":"Yes","Computer use":"Yes (Preview)","API access":"Yes","Product access":"Google AI Studio + Gemini API + Gemini Enterprise + Antigravity","Weights / license":"Proprietary"},"sources":[{"title":"Gemini 3.7 Flash model docs","url":"https://ai.google.dev/gemini-api/docs/models/gemini-3.7-flash"},{"title":"Gemini 3.7 Flash model card","url":"https://deepmind.google/models/model-cards/gemini-3-7-flash/"},{"title":"Gemini API pricing","url":"https://ai.google.dev/gemini-api/docs/pricing"}],"notes":"Current introductory pricing expires December 31, 2026; standard $1.50/$7.50 begins January 1, 2027.","metadata":{"launch_stage":"ga","verification_pass":"gemini-core-2026-09-06"}},
  {"slug":"gemini-3-8-flash","family":"Gemini 3.8","ga_date":"2026-09-02","access":"proprietary","comparison_data":{"Developer":"Google DeepMind","Release date":"2026-09-02","API model ID":"gemini-3.8-flash","Context window":"1M tokens","Max output":"64K tokens","Knowledge cutoff":"Mar 2026 (some domains Jan 2025)","Reasoning / effort":"low / medium / high; medium default","Input / 1M tokens":"$0.75 introductory through Dec 31, 2026","Cached input / 1M":"$0.075 introductory through Dec 31, 2026","Output / 1M tokens":"$3.75 introductory through Dec 31, 2026","Text input":"Yes","Image / vision input":"Yes","Audio input":"Yes","Video input":"Yes","Text output":"Yes","Image output":"No","Audio output":"No","Video output":"No","Tool / function calling":"Yes","Computer use":"Yes (Preview)","API access":"Yes","Product access":"Gemini app + Gemini Enterprise + Google AI Studio + Gemini API + AI Mode + Antigravity","Weights / license":"Proprietary"},"sources":[{"title":"Gemini 3.8 Flash model docs","url":"https://ai.google.dev/gemini-api/docs/models/gemini-3.8-flash"},{"title":"Gemini 3.8 Flash overview","url":"https://deepmind.google/models/gemini/flash/"},{"title":"Gemini API pricing","url":"https://ai.google.dev/gemini-api/docs/pricing"}],"notes":"Current introductory pricing expires December 31, 2026; standard $1.50/$7.50 begins January 1, 2027.","metadata":{"launch_stage":"ga","verification_pass":"gemini-core-2026-09-06"}}
]
$patches$::jsonb) AS p(slug text, family text, ga_date text, access text, comparison_data jsonb, sources jsonb, notes text, metadata jsonb)
)
UPDATE models AS m
SET family=COALESCE(p.family,m.family), ga_date=COALESCE(NULLIF(p.ga_date,'')::date,m.ga_date), access=COALESCE(p.access,m.access),
    comparison_data=COALESCE(m.comparison_data,'{}'::jsonb)||COALESCE(p.comparison_data,'{}'::jsonb),
    sources=CASE WHEN p.sources IS NULL OR jsonb_array_length(p.sources)=0 THEN m.sources ELSE p.sources END,
    notes=COALESCE(p.notes,m.notes), metadata=COALESCE(m.metadata,'{}'::jsonb)||COALESCE(p.metadata,'{}'::jsonb), verified_at=NOW(), updated_at=NOW()
FROM verified_patches p WHERE m.slug=p.slug;

INSERT INTO model_benchmarks (id,model_slug,category,benchmark_name,benchmark_version,score_numeric,score_display,score_unit,tools,reasoning_effort,harness,evaluator,evaluation_date,source,notes,updated_at)
SELECT b.id,b.model_slug,b.category,b.benchmark_name,b.benchmark_version,b.score_numeric,b.score_display,b.score_unit,b.tools,b.reasoning_effort,b.harness,b.evaluator,NULLIF(b.evaluation_date,'')::date,b.source,b.notes,NOW()
FROM jsonb_to_recordset($benchmarks$
[
 {"id":"gdm-202607-g31pro-swe-pro","model_slug":"gemini-3-1-pro","category":"coding","benchmark_name":"SWE-bench Pro","benchmark_version":"Public","score_numeric":54.2,"score_display":"54.2%","score_unit":"percent","tools":null,"reasoning_effort":null,"harness":"Gemini 3.6 Flash model-card comparison","evaluator":"Google DeepMind","evaluation_date":"2026-07-21","source":"https://deepmind.google/models/model-cards/gemini-3-6-flash/","notes":null},
 {"id":"gdm-202607-g31pro-deepswe","model_slug":"gemini-3-1-pro","category":"coding","benchmark_name":"DeepSWE v1.1","benchmark_version":null,"score_numeric":12.0,"score_display":"12%","score_unit":"percent","tools":null,"reasoning_effort":null,"harness":"Gemini 3.6 Flash model-card comparison","evaluator":"Google DeepMind","evaluation_date":"2026-07-21","source":"https://deepmind.google/models/model-cards/gemini-3-6-flash/","notes":null},
 {"id":"gdm-202607-g31pro-terminal21","model_slug":"gemini-3-1-pro","category":"coding","benchmark_name":"Terminal-Bench 2.1","benchmark_version":"Terminus-2","score_numeric":73.8,"score_display":"73.8%","score_unit":"percent","tools":null,"reasoning_effort":null,"harness":"Terminus-2","evaluator":"Google DeepMind","evaluation_date":"2026-07-21","source":"https://deepmind.google/models/model-cards/gemini-3-6-flash/","notes":null},
 {"id":"gdm-202607-g31pro-mle","model_slug":"gemini-3-1-pro","category":"coding","benchmark_name":"MLE-Bench","benchmark_version":null,"score_numeric":42.6,"score_display":"42.6%","score_unit":"percent","tools":null,"reasoning_effort":null,"harness":"Gemini 3.6 Flash model-card comparison","evaluator":"Google DeepMind","evaluation_date":"2026-07-21","source":"https://deepmind.google/models/model-cards/gemini-3-6-flash/","notes":null},
 {"id":"gdm-202607-g31pro-gdpv2","model_slug":"gemini-3-1-pro","category":"agentic_computer_use","benchmark_name":"GDPval-AA v2","benchmark_version":null,"score_numeric":965,"score_display":"965 Elo","score_unit":"Elo","tools":true,"reasoning_effort":null,"harness":"Artificial Analysis","evaluator":"Google DeepMind","evaluation_date":"2026-07-21","source":"https://deepmind.google/models/model-cards/gemini-3-6-flash/","notes":null},
 {"id":"gdm-202607-g31pro-osworld-verified","model_slug":"gemini-3-1-pro","category":"agentic_computer_use","benchmark_name":"OSWorld-Verified","benchmark_version":null,"score_numeric":76.2,"score_display":"76.2%","score_unit":"percent","tools":true,"reasoning_effort":null,"harness":"Gemini 3.6 Flash model-card comparison","evaluator":"Google DeepMind","evaluation_date":"2026-07-21","source":"https://deepmind.google/models/model-cards/gemini-3-6-flash/","notes":null},

 {"id":"gdm-202607-g35-swe-pro","model_slug":"gemini-3-5-flash","category":"coding","benchmark_name":"SWE-bench Pro","benchmark_version":"Public","score_numeric":55.1,"score_display":"55.1%","score_unit":"percent","tools":null,"reasoning_effort":null,"harness":"Gemini 3.6 Flash model-card comparison","evaluator":"Google DeepMind","evaluation_date":"2026-07-21","source":"https://deepmind.google/models/model-cards/gemini-3-6-flash/","notes":null},
 {"id":"gdm-202607-g35-deepswe","model_slug":"gemini-3-5-flash","category":"coding","benchmark_name":"DeepSWE v1.1","benchmark_version":null,"score_numeric":37.0,"score_display":"37%","score_unit":"percent","tools":null,"reasoning_effort":null,"harness":"Gemini 3.6 Flash model-card comparison","evaluator":"Google DeepMind","evaluation_date":"2026-07-21","source":"https://deepmind.google/models/model-cards/gemini-3-6-flash/","notes":null},
 {"id":"gdm-202605-g35-terminal21","model_slug":"gemini-3-5-flash","category":"coding","benchmark_name":"Terminal-Bench 2.1","benchmark_version":null,"score_numeric":76.2,"score_display":"76.2%","score_unit":"percent","tools":null,"reasoning_effort":null,"harness":"Gemini 3.5 launch evaluation","evaluator":"Google DeepMind","evaluation_date":"2026-05-19","source":"https://blog.google/innovation-and-ai/models-and-research/gemini-models/gemini-3-5/","notes":null},
 {"id":"gdm-202607-g35-mle","model_slug":"gemini-3-5-flash","category":"coding","benchmark_name":"MLE-Bench","benchmark_version":null,"score_numeric":49.7,"score_display":"49.7%","score_unit":"percent","tools":null,"reasoning_effort":null,"harness":"Gemini 3.6 Flash model-card comparison","evaluator":"Google DeepMind","evaluation_date":"2026-07-21","source":"https://deepmind.google/models/model-cards/gemini-3-6-flash/","notes":null},
 {"id":"gdm-202607-g35-gdpv2","model_slug":"gemini-3-5-flash","category":"agentic_computer_use","benchmark_name":"GDPval-AA v2","benchmark_version":null,"score_numeric":1349,"score_display":"1349 Elo","score_unit":"Elo","tools":true,"reasoning_effort":null,"harness":"Artificial Analysis","evaluator":"Google DeepMind","evaluation_date":"2026-07-21","source":"https://deepmind.google/models/model-cards/gemini-3-6-flash/","notes":"Do not conflate with the May launch GDPval-AA result of 1656 Elo; this is GDPVal-AA v2."},
 {"id":"gdm-202607-g35-osworld-verified","model_slug":"gemini-3-5-flash","category":"agentic_computer_use","benchmark_name":"OSWorld-Verified","benchmark_version":null,"score_numeric":78.4,"score_display":"78.4%","score_unit":"percent","tools":true,"reasoning_effort":null,"harness":"Gemini 3.6 Flash model-card comparison","evaluator":"Google DeepMind","evaluation_date":"2026-07-21","source":"https://deepmind.google/models/model-cards/gemini-3-6-flash/","notes":null},
 {"id":"google-202605-g35-mcp-atlas","model_slug":"gemini-3-5-flash","category":"agentic_computer_use","benchmark_name":"MCP Atlas","benchmark_version":null,"score_numeric":83.6,"score_display":"83.6%","score_unit":"percent","tools":true,"reasoning_effort":null,"harness":"Gemini 3.5 launch evaluation","evaluator":"Google DeepMind","evaluation_date":"2026-05-19","source":"https://blog.google/innovation-and-ai/models-and-research/gemini-models/gemini-3-5/","notes":null},

 {"id":"gdm-202607-g36-swe-pro","model_slug":"gemini-3-6-flash","category":"coding","benchmark_name":"SWE-bench Pro","benchmark_version":"Public","score_numeric":58.7,"score_display":"58.7%","score_unit":"percent","tools":null,"reasoning_effort":null,"harness":"Gemini 3.6 Flash model card","evaluator":"Google DeepMind","evaluation_date":"2026-07-21","source":"https://deepmind.google/models/model-cards/gemini-3-6-flash/","notes":null},
 {"id":"gdm-202608-g36-frontiercode-main","model_slug":"gemini-3-6-flash","category":"coding","benchmark_name":"FrontierCode 1.1 Main","benchmark_version":null,"score_numeric":34.4,"score_display":"34.4%","score_unit":"percent","tools":null,"reasoning_effort":null,"harness":"Gemini 3.7 Flash model-card comparison","evaluator":"Google DeepMind","evaluation_date":"2026-08-13","source":"https://deepmind.google/models/model-cards/gemini-3-7-flash/","notes":null},
 {"id":"gdm-202608-g36-deepswe","model_slug":"gemini-3-6-flash","category":"coding","benchmark_name":"DeepSWE v1.1","benchmark_version":null,"score_numeric":48.6,"score_display":"48.6%","score_unit":"percent","tools":null,"reasoning_effort":null,"harness":"Gemini 3.7 Flash model-card comparison","evaluator":"Google DeepMind","evaluation_date":"2026-08-13","source":"https://deepmind.google/models/model-cards/gemini-3-7-flash/","notes":null},
 {"id":"gdm-202608-g36-terminal21","model_slug":"gemini-3-6-flash","category":"coding","benchmark_name":"Terminal-Bench 2.1","benchmark_version":null,"score_numeric":78.0,"score_display":"78.0%","score_unit":"percent","tools":null,"reasoning_effort":null,"harness":"Gemini 3.7 Flash model-card comparison","evaluator":"Google DeepMind","evaluation_date":"2026-08-13","source":"https://deepmind.google/models/model-cards/gemini-3-7-flash/","notes":null},
 {"id":"gdm-202608-g36-terminal30","model_slug":"gemini-3-6-flash","category":"coding","benchmark_name":"Terminal-Bench 3.0","benchmark_version":null,"score_numeric":5.4,"score_display":"5.4%","score_unit":"percent","tools":null,"reasoning_effort":null,"harness":"Gemini 3.7 Flash model-card comparison","evaluator":"Google DeepMind","evaluation_date":"2026-08-13","source":"https://deepmind.google/models/model-cards/gemini-3-7-flash/","notes":null},
 {"id":"gdm-202607-g36-mle","model_slug":"gemini-3-6-flash","category":"coding","benchmark_name":"MLE-Bench","benchmark_version":null,"score_numeric":63.9,"score_display":"63.9%","score_unit":"percent","tools":null,"reasoning_effort":null,"harness":"Gemini 3.6 Flash model card","evaluator":"Google DeepMind","evaluation_date":"2026-07-21","source":"https://deepmind.google/models/model-cards/gemini-3-6-flash/","notes":null},
 {"id":"gdm-202608-g36-automation","model_slug":"gemini-3-6-flash","category":"agentic_computer_use","benchmark_name":"AutomationBench","benchmark_version":"Private set","score_numeric":17.0,"score_display":"17.0%","score_unit":"percent","tools":true,"reasoning_effort":null,"harness":"Gemini 3.7 Flash model-card comparison","evaluator":"Google DeepMind","evaluation_date":"2026-08-13","source":"https://deepmind.google/models/model-cards/gemini-3-7-flash/","notes":null},
 {"id":"gdm-202608-g36-gdpv2","model_slug":"gemini-3-6-flash","category":"agentic_computer_use","benchmark_name":"GDPval-AA v2","benchmark_version":null,"score_numeric":1422,"score_display":"1422 Elo","score_unit":"Elo","tools":true,"reasoning_effort":null,"harness":"Artificial Analysis","evaluator":"Google DeepMind","evaluation_date":"2026-08-13","source":"https://deepmind.google/models/model-cards/gemini-3-7-flash/","notes":null},
 {"id":"gdm-202607-g36-osworld-verified","model_slug":"gemini-3-6-flash","category":"agentic_computer_use","benchmark_name":"OSWorld-Verified","benchmark_version":null,"score_numeric":83.0,"score_display":"83.0%","score_unit":"percent","tools":true,"reasoning_effort":null,"harness":"Gemini 3.6 Flash model card","evaluator":"Google DeepMind","evaluation_date":"2026-07-21","source":"https://deepmind.google/models/model-cards/gemini-3-6-flash/","notes":null},
 {"id":"gdm-202608-g36-osworld20","model_slug":"gemini-3-6-flash","category":"agentic_computer_use","benchmark_name":"OSWorld 2.0","benchmark_version":null,"score_numeric":33.8,"score_display":"33.8%","score_unit":"percent","tools":true,"reasoning_effort":null,"harness":"Gemini 3.7 Flash model-card comparison","evaluator":"Google DeepMind","evaluation_date":"2026-08-13","source":"https://deepmind.google/models/model-cards/gemini-3-7-flash/","notes":null},
 {"id":"gdm-202608-g36-agents-last-exam","model_slug":"gemini-3-6-flash","category":"agentic_computer_use","benchmark_name":"Agents' Last Exam","benchmark_version":null,"score_numeric":24.2,"score_display":"24.2%","score_unit":"percent","tools":true,"reasoning_effort":null,"harness":"Gemini 3.7 Flash model-card comparison","evaluator":"Google DeepMind","evaluation_date":"2026-08-13","source":"https://deepmind.google/models/model-cards/gemini-3-7-flash/","notes":"Google's table labels this benchmark Agent's Last Exam; normalized here to the catalog label."},
 {"id":"gdm-202608-g36-hleverified","model_slug":"gemini-3-6-flash","category":"knowledge","benchmark_name":"HLE-Verified","benchmark_version":null,"score_numeric":51.2,"score_display":"51.2%","score_unit":"percent","tools":null,"reasoning_effort":null,"harness":"Gemini 3.7 Flash model-card comparison","evaluator":"Google DeepMind","evaluation_date":"2026-08-13","source":"https://deepmind.google/models/model-cards/gemini-3-7-flash/","notes":null},

 {"id":"gdm-202608-g37-frontiercode-main","model_slug":"gemini-3-7-flash","category":"coding","benchmark_name":"FrontierCode 1.1 Main","benchmark_version":null,"score_numeric":43.6,"score_display":"43.6%","score_unit":"percent","tools":null,"reasoning_effort":null,"harness":"Gemini 3.7 Flash model card","evaluator":"Google DeepMind","evaluation_date":"2026-08-13","source":"https://deepmind.google/models/model-cards/gemini-3-7-flash/","notes":null},
 {"id":"gdm-202608-g37-deepswe","model_slug":"gemini-3-7-flash","category":"coding","benchmark_name":"DeepSWE v1.1","benchmark_version":null,"score_numeric":65.3,"score_display":"65.3%","score_unit":"percent","tools":null,"reasoning_effort":null,"harness":"Gemini 3.7 Flash model card","evaluator":"Google DeepMind","evaluation_date":"2026-08-13","source":"https://deepmind.google/models/model-cards/gemini-3-7-flash/","notes":null},
 {"id":"gdm-202608-g37-terminal21","model_slug":"gemini-3-7-flash","category":"coding","benchmark_name":"Terminal-Bench 2.1","benchmark_version":null,"score_numeric":85.8,"score_display":"85.8%","score_unit":"percent","tools":null,"reasoning_effort":null,"harness":"Gemini 3.7 Flash model card","evaluator":"Google DeepMind","evaluation_date":"2026-08-13","source":"https://deepmind.google/models/model-cards/gemini-3-7-flash/","notes":null},
 {"id":"gdm-202608-g37-terminal30","model_slug":"gemini-3-7-flash","category":"coding","benchmark_name":"Terminal-Bench 3.0","benchmark_version":null,"score_numeric":14.9,"score_display":"14.9%","score_unit":"percent","tools":null,"reasoning_effort":null,"harness":"Gemini 3.7 Flash model card","evaluator":"Google DeepMind","evaluation_date":"2026-08-13","source":"https://deepmind.google/models/model-cards/gemini-3-7-flash/","notes":null},
 {"id":"gdm-202608-g37-automation","model_slug":"gemini-3-7-flash","category":"agentic_computer_use","benchmark_name":"AutomationBench","benchmark_version":"Private set","score_numeric":30.4,"score_display":"30.4%","score_unit":"percent","tools":true,"reasoning_effort":null,"harness":"Gemini 3.7 Flash model card","evaluator":"Google DeepMind","evaluation_date":"2026-08-13","source":"https://deepmind.google/models/model-cards/gemini-3-7-flash/","notes":null},
 {"id":"gdm-202608-g37-gdpv2","model_slug":"gemini-3-7-flash","category":"agentic_computer_use","benchmark_name":"GDPval-AA v2","benchmark_version":null,"score_numeric":1525,"score_display":"1525 Elo","score_unit":"Elo","tools":true,"reasoning_effort":null,"harness":"Artificial Analysis","evaluator":"Google DeepMind","evaluation_date":"2026-08-13","source":"https://deepmind.google/models/model-cards/gemini-3-7-flash/","notes":null},
 {"id":"gdm-202608-g37-osworld20","model_slug":"gemini-3-7-flash","category":"agentic_computer_use","benchmark_name":"OSWorld 2.0","benchmark_version":null,"score_numeric":47.9,"score_display":"47.9%","score_unit":"percent","tools":true,"reasoning_effort":null,"harness":"Gemini 3.7 Flash model card","evaluator":"Google DeepMind","evaluation_date":"2026-08-13","source":"https://deepmind.google/models/model-cards/gemini-3-7-flash/","notes":null},
 {"id":"gdm-202608-g37-agents-last-exam","model_slug":"gemini-3-7-flash","category":"agentic_computer_use","benchmark_name":"Agents' Last Exam","benchmark_version":null,"score_numeric":26.3,"score_display":"26.3%","score_unit":"percent","tools":true,"reasoning_effort":null,"harness":"Gemini 3.7 Flash model card","evaluator":"Google DeepMind","evaluation_date":"2026-08-13","source":"https://deepmind.google/models/model-cards/gemini-3-7-flash/","notes":"Google's table labels this benchmark Agent's Last Exam; normalized here to the catalog label."},
 {"id":"gdm-202608-g37-hleverified","model_slug":"gemini-3-7-flash","category":"knowledge","benchmark_name":"HLE-Verified","benchmark_version":null,"score_numeric":53.6,"score_display":"53.6%","score_unit":"percent","tools":null,"reasoning_effort":null,"harness":"Gemini 3.7 Flash model card","evaluator":"Google DeepMind","evaluation_date":"2026-08-13","source":"https://deepmind.google/models/model-cards/gemini-3-7-flash/","notes":null},

 {"id":"gdm-202609-g38-hleverified","model_slug":"gemini-3-8-flash","category":"knowledge","benchmark_name":"HLE-Verified","benchmark_version":null,"score_numeric":54.9,"score_display":"54.9%","score_unit":"percent","tools":null,"reasoning_effort":null,"harness":"Gemini 3.8 Flash launch evaluation","evaluator":"Google DeepMind","evaluation_date":"2026-09-02","source":"https://deepmind.google/models/gemini/flash/","notes":null}
]
$benchmarks$::jsonb) AS b(id text,model_slug text,category text,benchmark_name text,benchmark_version text,score_numeric double precision,score_display text,score_unit text,tools boolean,reasoning_effort text,harness text,evaluator text,evaluation_date text,source text,notes text)
ON CONFLICT (id) DO UPDATE SET model_slug=EXCLUDED.model_slug,category=EXCLUDED.category,benchmark_name=EXCLUDED.benchmark_name,benchmark_version=EXCLUDED.benchmark_version,score_numeric=EXCLUDED.score_numeric,score_display=EXCLUDED.score_display,score_unit=EXCLUDED.score_unit,tools=EXCLUDED.tools,reasoning_effort=EXCLUDED.reasoning_effort,harness=EXCLUDED.harness,evaluator=EXCLUDED.evaluator,evaluation_date=EXCLUDED.evaluation_date,source=EXCLUDED.source,notes=EXCLUDED.notes,updated_at=NOW();