-- First-party enrichment for specialized Gemini image, live/audio, TTS, and Omni records.
-- Google AI / DeepMind sources checked 2026-09-06.

WITH verified_patches AS (
  SELECT * FROM jsonb_to_recordset($patches$
[
 {"slug":"gemini-3-1-flash-image","family":"Gemini 3.1","ga_date":"2026-05-28","access":"proprietary","comparison_data":{"Developer":"Google DeepMind","Release date":"2026-02-26","API model ID":"gemini-3.1-flash-image","Context window":"128K tokens","Max output":"32K tokens","Reasoning / effort":"Thinking supported","Input / 1M tokens":"$0.50 text/image","Output / 1M tokens":"$3 text/thinking / $60 image tokens","Batch / flex discount":"Batch: $0.25 input; $1.50 text/thinking / $30 image tokens output","Text input":"Yes","Image / vision input":"Yes","Audio input":"No","Video input":"Yes","Text output":"Yes","Image output":"Yes (0.5K/1K/2K/4K)","Audio output":"No","Video output":"No","Tool / function calling":"No","Computer use":"No","API access":"Yes","Product access":"Google AI Studio + Gemini API","Weights / license":"Proprietary"},"sources":[{"title":"Gemini 3.1 Flash Image model docs","url":"https://ai.google.dev/gemini-api/docs/models/gemini-3.1-flash-image"},{"title":"Gemini API pricing","url":"https://ai.google.dev/gemini-api/docs/pricing"},{"title":"Gemini deprecations","url":"https://ai.google.dev/gemini-api/docs/deprecations"}],"notes":"Nano Banana 2 preview launched February 26; stable endpoint reached GA May 28, 2026.","metadata":{"specialization":"image generation and editing","launch_stage":"preview_then_ga","verification_pass":"gemini-specialized-2026-09-06"}},
 {"slug":"gemini-3-1-flash-live","family":"Gemini 3.1","ga_date":null,"access":"proprietary","comparison_data":{"Developer":"Google DeepMind","Release date":"2026-03-26","API model ID":"gemini-3.1-flash-live-preview","Context window":"128K tokens","Max output":"64K tokens","Knowledge cutoff":"Jan 2025","Reasoning / effort":"minimal / low / medium / high; minimal default","Input / 1M tokens":"$0.75 text / $3 audio / $1 image-video","Output / 1M tokens":"$4.50 text / $12 audio","Text input":"Yes","Image / vision input":"Yes","Audio input":"Yes","Video input":"Yes","Text output":"Yes","Image output":"No","Audio output":"Yes","Video output":"No","Tool / function calling":"Yes (synchronous)","Computer use":"No native computer-use tool documented","API access":"Preview via Live API","Product access":"Google AI Studio + Gemini Live API","Weights / license":"Proprietary"},"sources":[{"title":"Gemini 3.1 Flash Live model docs","url":"https://ai.google.dev/gemini-api/docs/models/gemini-3.1-flash-live-preview"},{"title":"Gemini API pricing","url":"https://ai.google.dev/gemini-api/docs/pricing"}],"notes":"Low-latency audio-to-audio preview model; async function calling is not supported.","metadata":{"specialization":"realtime multimodal audio","launch_stage":"preview","verification_pass":"gemini-specialized-2026-09-06"}},
 {"slug":"gemini-3-1-flash-tts","family":"Gemini 3.1","ga_date":null,"access":"proprietary","comparison_data":{"Developer":"Google DeepMind","Release date":"2026-04-15","API model ID":"gemini-3.1-flash-tts-preview","Context window":"8K tokens","Max output":"16K tokens","Knowledge cutoff":"Jan 2025","Reasoning / effort":"Not supported","Input / 1M tokens":"$1 text","Output / 1M tokens":"$20 audio","Batch / flex discount":"Batch: $0.50 input / $10 audio output","Text input":"Yes","Image / vision input":"No","Audio input":"No","Video input":"No","Text output":"No","Image output":"No","Audio output":"Yes","Video output":"No","Tool / function calling":"No","Computer use":"No","API access":"Preview","Product access":"Google AI Studio + Gemini API","Weights / license":"Proprietary"},"sources":[{"title":"Gemini 3.1 Flash TTS model docs","url":"https://ai.google.dev/gemini-api/docs/models/gemini-3.1-flash-tts-preview"},{"title":"Gemini API pricing","url":"https://ai.google.dev/gemini-api/docs/pricing"}],"notes":null,"metadata":{"specialization":"text-to-speech","launch_stage":"preview","verification_pass":"gemini-specialized-2026-09-06"}},
 {"slug":"gemini-3-1-flash-lite-image","family":"Gemini 3.1","ga_date":"2026-06-30","access":"proprietary","comparison_data":{"Developer":"Google DeepMind","Release date":"2026-06-30","API model ID":"gemini-3.1-flash-lite-image","Context window":"64K tokens","Max output":"4K tokens","Reasoning / effort":"minimal / high thinking","Input / 1M tokens":"$0.25 text/image/video","Output / 1M tokens":"$1.50 text/thinking / $30 image tokens","Batch / flex discount":"Batch: $0.125 input; $0.75 text/thinking / $15 image tokens output","Text input":"Yes","Image / vision input":"Yes","Audio input":"No","Video input":"Yes","Text output":"Yes","Image output":"Yes (1K)","Audio output":"No","Video output":"No","Tool / function calling":"Yes","Computer use":"No","API access":"Yes","Product access":"Google AI Studio + Gemini API","Weights / license":"Proprietary"},"sources":[{"title":"Gemini 3.1 Flash-Lite Image model docs","url":"https://ai.google.dev/gemini-api/docs/models/gemini-3.1-flash-lite-image"},{"title":"Gemini API pricing","url":"https://ai.google.dev/gemini-api/docs/pricing"},{"title":"Gemini API release notes","url":"https://ai.google.dev/gemini-api/docs/changelog"}],"notes":"Nano Banana 2 Lite is the low-latency 1K image-generation/editing variant.","metadata":{"specialization":"efficient image generation and editing","launch_stage":"ga","verification_pass":"gemini-specialized-2026-09-06"}},
 {"slug":"gemini-3-5-audio","family":"Gemini 3.5","ga_date":null,"access":"proprietary","comparison_data":{"Developer":"Google DeepMind","Release date":"2026-08-26","API model ID":"gemini-3.5-live-translate-preview / gemini-3.5-transcribe / gemini-3.5-transcribe-live","Context window":"128K Live Translate / 96K Transcribe","Max output":"64K Live Translate / 32K Transcribe","Knowledge cutoff":"Jan 2025","Input / 1M tokens":"Live Translate: $3.50 audio (~$0.0053/min)","Output / 1M tokens":"Live Translate: $21 audio (~$0.0315/min)","Text input":"Yes","Image / vision input":"No in documented Audio variants","Audio input":"Yes","Video input":"No in documented Audio variants","Text output":"Yes","Image output":"No","Audio output":"Yes (Live Translate)","Video output":"No","Tool / function calling":"Variant-dependent","Computer use":"No native computer-use tool documented","API access":"Yes / preview depending variant","Product access":"Gemini API + Google AI Studio; Transcribe variants also Gemini app/Vertex AI and other Google products","Weights / license":"Proprietary"},"sources":[{"title":"Gemini 3.5 Audio model card","url":"https://deepmind.google/models/model-cards/gemini-3-5-audio/"},{"title":"Gemini API pricing","url":"https://ai.google.dev/gemini-api/docs/pricing"}],"notes":"Catalog row groups Live Translate, Transcribe and Transcribe Live; capabilities and limits differ by variant.","metadata":{"specialization":"audio translation and transcription","launch_stage":"mixed","verification_pass":"gemini-specialized-2026-09-06"}},
 {"slug":"gemini-omni-flash","family":"Gemini Omni","ga_date":null,"access":"proprietary","comparison_data":{"Developer":"Google DeepMind","Release date":"2026-05-19","API model ID":"gemini-omni-flash-preview (API preview Jun 30)","Context window":"1M tokens","Max output":"3-10s video, 720p, 24 FPS","Input / 1M tokens":"$1.50 text/image/video/audio","Output / 1M tokens":"$9 text / $17.50 video (~$0.10/sec at 720p)","Text input":"Yes","Image / vision input":"Yes","Audio input":"Yes (model family/card; preview API docs vary)","Video input":"Yes","Text output":"Not primary output","Image output":"No","Audio output":"Yes, generated with video","Video output":"Yes","Tool / function calling":"No general function-calling interface documented","Computer use":"No","API access":"Preview from Jun 30","Product access":"Gemini app + YouTube + Google Flow; paid Gemini API preview","Weights / license":"Proprietary"},"sources":[{"title":"Gemini Omni Flash API model docs","url":"https://ai.google.dev/gemini-api/docs/models/gemini-omni-flash"},{"title":"Gemini Omni Flash model card","url":"https://deepmind.google/models/model-cards/gemini-omni-flash/"},{"title":"Gemini API pricing","url":"https://ai.google.dev/gemini-api/docs/pricing"}],"notes":"Gemini Omni Flash was introduced at I/O in May; the developer API preview followed June 30.","metadata":{"specialization":"video generation and conversational editing","launch_stage":"product_then_api_preview","verification_pass":"gemini-specialized-2026-09-06"}},
 {"slug":"gemini-omni-1-1-flash","family":"Gemini Omni","ga_date":"2026-08-27","access":"proprietary","comparison_data":{"Developer":"Google DeepMind","Release date":"2026-08-27","API model ID":"gemini-omni-1.1-flash","Context window":"1M-token family architecture; API-specific limit not separately disclosed on launch page","Max output":"Video generation with 4K upscaling; scene extension and frame interpolation","Text input":"Yes","Image / vision input":"Yes","Audio input":"Yes","Video input":"Yes","Text output":"Not primary output","Image output":"No","Audio output":"Yes, generated with video","Video output":"Yes","Tool / function calling":"No general function-calling interface documented","Computer use":"No","API access":"Yes","Product access":"Google AI Studio + Gemini Enterprise Agent Platform + Gemini app + Google Flow","Weights / license":"Proprietary"},"sources":[{"title":"Gemini Omni 1.1 Flash announcement","url":"https://blog.google/innovation-and-ai/technology/developers-tools/build-with-gemini-omni-1-1-flash/"},{"title":"Gemini Omni Flash model card","url":"https://deepmind.google/models/model-cards/gemini-omni-flash/"},{"title":"Gemini API models","url":"https://ai.google.dev/gemini-api/docs/models"}],"notes":"Production-ready August update adding scene extension, first/last-frame interpolation and high-resolution upscaling. The current pricing page still labels the Omni preview endpoint, so no unverified 1.1-specific token price is copied here.","metadata":{"specialization":"production video generation and editing","launch_stage":"ga","verification_pass":"gemini-specialized-2026-09-06"}}
]
$patches$::jsonb) AS p(slug text,family text,ga_date text,access text,comparison_data jsonb,sources jsonb,notes text,metadata jsonb)
)
UPDATE models AS m
SET family=COALESCE(p.family,m.family),ga_date=COALESCE(NULLIF(p.ga_date,'')::date,m.ga_date),access=COALESCE(p.access,m.access),
    comparison_data=COALESCE(m.comparison_data,'{}'::jsonb)||COALESCE(p.comparison_data,'{}'::jsonb),
    sources=CASE WHEN p.sources IS NULL OR jsonb_array_length(p.sources)=0 THEN m.sources ELSE p.sources END,
    notes=COALESCE(p.notes,m.notes),metadata=COALESCE(m.metadata,'{}'::jsonb)||COALESCE(p.metadata,'{}'::jsonb),verified_at=NOW(),updated_at=NOW()
FROM verified_patches p WHERE m.slug=p.slug;