-- Verified enrichment for Meta Muse Spark 1.0-1.3 and Muse Glimmer.
-- Meta AI / Meta Research primary sources checked 2026-09-06.

WITH verified_patches AS (
  SELECT * FROM jsonb_to_recordset($patches$
[
 {"slug":"muse-spark","family":"Muse Spark","ga_date":"2026-04-08","access":"proprietary","comparison_data":{"Developer":"Meta","Release date":"2026-04-08","Reasoning / effort":"Native reasoning; Contemplating mode uses parallel multi-agent test-time reasoning","Text input":"Yes","Image / vision input":"Yes","Text output":"Yes","Tool / function calling":"Yes","API access":"Private preview at launch","Product access":"Meta AI + meta.ai","Weights / license":"Proprietary"},"sources":[{"title":"Introducing Muse Spark","url":"https://ai.meta.com/blog/introducing-muse-spark-msl/"}],"notes":"First Muse model. Meta described native multimodal reasoning, visual chain of thought, tool use and multi-agent orchestration. The launch post does not disclose a precise audio/video API modality matrix or token limits, so those fields remain unset.","metadata":{"launch_stage":"ga_product_private_api","verification_pass":"muse-family-2026-09-06"}},
 {"slug":"muse-spark-1-1","family":"Muse Spark","ga_date":"2026-07-09","access":"proprietary","comparison_data":{"Developer":"Meta","Release date":"2026-07-09","Context window":"1M tokens","Reasoning / effort":"Thinking mode; long-horizon planning with compaction and multi-agent orchestration","Text input":"Yes","Image / vision input":"Yes","Audio input":"Yes","Video input":"Yes","Text output":"Yes","Tool / function calling":"Yes; native tools, MCP and custom skills","Computer use":"Yes","API access":"Meta Model API public preview","Product access":"Meta AI + Muse Code + Meta Model API","Weights / license":"Proprietary"},"sources":[{"title":"Muse Spark 1.1 and Meta Model API","url":"https://research.meta.ai/blog/introducing-muse-spark-meta-model-api"}],"notes":"Meta documents 1M context and perception across images, video and audio for the 1.1 agentic model. No first-party token price was disclosed in the launch material reviewed, so pricing is intentionally blank.","metadata":{"launch_stage":"public_api_preview","verification_pass":"muse-family-2026-09-06"}},
 {"slug":"muse-spark-1-2","family":"Muse Spark","ga_date":"2026-08-05","access":"proprietary","comparison_data":{"Developer":"Meta","Release date":"2026-08-05","Reasoning / effort":"Long-horizon reasoning with compaction and subagents","Input / 1M tokens":"$1.25 (Google DeepMind comparison table)","Output / 1M tokens":"$4.25 (Google DeepMind comparison table)","Text input":"Yes","Image / vision input":"Yes","Audio input":"Yes","Video input":"Yes","Text output":"Yes","Tool / function calling":"Yes","Computer use":"Yes; agentic computer/code workflows","API access":"Meta Model API","Product access":"Muse Code + Meta Model API + Meta AI","Weights / license":"Proprietary; Meta said open weights were forthcoming but had not released them as of Sep 6, 2026"},"sources":[{"title":"Introducing Muse Code and Muse Spark 1.2","url":"https://research.meta.ai/blog/introducing-muse-code-and-muse-spark-1-2"},{"title":"Multimodal intelligence of Muse Spark 1.2","url":"https://research.meta.ai/blog/multimodal-intelligence-of-muse-spark-1-2"},{"title":"Gemini 3.7 Flash model card comparison","url":"https://deepmind.google/models/model-cards/gemini-3-7-flash/"}],"notes":"The modality claims come from Meta's 1.2 multimodal report. Price and the normalized cross-vendor benchmark rows below come from Google DeepMind's Gemini 3.7 comparison table and are labeled with Google as evaluator.","metadata":{"launch_stage":"ga_hosted","open_weights_status":"announced_not_released","verification_pass":"muse-family-2026-09-06"}},
 {"slug":"muse-spark-1-3","family":"Muse Spark","ga_date":"2026-09-02","access":"proprietary","comparison_data":{"Developer":"Meta","Release date":"2026-09-02","Reasoning / effort":"Max reasoning available; optimized long-horizon agentic workflows","Text input":"Yes","Image / vision input":"Multimodal workflows supported","Audio input":"Multimodal file workflows demonstrated; exact API modality matrix not separately disclosed","Video input":"Multimodal file workflows demonstrated; exact API modality matrix not separately disclosed","Text output":"Yes","Tool / function calling":"Yes","Computer use":"Yes; long-horizon agentic workflows","API access":"Meta Model API","Product access":"Muse Code + Meta Model API + Meta AI","Weights / license":"Proprietary; Meta still described open weights as a future release"},"sources":[{"title":"Introducing Muse Spark 1.3","url":"https://research.meta.ai/blog/introducing-muse-spark-1-3"}],"notes":"Meta reports roughly 20% fewer tool calls and 25% fewer tokens than 1.2 in internal engineer comparisons. No unambiguous first-party token price or public benchmark score table was available in the launch material reviewed, so those fields are not inferred.","metadata":{"launch_stage":"ga_hosted","open_weights_status":"future_release","verification_pass":"muse-family-2026-09-06"}},
 {"slug":"muse-glimmer","family":"Muse","ga_date":"2026-08-10","access":"open_source","comparison_data":{"Developer":"Meta","Release date":"2026-08-10","Reasoning / effort":"Controllable reasoning effort","Text input":"Yes","Image / vision input":"Yes; interleaved text/image input","Audio input":"No native audio support documented","Video input":"No native video support documented","Text output":"Yes","Tool / function calling":"Yes","Computer use":"Via screenshot-driven/agent scaffolds; not a hosted native computer-use tool","API access":"Self-hosted and third-party serving","Product access":"Downloadable weights + agent scaffolds such as OpenClaw","Weights / license":"Open source — Apache 2.0"},"sources":[{"title":"Introducing Muse Glimmer","url":"https://research.meta.ai/blog/introducing-muse-glimmer-open-agentic-model"}],"notes":"30B local-agent model, 100+ languages. Meta published weights under Apache 2.0; a 4-bit K-Quant build is under 20GB. The launch report discusses long-context memory but does not disclose one canonical token limit, so Context window remains unset.","metadata":{"parameters_total":"30B","languages":"100+","verification_pass":"muse-family-2026-09-06"}}
]
$patches$::jsonb) AS p(slug text,family text,ga_date text,access text,comparison_data jsonb,sources jsonb,notes text,metadata jsonb)
)
UPDATE models AS m
SET family=COALESCE(p.family,m.family),ga_date=COALESCE(NULLIF(p.ga_date,'')::date,m.ga_date),access=COALESCE(p.access,m.access),
    comparison_data=COALESCE(m.comparison_data,'{}'::jsonb)||COALESCE(p.comparison_data,'{}'::jsonb),
    sources=CASE WHEN p.sources IS NULL OR jsonb_array_length(p.sources)=0 THEN m.sources ELSE p.sources END,
    notes=COALESCE(p.notes,m.notes),metadata=COALESCE(m.metadata,'{}'::jsonb)||COALESCE(p.metadata,'{}'::jsonb),verified_at=NOW(),updated_at=NOW()
FROM verified_patches p WHERE m.slug=p.slug;

INSERT INTO model_benchmarks (id,model_slug,category,benchmark_name,benchmark_version,score_numeric,score_display,score_unit,tools,reasoning_effort,harness,evaluator,evaluation_date,source,notes,updated_at)
SELECT b.id,b.model_slug,b.category,b.benchmark_name,b.benchmark_version,b.score_numeric,b.score_display,b.score_unit,b.tools,b.reasoning_effort,b.harness,b.evaluator,NULLIF(b.evaluation_date,'')::date,b.source,b.notes,NOW()
FROM jsonb_to_recordset($benchmarks$
[
 {"id":"meta-20260408-muse-spark-hle-contemplating","model_slug":"muse-spark","category":"knowledge","benchmark_name":"Humanity's Last Exam","benchmark_version":null,"score_numeric":58.0,"score_display":"58%","score_unit":"percent","tools":null,"reasoning_effort":"Contemplating","harness":"Muse Spark launch evaluation","evaluator":"Meta","evaluation_date":"2026-04-08","source":"https://ai.meta.com/blog/introducing-muse-spark-msl/","notes":"Contemplating mode uses parallel multi-agent test-time reasoning."},
 {"id":"gdm-20260813-muse12-deepswe","model_slug":"muse-spark-1-2","category":"coding","benchmark_name":"DeepSWE v1.1","benchmark_version":null,"score_numeric":54.9,"score_display":"54.9%","score_unit":"percent","tools":null,"reasoning_effort":null,"harness":"Gemini 3.7 Flash model-card comparison","evaluator":"Google DeepMind","evaluation_date":"2026-08-13","source":"https://deepmind.google/models/model-cards/gemini-3-7-flash/","notes":"Cross-vendor score reported by Google DeepMind; preserve evaluator and harness."},
 {"id":"gdm-20260813-muse12-terminal21","model_slug":"muse-spark-1-2","category":"coding","benchmark_name":"Terminal-Bench 2.1","benchmark_version":null,"score_numeric":82.9,"score_display":"82.9%","score_unit":"percent","tools":null,"reasoning_effort":null,"harness":"Gemini 3.7 Flash model-card comparison","evaluator":"Google DeepMind","evaluation_date":"2026-08-13","source":"https://deepmind.google/models/model-cards/gemini-3-7-flash/","notes":"Cross-vendor score reported by Google DeepMind; preserve evaluator and harness."},
 {"id":"gdm-20260813-muse12-gdpv2","model_slug":"muse-spark-1-2","category":"agentic_computer_use","benchmark_name":"GDPval-AA v2","benchmark_version":null,"score_numeric":1628,"score_display":"1628 Elo","score_unit":"Elo","tools":true,"reasoning_effort":null,"harness":"Artificial Analysis / Gemini 3.7 model-card comparison","evaluator":"Google DeepMind","evaluation_date":"2026-08-13","source":"https://deepmind.google/models/model-cards/gemini-3-7-flash/","notes":"Cross-vendor table value; GDPval-AA v2 must not be compared as if it were the older GDPval-AA variant."}
]
$benchmarks$::jsonb) AS b(id text,model_slug text,category text,benchmark_name text,benchmark_version text,score_numeric double precision,score_display text,score_unit text,tools boolean,reasoning_effort text,harness text,evaluator text,evaluation_date text,source text,notes text)
ON CONFLICT (id) DO UPDATE SET model_slug=EXCLUDED.model_slug,category=EXCLUDED.category,benchmark_name=EXCLUDED.benchmark_name,benchmark_version=EXCLUDED.benchmark_version,score_numeric=EXCLUDED.score_numeric,score_display=EXCLUDED.score_display,score_unit=EXCLUDED.score_unit,tools=EXCLUDED.tools,reasoning_effort=EXCLUDED.reasoning_effort,harness=EXCLUDED.harness,evaluator=EXCLUDED.evaluator,evaluation_date=EXCLUDED.evaluation_date,source=EXCLUDED.source,notes=EXCLUDED.notes,updated_at=NOW();