-- Detailed enrichment for the remaining Qwen3.5/3.6/3.7 catalog. Sources verified 2026-09-07.
WITH s(slug,name,release_date,parameters_total,parameters_active,architecture,api_id,context_window,source_url,notes) AS (VALUES
('qwen3-5-397b-a17b','Qwen3.5-397B-A17B','2026-02-15','397B','17B','multimodal sparse MoE; Gated DeltaNet + gated attention','Qwen/Qwen3.5-397B-A17B','262K native; extensible to ~1.01M','https://qwen.ai/blog?id=qwen3.5','397B-total / 17B-active native multimodal MoE; hybrid Gated DeltaNet + gated attention.'),
('qwen3-5-122b-a10b','Qwen3.5-122B-A10B','2026-02-24','122B','10B','multimodal hybrid Gated DeltaNet + attention','Qwen/Qwen3.5-122B-A10B','262K native; extensible to ~1.01M','https://huggingface.co/Qwen/Qwen3.5-122B-A10B','122B total / 10B active native multimodal model.'),
('qwen3-5-35b-a3b','Qwen3.5-35B-A3B','2026-02-24','35B','3B','multimodal hybrid Gated DeltaNet + attention','Qwen/Qwen3.5-35B-A3B','262K native; extensible to ~1.01M','https://huggingface.co/Qwen/Qwen3.5-35B-A3B','35B total / 3B active native multimodal model.'),
('qwen3-5-27b','Qwen3.5-27B','2026-02-24','27B','','multimodal hybrid Gated DeltaNet + attention','Qwen/Qwen3.5-27B','262K native; extensible to ~1.01M','https://huggingface.co/Qwen/Qwen3.5-27B','27B dense native multimodal model.'),
('qwen3-5-9b','Qwen3.5-9B','2026-03-02','9B','','dense multimodal hybrid Gated DeltaNet + attention','Qwen/Qwen3.5-9B','262K native; extensible to ~1.01M','https://huggingface.co/Qwen/Qwen3.5-9B','9B dense native multimodal model.'),
('qwen3-5-4b','Qwen3.5-4B','2026-03-02','4B','','dense multimodal hybrid Gated DeltaNet + attention','Qwen/Qwen3.5-4B','262K native; extensible to ~1.01M','https://huggingface.co/Qwen/Qwen3.5-4B','4B dense native multimodal model.'),
('qwen3-5-2b','Qwen3.5-2B','2026-03-02','2B','','dense multimodal hybrid Gated DeltaNet + attention','Qwen/Qwen3.5-2B','262K native; extensible to ~1.01M','https://huggingface.co/Qwen/Qwen3.5-2B','2B dense native multimodal model.'),
('qwen3-5-0-8b','Qwen3.5-0.8B','2026-03-02','0.8B','','dense multimodal hybrid Gated DeltaNet + attention','Qwen/Qwen3.5-0.8B','262K native; extensible to ~1.01M','https://huggingface.co/Qwen/Qwen3.5-0.8B','0.8B dense native multimodal model.')
)
INSERT INTO models(slug,name,developer,release_date,ga_date,access,family,comparison_data,sources,notes,metadata,verified_at)
SELECT slug,name,'Alibaba / Qwen',release_date::date,NULL,'open_source',split_part(name,'-',1),
 jsonb_build_object('Developer','Alibaba / Qwen','Release date',release_date,'API model ID',api_id,'Context window',context_window,'Reasoning / effort','Thinking and non-thinking modes','Text input','Yes','Image / vision input','Yes','Audio input','No native audio input','Video input','Yes','Text output','Yes','Image output','No','Audio output','No','Video output','No','Tool / function calling','Yes','Computer use','Via external agent/tool harnesses; no native computer-use API','API access','Downloadable weights; self-hosted OpenAI-compatible servers','Product access','Qwen Chat + downloadable weights','Weights / license','Open source — Apache 2.0'),
 jsonb_build_array(jsonb_build_object('title',name||' official weights','url',source_url),jsonb_build_object('title','Qwen3.5 launch','url','https://qwen.ai/blog?id=qwen3.5')),
 notes,jsonb_strip_nulls(jsonb_build_object('verification_pass','qwen-remaining-2026-09-07','parameters_total',parameters_total,'parameters_active',NULLIF(parameters_active,''),'architecture',architecture,'license','Apache 2.0')),NOW()
FROM s
ON CONFLICT(slug) DO UPDATE SET name=EXCLUDED.name,developer=EXCLUDED.developer,release_date=EXCLUDED.release_date,ga_date=EXCLUDED.ga_date,access=EXCLUDED.access,family=EXCLUDED.family,comparison_data=COALESCE(models.comparison_data,'{}'::jsonb)||EXCLUDED.comparison_data,sources=EXCLUDED.sources,notes=EXCLUDED.notes,metadata=COALESCE(models.metadata,'{}'::jsonb)||EXCLUDED.metadata,verified_at=NOW(),updated_at=NOW();

WITH s(slug,name,release_date,ga_date,family,api_id,context_window,max_output,input_price,cached_price,cache_write,output_price,image_input,video_input,batch_discount,source_url,notes,metadata) AS (VALUES
('qwen3-5-plus','Qwen3.5-Plus','2026-02-15','2026-02-15','Qwen3.5','qwen3.5-plus','1M','64K','$0.40 ≤256K / $0.50 >256K','','','$2.40 ≤256K / $3.00 >256K','Yes','Yes','','https://qwen.ai/blog?id=qwen3.5','Hosted Qwen3.5 flagship corresponding to the 397B-A17B family; includes official built-in tools and adaptive tool use.','{"hosted_snapshot":"qwen3.5-plus-2026-02-15","pricing_region":"Alibaba Model Studio International"}'),
('qwen3-5-flash','Qwen3.5-Flash','2026-02-23','2026-02-23','Qwen3.5','qwen3.5-flash','1M','64K','$0.10','','','$0.40','Yes','Yes','50% batch inference discount','https://www.alibabacloud.com/help/en/model-studio/qwen3-5-flash','Hosted low-cost Qwen3.5 model with function calling, structured output, web search and context caching.','{"hosted_snapshot":"qwen3.5-flash-2026-02-23","pricing_region":"Alibaba Model Studio International"}'),
('qwen3-6-plus','Qwen3.6-Plus','2026-04-02','2026-04-02','Qwen3.6','qwen3.6-plus','1M','64K','$0.50 ≤256K / $2.00 >256K','','','$3.00 ≤256K / $6.00 >256K','Yes','Yes','','https://www.alibabacloud.com/help/en/model-studio/qwen3-6-plus','Hosted multimodal Qwen3.6 flagship with built-in tools, structured output and web search.','{"hosted_snapshot":"qwen3.6-plus-2026-04-02","pricing_region":"Alibaba Model Studio International"}'),
('qwen3-6-flash','Qwen3.6-Flash','2026-04-16','2026-04-17','Qwen3.6','qwen3.6-flash','1M','64K','$0.25 ≤256K / $1.00 >256K','','','$1.50 ≤256K / $4.00 >256K','Yes','Yes','50% batch inference discount','https://www.alibabacloud.com/help/en/model-studio/qwen3-6-flash','Hosted multimodal Qwen3.6 Flash model.','{"hosted_snapshot":"qwen3.6-flash-2026-04-16","pricing_region":"Alibaba Model Studio International"}'),
('qwen3-6-max-preview','Qwen3.6-Max-Preview','2026-04-18','2026-04-20','Qwen3.6','qwen3.6-max-preview','256K','64K','$1.30 ≤128K / $2.00 >128K','$0.13 explicit cache read ≤128K / $0.20 >128K','$1.625 ≤128K / $2.50 >128K','$7.80 ≤128K / $12.00 >128K','No','No','','https://qwen.ai/blog?id=qwen3.6-max-preview','Text-only proprietary preview focused on agentic coding and long-tail knowledge.','{"launch_stage":"preview","pricing_region":"Alibaba Model Studio International"}'),
('qwen3-7-max','Qwen3.7-Max','2026-05-20','2026-06-10','Qwen3.7','qwen3.7-max','1M','128K','$2.50','','','$7.50','Yes','Yes','','https://www.alibabacloud.com/help/en/model-studio/qwen3-7-max','Current Qwen3.7-Max points to the multimodal family; later snapshot qwen3.7-max-2026-06-08 adds image/video API support.','{"initial_preview":"2026-05-20","current_multimodal_snapshot":"qwen3.7-max-2026-06-08","pricing_region":"Alibaba Model Studio International"}'),
('qwen3-7-plus','Qwen3.7-Plus','2026-05-26','2026-06-01','Qwen3.7','qwen3.7-plus','1M','128K','$0.40 ≤256K / $1.20 >256K','','','$1.60 ≤256K / $4.80 >256K','Yes','Yes','','https://www.alibabacloud.com/help/en/model-studio/qwen3-7-plus','Hosted multimodal Qwen3.7 Plus model; later Qwen3.8 launch provides cross-generation evaluation results.','{"hosted_snapshot":"qwen3.7-plus-2026-05-26","pricing_region":"Alibaba Model Studio International"}')
)
INSERT INTO models(slug,name,developer,release_date,ga_date,access,family,comparison_data,sources,notes,metadata,verified_at)
SELECT slug,name,'Alibaba / Qwen',release_date::date,NULLIF(ga_date,'')::date,'proprietary',family,
 jsonb_strip_nulls(jsonb_build_object('Developer','Alibaba / Qwen','Release date',release_date,'API model ID',api_id,'Context window',context_window,'Max output',max_output,'Reasoning / effort','Thinking and non-thinking modes','Input / 1M tokens',input_price,'Cached input / 1M',NULLIF(cached_price,''),'Cache write / 1M',NULLIF(cache_write,''),'Output / 1M tokens',output_price,'Batch / flex discount',NULLIF(batch_discount,''),'Text input','Yes','Image / vision input',image_input,'Audio input','No','Video input',video_input,'Text output','Yes','Image output','No','Audio output','No','Video output','No','Tool / function calling','Yes','Computer use','Via built-in/external tools; no native computer-use API','API access','Alibaba Cloud Model Studio','Product access','Qwen Studio + Alibaba Cloud Model Studio','Weights / license','Proprietary hosted model')),
 jsonb_build_array(jsonb_build_object('title',name||' official docs','url',source_url),jsonb_build_object('title','Alibaba Model Studio pricing','url','https://www.alibabacloud.com/help/en/model-studio/model-pricing')),
 notes,COALESCE(metadata::jsonb,'{}'::jsonb)||jsonb_build_object('verification_pass','qwen-remaining-2026-09-07'),NOW()
FROM s
ON CONFLICT(slug) DO UPDATE SET name=EXCLUDED.name,developer=EXCLUDED.developer,release_date=EXCLUDED.release_date,ga_date=EXCLUDED.ga_date,access=EXCLUDED.access,family=EXCLUDED.family,comparison_data=COALESCE(models.comparison_data,'{}'::jsonb)||EXCLUDED.comparison_data,sources=EXCLUDED.sources,notes=EXCLUDED.notes,metadata=COALESCE(models.metadata,'{}'::jsonb)||EXCLUDED.metadata,verified_at=NOW(),updated_at=NOW();

WITH b(model_slug,category,benchmark_name,benchmark_version,score_numeric,tools,reasoning_effort,harness,evaluator,evaluation_date,source,notes) AS (VALUES
('qwen3-5-397b-a17b','coding','SWE-bench Verified','',76.2,'','','Qwen agent scaffold','Alibaba / Qwen','2026-02-15','https://qwen.ai/blog?id=qwen3.6-27b',''),
('qwen3-5-397b-a17b','coding','SWE-bench Pro','Public',50.9,'','','Qwen agent scaffold','Alibaba / Qwen','2026-02-15','https://qwen.ai/blog?id=qwen3.6-27b',''),
('qwen3-5-397b-a17b','coding','Terminal-Bench 2.0','',52.5,'','','Harbor / Terminus-2','Alibaba / Qwen','2026-02-15','https://qwen.ai/blog?id=qwen3.6-27b',''),
('qwen3-5-397b-a17b','coding','LiveCodeBench','v6',83.6,'false','','','Alibaba / Qwen','2026-02-15','https://qwen.ai/blog?id=qwen3.5',''),
('qwen3-5-397b-a17b','math_reasoning','AIME','2026',91.3,'false','','','Alibaba / Qwen','2026-02-15','https://qwen.ai/blog?id=qwen3.5',''),
('qwen3-5-397b-a17b','math_reasoning','HMMT','Feb. 2025',94.8,'false','','','Alibaba / Qwen','2026-02-15','https://qwen.ai/blog?id=qwen3.5',''),
('qwen3-5-397b-a17b','knowledge','MMLU-Pro','',87.8,'false','','','Alibaba / Qwen','2026-02-15','https://qwen.ai/blog?id=qwen3.5',''),
('qwen3-5-397b-a17b','knowledge','Humanity''s Last Exam','',28.7,'false','','','Alibaba / Qwen','2026-02-15','https://qwen.ai/blog?id=qwen3.5',''),
('qwen3-5-397b-a17b','knowledge','HLE-Verified','',37.6,'false','','','Alibaba / Qwen','2026-02-15','https://qwen.ai/blog?id=qwen3.5',''),
('qwen3-5-397b-a17b','agentic_computer_use','BrowseComp','context-folding',69.0,'true','','','Alibaba / Qwen','2026-02-15','https://qwen.ai/blog?id=qwen3.5',''),
('qwen3-5-122b-a10b','knowledge','MMLU-Pro','',86.7,'false','','','Alibaba / Qwen','2026-02-24','https://huggingface.co/Qwen/Qwen3.5-122B-A10B',''),
('qwen3-5-122b-a10b','knowledge','GPQA Diamond','',86.6,'false','','','Alibaba / Qwen','2026-02-24','https://huggingface.co/Qwen/Qwen3.5-122B-A10B',''),
('qwen3-5-122b-a10b','knowledge','Humanity''s Last Exam','',25.3,'false','','','Alibaba / Qwen','2026-02-24','https://huggingface.co/Qwen/Qwen3.5-122B-A10B',''),
('qwen3-5-122b-a10b','math_reasoning','HMMT','Feb. 2025',91.4,'false','','','Alibaba / Qwen','2026-02-24','https://huggingface.co/Qwen/Qwen3.5-122B-A10B',''),
('qwen3-5-122b-a10b','coding','SWE-bench Verified','',72.0,'','','Qwen evaluation harness','Alibaba / Qwen','2026-02-24','https://huggingface.co/Qwen/Qwen3.5-122B-A10B',''),
('qwen3-5-122b-a10b','coding','Terminal-Bench 2.0','',49.4,'','','Qwen evaluation harness','Alibaba / Qwen','2026-02-24','https://huggingface.co/Qwen/Qwen3.5-122B-A10B',''),
('qwen3-5-122b-a10b','coding','LiveCodeBench','v6',78.9,'false','','','Alibaba / Qwen','2026-02-24','https://huggingface.co/Qwen/Qwen3.5-122B-A10B',''),
('qwen3-5-122b-a10b','knowledge','Humanity''s Last Exam','',47.5,'true','','','Alibaba / Qwen','2026-02-24','https://huggingface.co/Qwen/Qwen3.5-122B-A10B',''),
('qwen3-5-122b-a10b','agentic_computer_use','BrowseComp','context-folding',63.8,'true','','','Alibaba / Qwen','2026-02-24','https://huggingface.co/Qwen/Qwen3.5-122B-A10B',''),
('qwen3-5-27b','knowledge','MMLU-Pro','',86.1,'false','','','Alibaba / Qwen','2026-02-24','https://huggingface.co/Qwen/Qwen3.5-122B-A10B',''),
('qwen3-5-27b','knowledge','GPQA Diamond','',85.5,'false','','','Alibaba / Qwen','2026-02-24','https://huggingface.co/Qwen/Qwen3.5-122B-A10B',''),
('qwen3-5-27b','knowledge','Humanity''s Last Exam','',24.3,'false','','','Alibaba / Qwen','2026-02-24','https://huggingface.co/Qwen/Qwen3.5-122B-A10B',''),
('qwen3-5-27b','math_reasoning','HMMT','Feb. 2025',92.0,'false','','','Alibaba / Qwen','2026-02-24','https://huggingface.co/Qwen/Qwen3.5-122B-A10B',''),
('qwen3-5-27b','coding','SWE-bench Verified','',72.4,'','','Qwen evaluation harness','Alibaba / Qwen','2026-02-24','https://huggingface.co/Qwen/Qwen3.5-122B-A10B',''),
('qwen3-5-27b','coding','Terminal-Bench 2.0','',41.6,'','','Qwen evaluation harness','Alibaba / Qwen','2026-02-24','https://huggingface.co/Qwen/Qwen3.5-122B-A10B',''),
('qwen3-5-27b','coding','LiveCodeBench','v6',80.7,'false','','','Alibaba / Qwen','2026-02-24','https://huggingface.co/Qwen/Qwen3.5-122B-A10B',''),
('qwen3-5-27b','knowledge','Humanity''s Last Exam','',48.5,'true','','','Alibaba / Qwen','2026-02-24','https://huggingface.co/Qwen/Qwen3.5-122B-A10B',''),
('qwen3-5-27b','agentic_computer_use','BrowseComp','context-folding',61.0,'true','','','Alibaba / Qwen','2026-02-24','https://huggingface.co/Qwen/Qwen3.5-122B-A10B',''),
('qwen3-5-35b-a3b','knowledge','MMLU-Pro','',85.3,'false','','','Alibaba / Qwen','2026-02-24','https://huggingface.co/Qwen/Qwen3.5-122B-A10B',''),
('qwen3-5-35b-a3b','knowledge','GPQA Diamond','',84.2,'false','','','Alibaba / Qwen','2026-02-24','https://huggingface.co/Qwen/Qwen3.5-122B-A10B',''),
('qwen3-5-35b-a3b','knowledge','Humanity''s Last Exam','',22.4,'false','','','Alibaba / Qwen','2026-02-24','https://huggingface.co/Qwen/Qwen3.5-122B-A10B',''),
('qwen3-5-35b-a3b','math_reasoning','HMMT','Feb. 2025',89.0,'false','','','Alibaba / Qwen','2026-02-24','https://huggingface.co/Qwen/Qwen3.5-122B-A10B',''),
('qwen3-5-35b-a3b','coding','SWE-bench Verified','',69.2,'','','Qwen evaluation harness','Alibaba / Qwen','2026-02-24','https://huggingface.co/Qwen/Qwen3.5-122B-A10B',''),
('qwen3-5-35b-a3b','coding','Terminal-Bench 2.0','',40.5,'','','Qwen evaluation harness','Alibaba / Qwen','2026-02-24','https://huggingface.co/Qwen/Qwen3.5-122B-A10B',''),
('qwen3-5-35b-a3b','coding','LiveCodeBench','v6',74.6,'false','','','Alibaba / Qwen','2026-02-24','https://huggingface.co/Qwen/Qwen3.5-122B-A10B',''),
('qwen3-5-35b-a3b','knowledge','Humanity''s Last Exam','',47.4,'true','','','Alibaba / Qwen','2026-02-24','https://huggingface.co/Qwen/Qwen3.5-122B-A10B',''),
('qwen3-5-35b-a3b','agentic_computer_use','BrowseComp','context-folding',61.0,'true','','','Alibaba / Qwen','2026-02-24','https://huggingface.co/Qwen/Qwen3.5-122B-A10B',''),
('qwen3-5-9b','knowledge','MMLU-Pro','',82.5,'false','','','Alibaba / Qwen','2026-03-02','https://huggingface.co/Qwen/Qwen3.5-9B',''),
('qwen3-5-9b','knowledge','GPQA Diamond','',81.7,'false','','','Alibaba / Qwen','2026-03-02','https://huggingface.co/Qwen/Qwen3.5-9B',''),
('qwen3-5-9b','math_reasoning','HMMT','Feb. 2025',83.2,'false','','','Alibaba / Qwen','2026-03-02','https://huggingface.co/Qwen/Qwen3.5-9B',''),
('qwen3-5-9b','coding','LiveCodeBench','v6',65.6,'false','','','Alibaba / Qwen','2026-03-02','https://huggingface.co/Qwen/Qwen3.5-9B',''),
('qwen3-5-9b','agentic_computer_use','OSWorld-Verified','',41.8,'true','','','Alibaba / Qwen','2026-03-02','https://huggingface.co/Qwen/Qwen3.5-9B',''),
('qwen3-5-4b','knowledge','MMLU-Pro','',79.1,'false','','','Alibaba / Qwen','2026-03-02','https://huggingface.co/Qwen/Qwen3.5-9B',''),
('qwen3-5-4b','knowledge','GPQA Diamond','',76.2,'false','','','Alibaba / Qwen','2026-03-02','https://huggingface.co/Qwen/Qwen3.5-9B',''),
('qwen3-5-4b','math_reasoning','HMMT','Feb. 2025',74.0,'false','','','Alibaba / Qwen','2026-03-02','https://huggingface.co/Qwen/Qwen3.5-9B',''),
('qwen3-5-4b','coding','LiveCodeBench','v6',55.8,'false','','','Alibaba / Qwen','2026-03-02','https://huggingface.co/Qwen/Qwen3.5-9B',''),
('qwen3-5-4b','agentic_computer_use','OSWorld-Verified','',35.6,'true','','','Alibaba / Qwen','2026-03-02','https://huggingface.co/Qwen/Qwen3.5-9B',''),
('qwen3-5-2b','knowledge','MMLU-Pro','',55.3,'false','non-thinking','','Alibaba / Qwen','2026-03-02','https://huggingface.co/Qwen/Qwen3.5-2B',''),
('qwen3-5-2b','knowledge','MMLU-Pro','',66.5,'false','thinking','','Alibaba / Qwen','2026-03-02','https://huggingface.co/Qwen/Qwen3.5-2B',''),
('qwen3-5-0-8b','knowledge','MMLU-Pro','',29.7,'false','non-thinking','','Alibaba / Qwen','2026-03-02','https://huggingface.co/Qwen/Qwen3.5-2B',''),
('qwen3-5-0-8b','knowledge','MMLU-Pro','',42.3,'false','thinking','','Alibaba / Qwen','2026-03-02','https://huggingface.co/Qwen/Qwen3.5-2B',''),
('qwen3-5-2b','math_reasoning','HMMT','Feb. 2025',22.9,'false','thinking','','Alibaba / Qwen','2026-03-02','https://huggingface.co/Qwen/Qwen3.5-2B',''),
('qwen3-5-2b','math_reasoning','HMMT','Nov. 2025',19.6,'false','thinking','','Alibaba / Qwen','2026-03-02','https://huggingface.co/Qwen/Qwen3.5-2B',''),
('qwen3-7-plus','coding','DeepSWE v1.1','',16.5,'','','Claude Code / mini-SWE-agent','Alibaba / Qwen','2026-08-26','https://qwen.ai/blog?id=qwen3.8-flash-next','Cross-generation rerun published by Qwen in the Qwen3.8-Flash-Next launch evaluation.'),
('qwen3-7-plus','coding','SWE-bench Pro','Public',55.8,'','','Claude Code','Alibaba / Qwen','2026-08-26','https://qwen.ai/blog?id=qwen3.8-flash-next','Cross-generation rerun published by Qwen in the Qwen3.8-Flash-Next launch evaluation.'),
('qwen3-7-plus','coding','LiveCodeBench','v6',89.6,'false','','','Alibaba / Qwen','2026-08-26','https://qwen.ai/blog?id=qwen3.8-flash-next','Cross-generation rerun published by Qwen in the Qwen3.8-Flash-Next launch evaluation.'),
('qwen3-7-plus','knowledge','GPQA Diamond','',90.3,'false','','','Alibaba / Qwen','2026-08-26','https://qwen.ai/blog?id=qwen3.8-flash-next','Cross-generation rerun published by Qwen in the Qwen3.8-Flash-Next launch evaluation.'),
('qwen3-7-plus','knowledge','Humanity''s Last Exam','',34.7,'false','','','Alibaba / Qwen','2026-08-26','https://qwen.ai/blog?id=qwen3.8-flash-next','Cross-generation rerun published by Qwen in the Qwen3.8-Flash-Next launch evaluation.'),
('qwen3-7-plus','agentic_computer_use','Agents'' Last Exam','Pass@1',13.2,'true','','','Alibaba / Qwen','2026-08-26','https://qwen.ai/blog?id=qwen3.8-flash-next','Cross-generation rerun published by Qwen in the Qwen3.8-Flash-Next launch evaluation.'),
('qwen3-7-plus','agentic_computer_use','Toolathlon','Verified',50.6,'true','','','Alibaba / Qwen','2026-08-26','https://qwen.ai/blog?id=qwen3.8-flash-next','Cross-generation rerun published by Qwen in the Qwen3.8-Flash-Next launch evaluation.'),
('qwen3-7-plus','agentic_computer_use','OSWorld 2.0','Binary',2.8,'true','','','Alibaba / Qwen','2026-08-26','https://qwen.ai/blog?id=qwen3.8-flash-next','Cross-generation rerun published by Qwen in the Qwen3.8-Flash-Next launch evaluation.'),
('qwen3-7-plus','agentic_computer_use','OSWorld 2.0','Partial',21.5,'true','','','Alibaba / Qwen','2026-08-26','https://qwen.ai/blog?id=qwen3.8-flash-next','Cross-generation rerun published by Qwen in the Qwen3.8-Flash-Next launch evaluation.')
)
INSERT INTO model_benchmarks(id,model_slug,category,benchmark_name,benchmark_version,score_numeric,score_display,score_unit,tools,reasoning_effort,harness,evaluator,evaluation_date,source,notes,updated_at)
SELECT 'tq-20260907-032-'||substr(md5(concat_ws('|',model_slug,benchmark_name,benchmark_version,score_numeric::text,reasoning_effort,harness)),1,20),model_slug,category,benchmark_name,NULLIF(benchmark_version,''),score_numeric,trim(to_char(score_numeric,'FM999990.0'))||'%','percent',CASE WHEN tools='' THEN NULL ELSE tools::boolean END,NULLIF(reasoning_effort,''),NULLIF(harness,''),evaluator,evaluation_date::date,source,NULLIF(notes,''),NOW()
FROM b
ON CONFLICT(id) DO UPDATE SET model_slug=EXCLUDED.model_slug,category=EXCLUDED.category,benchmark_name=EXCLUDED.benchmark_name,benchmark_version=EXCLUDED.benchmark_version,score_numeric=EXCLUDED.score_numeric,score_display=EXCLUDED.score_display,score_unit=EXCLUDED.score_unit,tools=EXCLUDED.tools,reasoning_effort=EXCLUDED.reasoning_effort,harness=EXCLUDED.harness,evaluator=EXCLUDED.evaluator,evaluation_date=EXCLUDED.evaluation_date,source=EXCLUDED.source,notes=EXCLUDED.notes,updated_at=NOW();

WITH r AS (
 SELECT b.model_slug,b.benchmark_name,b.evaluation_date,b.id,b.score_display||CASE WHEN concat_ws('; ',CASE WHEN b.benchmark_version IS NOT NULL AND lower(trim(b.benchmark_version))<>'public' AND position(lower(b.benchmark_version) in lower(b.benchmark_name))=0 THEN b.benchmark_version END,CASE WHEN b.tools IS TRUE THEN 'tools' WHEN b.tools IS FALSE THEN 'no tools' END,b.reasoning_effort)<>'' THEN ' ('||concat_ws('; ',CASE WHEN b.benchmark_version IS NOT NULL AND lower(trim(b.benchmark_version))<>'public' AND position(lower(b.benchmark_version) in lower(b.benchmark_name))=0 THEN b.benchmark_version END,CASE WHEN b.tools IS TRUE THEN 'tools' WHEN b.tools IS FALSE THEN 'no tools' END,b.reasoning_effort)||')' ELSE '' END rendered
 FROM model_benchmarks b WHERE b.model_slug IN ('qwen3-5-397b-a17b','qwen3-5-122b-a10b','qwen3-5-35b-a3b','qwen3-5-27b','qwen3-5-plus','qwen3-5-flash','qwen3-5-9b','qwen3-5-4b','qwen3-5-2b','qwen3-5-0-8b','qwen3-6-plus','qwen3-6-flash','qwen3-6-max-preview','qwen3-7-max','qwen3-7-plus')
),g AS (SELECT model_slug,benchmark_name,string_agg(rendered,' · ' ORDER BY evaluation_date NULLS LAST,id) rendered FROM r GROUP BY model_slug,benchmark_name),x AS (
 SELECT c.id,jsonb_agg(CASE WHEN jsonb_typeof(be.block->'rows')='array' THEN jsonb_set(be.block,'{rows}',COALESCE((SELECT jsonb_agg(CASE WHEN jsonb_typeof(re.row_value)='array' AND jsonb_array_length(re.row_value)>=3 THEN jsonb_set(jsonb_set(re.row_value,'{1}',to_jsonb(CASE WHEN COALESCE(re.row_value->>1,'')='' AND a.rendered IS NOT NULL THEN a.rendered ELSE COALESCE(re.row_value->>1,'') END),false),'{2}',to_jsonb(CASE WHEN COALESCE(re.row_value->>2,'')='' AND d.rendered IS NOT NULL THEN d.rendered ELSE COALESCE(re.row_value->>2,'') END),false) ELSE re.row_value END ORDER BY re.ord) FROM jsonb_array_elements(be.block->'rows') WITH ORDINALITY re(row_value,ord) LEFT JOIN g a ON a.model_slug=c.metadata->>'modelA' AND lower(a.benchmark_name)=lower(COALESCE(re.row_value->>0,'')) LEFT JOIN g d ON d.model_slug=c.metadata->>'modelB' AND lower(d.benchmark_name)=lower(COALESCE(re.row_value->>0,''))),'[]'::jsonb),true) ELSE be.block END ORDER BY be.ord) blocks
 FROM content_items c CROSS JOIN LATERAL jsonb_array_elements(COALESCE(c.blocks,'[]'::jsonb)) WITH ORDINALITY be(block,ord)
 WHERE c.kind='comparison' AND (c.metadata->>'modelA' IN ('qwen3-5-397b-a17b','qwen3-5-122b-a10b','qwen3-5-35b-a3b','qwen3-5-27b','qwen3-5-plus','qwen3-5-flash','qwen3-5-9b','qwen3-5-4b','qwen3-5-2b','qwen3-5-0-8b','qwen3-6-plus','qwen3-6-flash','qwen3-6-max-preview','qwen3-7-max','qwen3-7-plus') OR c.metadata->>'modelB' IN ('qwen3-5-397b-a17b','qwen3-5-122b-a10b','qwen3-5-35b-a3b','qwen3-5-27b','qwen3-5-plus','qwen3-5-flash','qwen3-5-9b','qwen3-5-4b','qwen3-5-2b','qwen3-5-0-8b','qwen3-6-plus','qwen3-6-flash','qwen3-6-max-preview','qwen3-7-max','qwen3-7-plus')) GROUP BY c.id,c.metadata)
UPDATE content_items c SET blocks=x.blocks,updated_at=NOW() FROM x WHERE c.id=x.id AND c.blocks IS DISTINCT FROM x.blocks;
