-- Detailed enrichment for the complete Gemma 4 family. Sources verified 2026-09-07.
WITH s(slug,name,release_date,api_id,context_window,audio_input,api_access,product_access,notes,metadata) AS (VALUES
('gemma-4-e2b','Gemma 4 E2B','2026-03-31','google/gemma-4-E2B-it','128K','Yes','Downloadable weights; self-hosted runtimes','Kaggle + Hugging Face + self-hosted runtimes','2.3B effective / 5.1B including per-layer embeddings; designed for mobile deployment.','{"license":"Apache 2.0","parameters_effective":"2.3B","parameters_with_embeddings":"5.1B","layers":35,"architecture":"dense + PLE","vision_encoder":"~150M","audio_encoder":"~300M"}'),
('gemma-4-e4b','Gemma 4 E4B','2026-03-31','google/gemma-4-E4B-it','128K','Yes','Downloadable weights; self-hosted runtimes','Kaggle + Hugging Face + self-hosted runtimes','4.5B effective / 8B including per-layer embeddings; designed for mobile and laptop deployment.','{"license":"Apache 2.0","parameters_effective":"4.5B","parameters_with_embeddings":"8B","layers":42,"architecture":"dense + PLE","vision_encoder":"~150M","audio_encoder":"~300M"}'),
('gemma-4-12b','Gemma 4 12B','2026-06-03','google/gemma-4-12B-it','256K','Yes','Downloadable weights; self-hosted runtimes','Kaggle + Hugging Face + self-hosted runtimes','11.95B encoder-free unified multimodal model; audio and image streams project directly into the decoder.','{"license":"Apache 2.0","parameters_total":"11.95B","layers":48,"architecture":"dense unified encoder-free"}'),
('gemma-4-26b-a4b','Gemma 4 26B-A4B','2026-03-31','gemma-4-26b-a4b-it (Gemini API); google/gemma-4-26B-A4B-it (weights)','256K','No','Gemini API + downloadable weights','Google AI Studio / Gemini API + Kaggle/Hugging Face','25.2B-total / 3.8B-active MoE with 128 routed experts plus one shared expert; eight routed experts active.','{"license":"Apache 2.0","parameters_total":"25.2B","parameters_active":"3.8B","layers":30,"architecture":"MoE","experts_total":128,"experts_active":8,"vision_encoder":"~550M"}'),
('gemma-4-31b','Gemma 4 31B','2026-03-31','gemma-4-31b-it (Gemini API); google/gemma-4-31B-it (weights)','256K','No','Gemini API + downloadable weights','Google AI Studio / Gemini API + Kaggle/Hugging Face','30.7B dense multimodal model with a ~550M vision encoder.','{"license":"Apache 2.0","parameters_total":"30.7B","layers":60,"architecture":"dense","vision_encoder":"~550M"}')
)
INSERT INTO models(slug,name,developer,release_date,ga_date,access,family,comparison_data,sources,notes,metadata,verified_at)
SELECT slug,name,'Google DeepMind',release_date::date,release_date::date,'open_source','Gemma 4',
 jsonb_build_object('Developer','Google DeepMind','Release date',release_date,'API model ID',api_id,'Context window',context_window,'Reasoning / effort','Built-in thinking mode','Text input','Yes','Image / vision input','Yes','Audio input',audio_input,'Video input','Yes — processed as frame sequences','Text output','Yes','Image output','No','Audio output','No','Video output','No','Tool / function calling','Yes','Computer use','Via external agent/tool harnesses; no native computer-use API','API access',api_access,'Product access',product_access,'Weights / license','Open source — Apache 2.0'),
 jsonb_build_array(jsonb_build_object('title','Gemma 4 model card','url','https://ai.google.dev/gemma/docs/core/model_card_4'),jsonb_build_object('title','Gemma release history','url','https://ai.google.dev/gemma/docs/releases'),jsonb_build_object('title','Gemma 4 model collection','url','https://huggingface.co/collections/google/gemma-4')),
 notes,COALESCE(metadata::jsonb,'{}'::jsonb)||jsonb_build_object('verification_pass','gemma4-family-2026-09-07'),NOW()
FROM s
ON CONFLICT(slug) DO UPDATE SET name=EXCLUDED.name,developer=EXCLUDED.developer,release_date=EXCLUDED.release_date,ga_date=EXCLUDED.ga_date,access=EXCLUDED.access,family=EXCLUDED.family,comparison_data=COALESCE(models.comparison_data,'{}'::jsonb)||EXCLUDED.comparison_data,sources=EXCLUDED.sources,notes=EXCLUDED.notes,metadata=COALESCE(models.metadata,'{}'::jsonb)||EXCLUDED.metadata,verified_at=NOW(),updated_at=NOW();

WITH b(model_slug,category,benchmark_name,benchmark_version,score_numeric,tools,reasoning_effort,harness,evaluator,evaluation_date,source,notes) AS (VALUES
('gemma-4-31b','knowledge','MMLU-Pro','',85.2,'false','thinking','','Google DeepMind','2026-03-31','https://ai.google.dev/gemma/docs/core/model_card_4',''),
('gemma-4-31b','math_reasoning','AIME','2026',89.2,'false','thinking','','Google DeepMind','2026-03-31','https://ai.google.dev/gemma/docs/core/model_card_4',''),
('gemma-4-31b','coding','LiveCodeBench','v6',80.0,'false','thinking','','Google DeepMind','2026-03-31','https://ai.google.dev/gemma/docs/core/model_card_4',''),
('gemma-4-31b','knowledge','GPQA Diamond','',84.3,'false','thinking','','Google DeepMind','2026-03-31','https://ai.google.dev/gemma/docs/core/model_card_4',''),
('gemma-4-31b','knowledge','Humanity''s Last Exam','',19.5,'false','thinking','','Google DeepMind','2026-03-31','https://ai.google.dev/gemma/docs/core/model_card_4',''),
('gemma-4-31b','knowledge','Humanity''s Last Exam','search',26.5,'true','thinking','','Google DeepMind','2026-03-31','https://ai.google.dev/gemma/docs/core/model_card_4','Google model card reports HLE with search.'),
('gemma-4-26b-a4b','knowledge','MMLU-Pro','',82.6,'false','thinking','','Google DeepMind','2026-03-31','https://ai.google.dev/gemma/docs/core/model_card_4',''),
('gemma-4-26b-a4b','math_reasoning','AIME','2026',88.3,'false','thinking','','Google DeepMind','2026-03-31','https://ai.google.dev/gemma/docs/core/model_card_4',''),
('gemma-4-26b-a4b','coding','LiveCodeBench','v6',77.1,'false','thinking','','Google DeepMind','2026-03-31','https://ai.google.dev/gemma/docs/core/model_card_4',''),
('gemma-4-26b-a4b','knowledge','GPQA Diamond','',82.3,'false','thinking','','Google DeepMind','2026-03-31','https://ai.google.dev/gemma/docs/core/model_card_4',''),
('gemma-4-26b-a4b','knowledge','Humanity''s Last Exam','',8.7,'false','thinking','','Google DeepMind','2026-03-31','https://ai.google.dev/gemma/docs/core/model_card_4',''),
('gemma-4-26b-a4b','knowledge','Humanity''s Last Exam','search',17.2,'true','thinking','','Google DeepMind','2026-03-31','https://ai.google.dev/gemma/docs/core/model_card_4','Google model card reports HLE with search.'),
('gemma-4-12b','knowledge','MMLU-Pro','',77.2,'false','thinking','','Google DeepMind','2026-06-03','https://ai.google.dev/gemma/docs/core/model_card_4',''),
('gemma-4-12b','math_reasoning','AIME','2026',77.5,'false','thinking','','Google DeepMind','2026-06-03','https://ai.google.dev/gemma/docs/core/model_card_4',''),
('gemma-4-12b','coding','LiveCodeBench','v6',72.0,'false','thinking','','Google DeepMind','2026-06-03','https://ai.google.dev/gemma/docs/core/model_card_4',''),
('gemma-4-12b','knowledge','GPQA Diamond','',78.8,'false','thinking','','Google DeepMind','2026-06-03','https://ai.google.dev/gemma/docs/core/model_card_4',''),
('gemma-4-12b','knowledge','Humanity''s Last Exam','',5.2,'false','thinking','','Google DeepMind','2026-06-03','https://ai.google.dev/gemma/docs/core/model_card_4',''),
('gemma-4-e4b','knowledge','MMLU-Pro','',69.4,'false','thinking','','Google DeepMind','2026-03-31','https://ai.google.dev/gemma/docs/core/model_card_4',''),
('gemma-4-e4b','math_reasoning','AIME','2026',42.5,'false','thinking','','Google DeepMind','2026-03-31','https://ai.google.dev/gemma/docs/core/model_card_4',''),
('gemma-4-e4b','coding','LiveCodeBench','v6',52.0,'false','thinking','','Google DeepMind','2026-03-31','https://ai.google.dev/gemma/docs/core/model_card_4',''),
('gemma-4-e4b','knowledge','GPQA Diamond','',58.6,'false','thinking','','Google DeepMind','2026-03-31','https://ai.google.dev/gemma/docs/core/model_card_4',''),
('gemma-4-e2b','knowledge','MMLU-Pro','',60.0,'false','thinking','','Google DeepMind','2026-03-31','https://ai.google.dev/gemma/docs/core/model_card_4',''),
('gemma-4-e2b','math_reasoning','AIME','2026',37.5,'false','thinking','','Google DeepMind','2026-03-31','https://ai.google.dev/gemma/docs/core/model_card_4',''),
('gemma-4-e2b','coding','LiveCodeBench','v6',44.0,'false','thinking','','Google DeepMind','2026-03-31','https://ai.google.dev/gemma/docs/core/model_card_4',''),
('gemma-4-e2b','knowledge','GPQA Diamond','',43.4,'false','thinking','','Google DeepMind','2026-03-31','https://ai.google.dev/gemma/docs/core/model_card_4',''),
('gemma-4-31b','coding','SWE-bench Verified','',52.0,'','','Qwen agent scaffold','Alibaba / Qwen','2026-04-21','https://qwen.ai/blog?id=qwen3.6-27b','Cross-vendor rerun published by Qwen; not a Google evaluation.'),
('gemma-4-31b','coding','SWE-bench Pro','Public',35.7,'','','Qwen agent scaffold','Alibaba / Qwen','2026-04-21','https://qwen.ai/blog?id=qwen3.6-27b','Cross-vendor rerun published by Qwen; not a Google evaluation.'),
('gemma-4-31b','coding','Terminal-Bench 2.0','',42.9,'','','Harbor / Terminus-2','Alibaba / Qwen','2026-04-21','https://qwen.ai/blog?id=qwen3.6-27b','Cross-vendor rerun published by Qwen; not a Google evaluation.')
)
INSERT INTO model_benchmarks(id,model_slug,category,benchmark_name,benchmark_version,score_numeric,score_display,score_unit,tools,reasoning_effort,harness,evaluator,evaluation_date,source,notes,updated_at)
SELECT 'tq-20260907-033-'||substr(md5(concat_ws('|',model_slug,benchmark_name,benchmark_version,score_numeric::text,reasoning_effort,harness,evaluator)),1,20),model_slug,category,benchmark_name,NULLIF(benchmark_version,''),score_numeric,trim(to_char(score_numeric,'FM999990.0'))||'%','percent',CASE WHEN tools='' THEN NULL ELSE tools::boolean END,NULLIF(reasoning_effort,''),NULLIF(harness,''),evaluator,evaluation_date::date,source,NULLIF(notes,''),NOW()
FROM b
ON CONFLICT(id) DO UPDATE SET model_slug=EXCLUDED.model_slug,category=EXCLUDED.category,benchmark_name=EXCLUDED.benchmark_name,benchmark_version=EXCLUDED.benchmark_version,score_numeric=EXCLUDED.score_numeric,score_display=EXCLUDED.score_display,score_unit=EXCLUDED.score_unit,tools=EXCLUDED.tools,reasoning_effort=EXCLUDED.reasoning_effort,harness=EXCLUDED.harness,evaluator=EXCLUDED.evaluator,evaluation_date=EXCLUDED.evaluation_date,source=EXCLUDED.source,notes=EXCLUDED.notes,updated_at=NOW();

WITH r AS (
 SELECT b.model_slug,b.benchmark_name,b.evaluation_date,b.id,b.score_display||CASE WHEN concat_ws('; ',CASE WHEN b.benchmark_version IS NOT NULL AND lower(trim(b.benchmark_version))<>'public' AND position(lower(b.benchmark_version) in lower(b.benchmark_name))=0 THEN b.benchmark_version END,CASE WHEN b.tools IS TRUE THEN 'tools' WHEN b.tools IS FALSE THEN 'no tools' END,b.reasoning_effort)<>'' THEN ' ('||concat_ws('; ',CASE WHEN b.benchmark_version IS NOT NULL AND lower(trim(b.benchmark_version))<>'public' AND position(lower(b.benchmark_version) in lower(b.benchmark_name))=0 THEN b.benchmark_version END,CASE WHEN b.tools IS TRUE THEN 'tools' WHEN b.tools IS FALSE THEN 'no tools' END,b.reasoning_effort)||')' ELSE '' END rendered
 FROM model_benchmarks b WHERE b.model_slug IN ('gemma-4-e2b','gemma-4-e4b','gemma-4-12b','gemma-4-26b-a4b','gemma-4-31b')
),g AS (SELECT model_slug,benchmark_name,string_agg(rendered,' · ' ORDER BY evaluation_date NULLS LAST,id) rendered FROM r GROUP BY model_slug,benchmark_name),x AS (
 SELECT c.id,jsonb_agg(CASE WHEN jsonb_typeof(be.block->'rows')='array' THEN jsonb_set(be.block,'{rows}',COALESCE((SELECT jsonb_agg(CASE WHEN jsonb_typeof(re.row_value)='array' AND jsonb_array_length(re.row_value)>=3 THEN jsonb_set(jsonb_set(re.row_value,'{1}',to_jsonb(CASE WHEN COALESCE(re.row_value->>1,'')='' AND a.rendered IS NOT NULL THEN a.rendered ELSE COALESCE(re.row_value->>1,'') END),false),'{2}',to_jsonb(CASE WHEN COALESCE(re.row_value->>2,'')='' AND d.rendered IS NOT NULL THEN d.rendered ELSE COALESCE(re.row_value->>2,'') END),false) ELSE re.row_value END ORDER BY re.ord) FROM jsonb_array_elements(be.block->'rows') WITH ORDINALITY re(row_value,ord) LEFT JOIN g a ON a.model_slug=c.metadata->>'modelA' AND lower(a.benchmark_name)=lower(COALESCE(re.row_value->>0,'')) LEFT JOIN g d ON d.model_slug=c.metadata->>'modelB' AND lower(d.benchmark_name)=lower(COALESCE(re.row_value->>0,''))),'[]'::jsonb),true) ELSE be.block END ORDER BY be.ord) blocks
 FROM content_items c CROSS JOIN LATERAL jsonb_array_elements(COALESCE(c.blocks,'[]'::jsonb)) WITH ORDINALITY be(block,ord)
 WHERE c.kind='comparison' AND (c.metadata->>'modelA' IN ('gemma-4-e2b','gemma-4-e4b','gemma-4-12b','gemma-4-26b-a4b','gemma-4-31b') OR c.metadata->>'modelB' IN ('gemma-4-e2b','gemma-4-e4b','gemma-4-12b','gemma-4-26b-a4b','gemma-4-31b')) GROUP BY c.id,c.metadata)
UPDATE content_items c SET blocks=x.blocks,updated_at=NOW() FROM x WHERE c.id=x.id AND c.blocks IS DISTINCT FROM x.blocks;
