-- Detailed enrichment for remaining OpenAI 2026 catalog models. Sources verified 2026-09-07.
WITH s(slug,name,release_date,ga_date,access,family,comparison_data,sources,notes,metadata) AS (VALUES
('gpt-5-3-codex','GPT-5.3-Codex','2026-02-05','2026-02-05','proprietary','GPT-5.3',
 '{"Developer":"OpenAI","Release date":"2026-02-05","API model ID":"gpt-5.3-codex","Context window":"400K","Max output":"128K","Knowledge cutoff":"Aug 31, 2025","Reasoning / effort":"low / medium / high / xhigh","Input / 1M tokens":"$1.75","Cached input / 1M":"$0.175","Output / 1M tokens":"$14","Text input":"Yes","Image / vision input":"Yes","Audio input":"No","Video input":"No","Text output":"Yes","Image output":"No native output","Audio output":"No","Video output":"No","Tool / function calling":"Yes","Computer use":"Yes — optimized for Codex and agentic coding environments","API access":"Yes — Chat Completions, Responses and Batch","Product access":"Codex + OpenAI API","Weights / license":"Proprietary"}'::jsonb,
 '[{"title":"GPT-5.3-Codex API model page","url":"https://developers.openai.com/api/docs/models/gpt-5.3-codex"},{"title":"Introducing GPT-5.3-Codex","url":"https://openai.com/index/introducing-gpt-5-3-codex/"},{"title":"Introducing GPT-5.4","url":"https://openai.com/index/introducing-gpt-5-4/"}]'::jsonb,
 'Agentic coding model. The OSWorld-Verified value stored by this migration uses OpenAI''s revised 74.0% result, which supersedes the original 64.7% after an image-resolution-preserving API parameter was introduced.',
 '{"verification_pass":"openai-remaining-2026-09-07","catalog_status":"active"}'::jsonb),
('gpt-5-3-codex-spark','GPT-5.3-Codex-Spark','2026-02-12',NULL,'restricted','GPT-5.3',
 '{"Developer":"OpenAI","Release date":"2026-02-12","API model ID":"gpt-5.3-codex-spark (research preview)","Context window":"128K","Reasoning / effort":"Optimized for lightweight real-time coding","Text input":"Yes","Image / vision input":"No","Audio input":"No","Video input":"No","Text output":"Yes","Image output":"No","Audio output":"No","Video output":"No","Tool / function calling":"Yes — through Codex environment","Computer use":"Codex app / CLI / VS Code tool environment","API access":"Limited design-partner preview","Product access":"ChatGPT Pro via Codex app, CLI and VS Code extension","Weights / license":"Restricted proprietary research preview"}'::jsonb,
 '[{"title":"Introducing GPT-5.3-Codex-Spark","url":"https://openai.com/index/introducing-gpt-5-3-codex-spark/"}]'::jsonb,
 'Research preview served on Cerebras and designed for >1,000 output tokens/s. OpenAI publishes qualitative SWE-Bench Pro and Terminal-Bench 2.0 comparisons but not machine-readable numeric scores, so no benchmark values are inferred here.',
 '{"verification_pass":"openai-remaining-2026-09-07","launch_stage":"research_preview","serving_partner":"Cerebras"}'::jsonb),
('gpt-5-3-instant','GPT-5.3 Instant','2026-03-03','2026-03-03','proprietary','GPT-5.3',
 '{"Developer":"OpenAI","Release date":"2026-03-03","API model ID":"gpt-5.3-chat-latest","Context window":"128K","Max output":"16K","Knowledge cutoff":"Aug 31, 2025","Input / 1M tokens":"$1.75","Cached input / 1M":"$0.175","Output / 1M tokens":"$14","Text input":"Yes","Image / vision input":"Yes","Audio input":"No","Video input":"No","Text output":"Yes","Image output":"No native output","Audio output":"No","Video output":"No","Tool / function calling":"Yes","Computer use":"No native computer-use model support documented","API access":"Deprecated API alias — gpt-5.3-chat-latest","Product access":"Legacy ChatGPT model; replaced by GPT-5.5 Instant","Weights / license":"Proprietary"}'::jsonb,
 '[{"title":"GPT-5.3 Chat API model page","url":"https://developers.openai.com/api/docs/models/gpt-5.3-chat-latest"},{"title":"GPT-5.3 Instant launch","url":"https://openai.com/index/gpt-5-3-instant/"}]'::jsonb,
 'Former ChatGPT default Instant model. OpenAI has deprecated the API alias and recommends newer models; no comparison-safe public benchmark table was published with the product update.',
 '{"verification_pass":"openai-remaining-2026-09-07","catalog_status":"deprecated","replacement":"gpt-5-5-instant"}'::jsonb),
('gpt-5-4','GPT-5.4','2026-03-05','2026-03-05','proprietary','GPT-5.4',
 '{"Developer":"OpenAI","Release date":"2026-03-05","API model ID":"gpt-5.4","Context window":"1.05M","Max output":"128K","Knowledge cutoff":"Aug 31, 2025","Reasoning / effort":"none (default) / low / medium / high / xhigh","Input / 1M tokens":"$2.50","Cached input / 1M":"$0.25","Output / 1M tokens":"$15","Long-context surcharge":">272K input: 2× input and 1.5× output for the full session","Text input":"Yes","Image / vision input":"Yes","Audio input":"No","Video input":"No","Text output":"Yes","Image output":"No native output; image-generation tool supported","Audio output":"No","Video output":"No","Tool / function calling":"Yes","Computer use":"Yes — native Responses API computer use","API access":"Yes — OpenAI API","Product access":"ChatGPT + Codex + OpenAI API","Weights / license":"Proprietary"}'::jsonb,
 '[{"title":"GPT-5.4 API model page","url":"https://developers.openai.com/api/docs/models/gpt-5.4"},{"title":"Introducing GPT-5.4","url":"https://openai.com/index/introducing-gpt-5-4/"},{"title":"Introducing GPT-5.5","url":"https://openai.com/index/introducing-gpt-5-5/"}]'::jsonb,
 'General-purpose reasoning model with native computer use and tool search. Benchmark rows use OpenAI''s latest published reruns where the GPT-5.5 launch updated prior GPT-5.4 values.',
 '{"verification_pass":"openai-remaining-2026-09-07","snapshot":"gpt-5.4-2026-03-05"}'::jsonb),
('gpt-5-4-pro','GPT-5.4 Pro','2026-03-05','2026-03-05','proprietary','GPT-5.4',
 '{"Developer":"OpenAI","Release date":"2026-03-05","API model ID":"gpt-5.4-pro","Context window":"1.05M","Max output":"128K","Knowledge cutoff":"Aug 31, 2025","Reasoning / effort":"medium (default) / high / xhigh","Input / 1M tokens":"$30","Cached input / 1M":"No cached-input discount","Output / 1M tokens":"$180","Long-context surcharge":">272K input: 2× input and 1.5× output for the full session","Text input":"Yes","Image / vision input":"Yes","Audio input":"No","Video input":"No","Text output":"Yes","Image output":"No native output; image-generation tool supported","Audio output":"No","Video output":"No","Tool / function calling":"Yes","Computer use":"Yes","API access":"Responses API + Batch API","Product access":"ChatGPT Pro + OpenAI API","Weights / license":"Proprietary"}'::jsonb,
 '[{"title":"GPT-5.4 Pro API model page","url":"https://developers.openai.com/api/docs/models/gpt-5.4-pro"},{"title":"Introducing GPT-5.4","url":"https://openai.com/index/introducing-gpt-5-4/"},{"title":"Introducing GPT-5.5","url":"https://openai.com/index/introducing-gpt-5-5/"}]'::jsonb,
 'Higher-compute GPT-5.4 variant. Responses API is the supported interactive API surface; no cached-input discount is offered.',
 '{"verification_pass":"openai-remaining-2026-09-07","snapshot":"gpt-5.4-pro-2026-03-05"}'::jsonb),
('gpt-5-5-pro','GPT-5.5 Pro','2026-04-23','2026-04-24','proprietary','GPT-5.5',
 '{"Developer":"OpenAI","Release date":"2026-04-23","API model ID":"gpt-5.5-pro","Context window":"1.05M","Max output":"128K","Knowledge cutoff":"Dec 1, 2025","Reasoning / effort":"medium / high (default) / xhigh","Input / 1M tokens":"$30","Cached input / 1M":"No cached-input discount","Output / 1M tokens":"$180","Text input":"Yes","Image / vision input":"Yes","Audio input":"No","Video input":"No","Text output":"Yes","Image output":"No native output; image-generation tool supported","Audio output":"No","Video output":"No","Tool / function calling":"Yes","Computer use":"No","API access":"Responses API + Batch API","Product access":"ChatGPT Pro / Business / Enterprise + OpenAI API","Weights / license":"Proprietary"}'::jsonb,
 '[{"title":"GPT-5.5 Pro API model page","url":"https://developers.openai.com/api/docs/models/gpt-5.5-pro"},{"title":"Introducing GPT-5.5","url":"https://openai.com/index/introducing-gpt-5-5/"}]'::jsonb,
 'Higher-compute GPT-5.5 variant. OpenAI explicitly lists computer use as unsupported and does not offer a cached-input discount.',
 '{"verification_pass":"openai-remaining-2026-09-07","snapshot":"gpt-5.5-pro-2026-04-23"}'::jsonb),
('gpt-5-5-instant','GPT-5.5 Instant','2026-05-05','2026-05-05','proprietary','GPT-5.5',
 '{"Developer":"OpenAI","Release date":"2026-05-05","API model ID":"chat-latest (GPT-5.5 Instant rolling alias)","Context window":"400K","Max output":"128K","Knowledge cutoff":"Aug 31, 2025","Input / 1M tokens":"$5","Cached input / 1M":"$0.50","Output / 1M tokens":"$30","Text input":"Yes","Image / vision input":"Yes","Audio input":"No","Video input":"No","Text output":"Yes","Image output":"No native output; image-generation tool supported","Audio output":"No","Video output":"No","Tool / function calling":"Yes","Computer use":"No","API access":"Yes — chat-latest rolling alias","Product access":"Default Instant model in ChatGPT + OpenAI API","Weights / license":"Proprietary"}'::jsonb,
 '[{"title":"Chat Latest API model page","url":"https://developers.openai.com/api/docs/models/chat-latest"},{"title":"GPT-5.5 Instant launch","url":"https://openai.com/index/gpt-5-5-instant/"},{"title":"GPT-5.5 Instant system card","url":"https://openai.com/index/gpt-5-5-instant-system-card/"}]'::jsonb,
 'GPT-5.5 Instant replaced GPT-5.3 Instant as ChatGPT''s default Instant model. The API uses the rolling chat-latest alias, whose underlying snapshot can change; no stable comparison-safe benchmark suite is attached to that alias.',
 '{"verification_pass":"openai-remaining-2026-09-07","rolling_api_alias":"chat-latest"}'::jsonb)
)
INSERT INTO models(slug,name,developer,release_date,ga_date,access,family,comparison_data,sources,notes,metadata,verified_at)
SELECT slug,name,'OpenAI',release_date::date,ga_date::date,access,family,comparison_data,sources,notes,metadata,NOW() FROM s
ON CONFLICT(slug) DO UPDATE SET name=EXCLUDED.name,developer=EXCLUDED.developer,release_date=EXCLUDED.release_date,ga_date=EXCLUDED.ga_date,access=EXCLUDED.access,family=EXCLUDED.family,comparison_data=COALESCE(models.comparison_data,'{}'::jsonb)||EXCLUDED.comparison_data,sources=EXCLUDED.sources,notes=EXCLUDED.notes,metadata=COALESCE(models.metadata,'{}'::jsonb)||EXCLUDED.metadata,verified_at=NOW(),updated_at=NOW();

WITH b(model_slug,category,benchmark_name,benchmark_version,score_numeric,score_unit,tools,reasoning_effort,harness,evaluator,evaluation_date,source,notes) AS (VALUES
('gpt-5-3-codex','coding','SWE-bench Pro','Public',56.8,'percent','','xhigh','OpenAI launch evaluation','OpenAI','2026-02-05','https://openai.com/index/introducing-gpt-5-3-codex/',''),
('gpt-5-3-codex','coding','Terminal-Bench 2.0','',77.3,'percent','','xhigh','OpenAI launch evaluation','OpenAI','2026-02-05','https://openai.com/index/introducing-gpt-5-3-codex/',''),
('gpt-5-3-codex','agentic_computer_use','OSWorld-Verified','',74.0,'percent','true','xhigh','OpenAI revised evaluation','OpenAI','2026-03-05','https://openai.com/index/introducing-gpt-5-4/','Supersedes the originally reported 64.7%; OpenAI reports 74.0% with the API parameter that preserves original image resolution.'),
('gpt-5-3-codex','agentic_computer_use','BrowseComp','',77.3,'percent','true','xhigh','OpenAI GPT-5.4 comparison suite','OpenAI','2026-03-05','https://openai.com/index/introducing-gpt-5-4/',''),
('gpt-5-3-codex','agentic_computer_use','Toolathlon','',51.9,'percent','true','xhigh','OpenAI GPT-5.4 comparison suite','OpenAI','2026-03-05','https://openai.com/index/introducing-gpt-5-4/',''),

('gpt-5-4','coding','SWE-bench Pro','Public',57.7,'percent','','xhigh','OpenAI evaluation','OpenAI','2026-04-23','https://openai.com/index/introducing-gpt-5-5/','Latest OpenAI comparison table.'),
('gpt-5-4','coding','Terminal-Bench 2.0','',75.1,'percent','','xhigh','OpenAI evaluation','OpenAI','2026-04-23','https://openai.com/index/introducing-gpt-5-5/','Latest OpenAI comparison table.'),
('gpt-5-4','agentic_computer_use','OSWorld-Verified','',75.0,'percent','true','xhigh','OpenAI evaluation','OpenAI','2026-04-23','https://openai.com/index/introducing-gpt-5-5/',''),
('gpt-5-4','agentic_computer_use','BrowseComp','',82.7,'percent','true','xhigh','ChatGPT search tool','OpenAI','2026-04-23','https://openai.com/index/introducing-gpt-5-5/',''),
('gpt-5-4','agentic_computer_use','MCP Atlas','Public',70.6,'percent','true','xhigh','Scale AI April 2026 update','OpenAI','2026-04-23','https://openai.com/index/introducing-gpt-5-5/','Result reflects Scale AI''s latest April 2026 benchmark update.'),
('gpt-5-4','agentic_computer_use','Toolathlon','',54.6,'percent','true','xhigh','OpenAI evaluation','OpenAI','2026-04-23','https://openai.com/index/introducing-gpt-5-5/',''),
('gpt-5-4','knowledge','GPQA Diamond','',92.8,'percent','false','xhigh','OpenAI evaluation','OpenAI','2026-04-23','https://openai.com/index/introducing-gpt-5-5/',''),
('gpt-5-4','knowledge','Humanity''s Last Exam','',39.8,'percent','false','xhigh','OpenAI evaluation','OpenAI','2026-04-23','https://openai.com/index/introducing-gpt-5-5/',''),
('gpt-5-4','knowledge','Humanity''s Last Exam','',52.1,'percent','true','xhigh','OpenAI evaluation','OpenAI','2026-04-23','https://openai.com/index/introducing-gpt-5-5/',''),
('gpt-5-4','math_reasoning','FrontierMath','Tier 1–3',47.6,'percent','false','xhigh','OpenAI evaluation','OpenAI','2026-04-23','https://openai.com/index/introducing-gpt-5-5/','Do not conflate with FrontierMath Tier 4 or FrontierMath v2.'),
('gpt-5-4','math_reasoning','FrontierMath','Tier 4',27.1,'percent','false','xhigh','OpenAI evaluation','OpenAI','2026-04-23','https://openai.com/index/introducing-gpt-5-5/','Do not conflate with Tier 1–3 or FrontierMath Tier 4 v2.'),

('gpt-5-4-pro','agentic_computer_use','BrowseComp','',89.3,'percent','true','xhigh','ChatGPT search tool','OpenAI','2026-04-23','https://openai.com/index/introducing-gpt-5-5/',''),
('gpt-5-4-pro','knowledge','GPQA Diamond','',94.4,'percent','false','xhigh','OpenAI evaluation','OpenAI','2026-04-23','https://openai.com/index/introducing-gpt-5-5/',''),
('gpt-5-4-pro','knowledge','Humanity''s Last Exam','',42.7,'percent','false','xhigh','OpenAI evaluation','OpenAI','2026-04-23','https://openai.com/index/introducing-gpt-5-5/',''),
('gpt-5-4-pro','knowledge','Humanity''s Last Exam','',58.7,'percent','true','xhigh','OpenAI evaluation','OpenAI','2026-04-23','https://openai.com/index/introducing-gpt-5-5/',''),
('gpt-5-4-pro','math_reasoning','FrontierMath','Tier 1–3',50.0,'percent','false','xhigh','OpenAI evaluation','OpenAI','2026-04-23','https://openai.com/index/introducing-gpt-5-5/',''),
('gpt-5-4-pro','math_reasoning','FrontierMath','Tier 4',38.0,'percent','false','xhigh','OpenAI evaluation','OpenAI','2026-04-23','https://openai.com/index/introducing-gpt-5-5/',''),

('gpt-5-5-pro','agentic_computer_use','BrowseComp','',90.1,'percent','true','xhigh','ChatGPT search tool','OpenAI','2026-04-23','https://openai.com/index/introducing-gpt-5-5/',''),
('gpt-5-5-pro','knowledge','Humanity''s Last Exam','',43.1,'percent','false','xhigh','OpenAI evaluation','OpenAI','2026-04-23','https://openai.com/index/introducing-gpt-5-5/',''),
('gpt-5-5-pro','knowledge','Humanity''s Last Exam','',57.2,'percent','true','xhigh','OpenAI evaluation','OpenAI','2026-04-23','https://openai.com/index/introducing-gpt-5-5/',''),
('gpt-5-5-pro','math_reasoning','FrontierMath','Tier 1–3',52.4,'percent','false','xhigh','OpenAI evaluation','OpenAI','2026-04-23','https://openai.com/index/introducing-gpt-5-5/',''),
('gpt-5-5-pro','math_reasoning','FrontierMath','Tier 4',39.6,'percent','false','xhigh','OpenAI evaluation','OpenAI','2026-04-23','https://openai.com/index/introducing-gpt-5-5/','')
)
INSERT INTO model_benchmarks(id,model_slug,category,benchmark_name,benchmark_version,score_numeric,score_display,score_unit,tools,reasoning_effort,harness,evaluator,evaluation_date,source,notes,updated_at)
SELECT 'tq-20260907-034-'||substr(md5(concat_ws('|',model_slug,benchmark_name,benchmark_version,score_numeric::text,tools,reasoning_effort,harness,evaluator)),1,20),model_slug,category,benchmark_name,NULLIF(benchmark_version,''),score_numeric,
 CASE WHEN score_unit='elo' THEN trim(to_char(score_numeric,'FM9999990'))||' Elo' ELSE trim(to_char(score_numeric,'FM999990.0'))||'%' END,
 score_unit,CASE WHEN tools='' THEN NULL ELSE tools::boolean END,NULLIF(reasoning_effort,''),NULLIF(harness,''),evaluator,evaluation_date::date,source,NULLIF(notes,''),NOW()
FROM b
ON CONFLICT(id) DO UPDATE SET model_slug=EXCLUDED.model_slug,category=EXCLUDED.category,benchmark_name=EXCLUDED.benchmark_name,benchmark_version=EXCLUDED.benchmark_version,score_numeric=EXCLUDED.score_numeric,score_display=EXCLUDED.score_display,score_unit=EXCLUDED.score_unit,tools=EXCLUDED.tools,reasoning_effort=EXCLUDED.reasoning_effort,harness=EXCLUDED.harness,evaluator=EXCLUDED.evaluator,evaluation_date=EXCLUDED.evaluation_date,source=EXCLUDED.source,notes=EXCLUDED.notes,updated_at=NOW();

WITH r AS (
 SELECT b.model_slug,b.benchmark_name,b.evaluation_date,b.id,b.score_display||CASE WHEN concat_ws('; ',CASE WHEN b.benchmark_version IS NOT NULL AND lower(trim(b.benchmark_version))<>'public' AND position(lower(b.benchmark_version) in lower(b.benchmark_name))=0 THEN b.benchmark_version END,CASE WHEN b.tools IS TRUE THEN 'tools' WHEN b.tools IS FALSE THEN 'no tools' END,b.reasoning_effort)<>'' THEN ' ('||concat_ws('; ',CASE WHEN b.benchmark_version IS NOT NULL AND lower(trim(b.benchmark_version))<>'public' AND position(lower(b.benchmark_version) in lower(b.benchmark_name))=0 THEN b.benchmark_version END,CASE WHEN b.tools IS TRUE THEN 'tools' WHEN b.tools IS FALSE THEN 'no tools' END,b.reasoning_effort)||')' ELSE '' END rendered
 FROM model_benchmarks b WHERE b.model_slug IN ('gpt-5-3-codex','gpt-5-3-codex-spark','gpt-5-3-instant','gpt-5-4','gpt-5-4-pro','gpt-5-5-pro','gpt-5-5-instant')
),g AS (SELECT model_slug,benchmark_name,string_agg(rendered,' · ' ORDER BY evaluation_date NULLS LAST,id) rendered FROM r GROUP BY model_slug,benchmark_name),x AS (
 SELECT c.id,jsonb_agg(CASE WHEN jsonb_typeof(be.block->'rows')='array' THEN jsonb_set(be.block,'{rows}',COALESCE((SELECT jsonb_agg(CASE WHEN jsonb_typeof(re.row_value)='array' AND jsonb_array_length(re.row_value)>=3 THEN jsonb_set(jsonb_set(re.row_value,'{1}',to_jsonb(CASE WHEN COALESCE(re.row_value->>1,'')='' AND a.rendered IS NOT NULL THEN a.rendered ELSE COALESCE(re.row_value->>1,'') END),false),'{2}',to_jsonb(CASE WHEN COALESCE(re.row_value->>2,'')='' AND d.rendered IS NOT NULL THEN d.rendered ELSE COALESCE(re.row_value->>2,'') END),false) ELSE re.row_value END ORDER BY re.ord) FROM jsonb_array_elements(be.block->'rows') WITH ORDINALITY re(row_value,ord) LEFT JOIN g a ON a.model_slug=c.metadata->>'modelA' AND lower(a.benchmark_name)=lower(COALESCE(re.row_value->>0,'')) LEFT JOIN g d ON d.model_slug=c.metadata->>'modelB' AND lower(d.benchmark_name)=lower(COALESCE(re.row_value->>0,''))),'[]'::jsonb),true) ELSE be.block END ORDER BY be.ord) blocks
 FROM content_items c CROSS JOIN LATERAL jsonb_array_elements(COALESCE(c.blocks,'[]'::jsonb)) WITH ORDINALITY be(block,ord)
 WHERE c.kind='comparison' AND (c.metadata->>'modelA' IN ('gpt-5-3-codex','gpt-5-3-codex-spark','gpt-5-3-instant','gpt-5-4','gpt-5-4-pro','gpt-5-5-pro','gpt-5-5-instant') OR c.metadata->>'modelB' IN ('gpt-5-3-codex','gpt-5-3-codex-spark','gpt-5-3-instant','gpt-5-4','gpt-5-4-pro','gpt-5-5-pro','gpt-5-5-instant')) GROUP BY c.id,c.metadata)
UPDATE content_items c SET blocks=x.blocks,updated_at=NOW() FROM x WHERE c.id=x.id AND c.blocks IS DISTINCT FROM x.blocks;
