-- Detailed enrichment for Claude Mythos Preview, Mythos 5 and Mythos 5.1. Sources verified 2026-09-07.
WITH s(slug,name,release_date,ga_date,comparison_data,sources,notes,metadata) AS (VALUES
('claude-mythos-preview','Claude Mythos Preview','2026-04-07',NULL,
 '{"Developer":"Anthropic","Release date":"2026-04-07","API model ID":"claude-mythos-preview (Project Glasswing gated preview)","Context window":"1M","Max output":"128K","Reasoning / effort":"Adaptive thinking; standard capability evals use max effort","Text input":"Yes","Image / vision input":"Yes","Audio input":"No","Video input":"No","Text output":"Yes","Image output":"No","Audio output":"No","Video output":"No","Tool / function calling":"Yes","Computer use":"Yes — agentic search and computer-use evaluation support","API access":"Restricted Project Glasswing access only","Product access":"Project Glasswing vetted organizations","Weights / license":"Restricted proprietary research preview"}'::jsonb,
 '[{"title":"Project Glasswing","url":"https://www.anthropic.com/glasswing"},{"title":"Claude Mythos Preview System Card","url":"https://www.anthropic.com/research/claude-mythos-preview-system-card"}]'::jsonb,
 'General-purpose unreleased frontier model used in Project Glasswing. Anthropic did not make Mythos Preview generally available. Historical per-token pricing is intentionally omitted because current first-party docs do not publish a stable rate for the retired gated preview.',
 '{"verification_pass":"anthropic-mythos-2026-09-07","launch_stage":"research_preview","catalog_status":"superseded","project":"Glasswing"}'::jsonb),
('claude-mythos-5','Claude Mythos 5','2026-06-09','2026-06-09',
 '{"Developer":"Anthropic","Release date":"2026-06-09","API model ID":"claude-mythos-5","Context window":"1M","Max output":"128K","Knowledge cutoff":"Jan 2026","Reasoning / effort":"Adaptive thinking (always on); default high","Input / 1M tokens":"$10","Cached input / 1M":"$1","Cache write / 1M":"$12.50 (5m) / $20 (1h)","Output / 1M tokens":"$50","Batch / flex discount":"Batch API: 50% discount on input and output","Text input":"Yes","Image / vision input":"Yes","Audio input":"No","Video input":"No","Text output":"Yes","Image output":"No","Audio output":"No","Video output":"No","Tool / function calling":"Yes","Computer use":"Yes","API access":"Invite only — Claude API","Product access":"Project Glasswing + Amazon Bedrock + Google Cloud + Microsoft Foundry for approved organizations","Weights / license":"Restricted proprietary — invite only"}'::jsonb,
 '[{"title":"Claude Mythos 5 model overview","url":"https://platform.claude.com/docs/en/models/mythos-5/overview"},{"title":"Claude Fable 5 and Claude Mythos 5 launch","url":"https://www.anthropic.com/news/claude-fable-5-mythos-5"}]'::jsonb,
 'Invite-only Project Glasswing model. Anthropic states that Mythos 5 shares Claude Fable 5 specifications and pricing; capability rows inherited below are limited to ordinary evaluations and explicitly exclude OSWorld-family and AutomationBench results that may be safeguard-sensitive.',
 '{"verification_pass":"anthropic-mythos-2026-09-07","launch_stage":"invite_only","shared_underlying_model":"claude-fable-5","project":"Glasswing"}'::jsonb),
('claude-mythos-5-1','Claude Mythos 5.1','2026-09-01','2026-09-01',
 '{"Developer":"Anthropic","Release date":"2026-09-01","API model ID":"claude-mythos-5-1","Context window":"1M","Max output":"128K","Knowledge cutoff":"Jun 2026","Reasoning / effort":"Adaptive thinking (always on); default high; per-message effort","Input / 1M tokens":"$10","Cached input / 1M":"$0.25","Cache write / 1M":"$12.50 (5m) / $20 (1h)","Output / 1M tokens":"$50","Batch / flex discount":"Batch API: 50% discount on input and output","Text input":"Yes","Image / vision input":"Yes","Audio input":"No","Video input":"No","Text output":"Yes","Image output":"No","Audio output":"No","Video output":"No","Tool / function calling":"Yes","Computer use":"Yes","API access":"Invite only — Claude API","Product access":"Project Glasswing + Amazon Bedrock + Google Cloud + Microsoft Foundry for approved organizations","Weights / license":"Restricted proprietary — invite only"}'::jsonb,
 '[{"title":"Claude Mythos 5.1 model overview","url":"https://platform.claude.com/docs/en/models/mythos-5-1/overview"},{"title":"Claude Mythos product page","url":"https://www.anthropic.com/claude/mythos"},{"title":"Claude Platform release notes","url":"https://platform.claude.com/docs/en/release-notes/overview"}]'::jsonb,
 'Current invite-only Mythos model. Anthropic states Mythos 5.1 has the same capabilities, specifications and pricing as Claude Fable 5.1 for Project Glasswing participants; safeguard-sensitive computer-use evaluations are not inherited.',
 '{"verification_pass":"anthropic-mythos-2026-09-07","launch_stage":"invite_only","shared_underlying_model":"claude-fable-5-1","project":"Glasswing"}'::jsonb)
)
INSERT INTO models(slug,name,developer,release_date,ga_date,access,family,comparison_data,sources,notes,metadata,verified_at)
SELECT slug,name,'Anthropic',release_date::date,NULLIF(ga_date,'')::date,'restricted',CASE WHEN slug='claude-mythos-preview' THEN 'Claude Mythos' WHEN slug='claude-mythos-5' THEN 'Claude 5' ELSE 'Claude 5.1' END,comparison_data,sources,notes,metadata,NOW() FROM s
ON CONFLICT(slug) DO UPDATE SET name=EXCLUDED.name,developer=EXCLUDED.developer,release_date=EXCLUDED.release_date,ga_date=EXCLUDED.ga_date,access=EXCLUDED.access,family=EXCLUDED.family,comparison_data=COALESCE(models.comparison_data,'{}'::jsonb)||EXCLUDED.comparison_data,sources=EXCLUDED.sources,notes=EXCLUDED.notes,metadata=COALESCE(models.metadata,'{}'::jsonb)||EXCLUDED.metadata,verified_at=NOW(),updated_at=NOW();

-- Direct Anthropic evaluations for Mythos Preview.
WITH b(model_slug,category,benchmark_name,benchmark_version,score_numeric,tools,reasoning_effort,harness,evaluator,evaluation_date,source,notes) AS (VALUES
('claude-mythos-preview','coding','SWE-bench Verified','',93.9,'','max','Anthropic Mythos Preview system-card harness','Anthropic','2026-04-07','https://www.anthropic.com/glasswing','Averaged over five trials.'),
('claude-mythos-preview','coding','SWE-bench Pro','',77.8,'','max','Anthropic Mythos Preview system-card harness','Anthropic','2026-04-07','https://www.anthropic.com/glasswing','Averaged over five trials.'),
('claude-mythos-preview','coding','Terminal-Bench 2.0','',82.0,'','max','Terminus-2; 1M-token task budget','Anthropic','2026-04-07','https://www.anthropic.com/glasswing','1× guaranteed / 3× ceiling resources, averaged over five attempts per task.'),
('claude-mythos-preview','coding','Terminal-Bench 2.1','4h timeout',92.1,'','max','Terminus-2; Terminal-Bench 2.1 updates','Anthropic','2026-04-07','https://www.anthropic.com/glasswing','Anthropic reports 92.1% after increasing timeout limits to four hours and applying Terminal-Bench 2.1 updates.'),
('claude-mythos-preview','knowledge','GPQA Diamond','',94.6,'false','max','Anthropic system-card evaluation','Anthropic','2026-04-07','https://www.anthropic.com/glasswing','System card gives 94.55%, rounded to one decimal for display consistency.'),
('claude-mythos-preview','knowledge','Humanity''s Last Exam','',56.8,'false','max','Anthropic system-card evaluation','Anthropic','2026-04-07','https://www.anthropic.com/glasswing','No-tools condition.'),
('claude-mythos-preview','knowledge','Humanity''s Last Exam','',64.7,'true','max','Anthropic system-card evaluation','Anthropic','2026-04-07','https://www.anthropic.com/glasswing','With-tools condition.'),
('claude-mythos-preview','agentic_computer_use','BrowseComp','',86.9,'true','max','Anthropic agentic search evaluation','Anthropic','2026-04-07','https://www.anthropic.com/glasswing','Anthropic reports Mythos Preview used 4.9× fewer tokens than Opus 4.6 in this evaluation.'),
('claude-mythos-preview','agentic_computer_use','OSWorld-Verified','',79.6,'true','max','Anthropic computer-use evaluation','Anthropic','2026-04-07','https://www.anthropic.com/glasswing','Direct Mythos Preview evaluation; do not transfer this value to safeguarded Fable/Mythos descendants.')
)
INSERT INTO model_benchmarks(id,model_slug,category,benchmark_name,benchmark_version,score_numeric,score_display,score_unit,tools,reasoning_effort,harness,evaluator,evaluation_date,source,notes,updated_at)
SELECT 'tq-20260907-035-preview-'||substr(md5(concat_ws('|',benchmark_name,benchmark_version,score_numeric::text,tools,reasoning_effort,harness)),1,20),model_slug,category,benchmark_name,NULLIF(benchmark_version,''),score_numeric,trim(to_char(score_numeric,'FM999990.0'))||'%','percent',CASE WHEN tools='' THEN NULL ELSE tools::boolean END,NULLIF(reasoning_effort,''),harness,evaluator,evaluation_date::date,source,NULLIF(notes,''),NOW() FROM b
ON CONFLICT(id) DO UPDATE SET model_slug=EXCLUDED.model_slug,category=EXCLUDED.category,benchmark_name=EXCLUDED.benchmark_name,benchmark_version=EXCLUDED.benchmark_version,score_numeric=EXCLUDED.score_numeric,score_display=EXCLUDED.score_display,score_unit=EXCLUDED.score_unit,tools=EXCLUDED.tools,reasoning_effort=EXCLUDED.reasoning_effort,harness=EXCLUDED.harness,evaluator=EXCLUDED.evaluator,evaluation_date=EXCLUDED.evaluation_date,source=EXCLUDED.source,notes=EXCLUDED.notes,updated_at=NOW();

-- Anthropic documents Mythos 5 and Fable 5 as the same underlying model, and likewise Mythos 5.1/Fable 5.1.
-- Copy ordinary capability evaluations while deliberately excluding OSWorld-family and AutomationBench rows,
-- where changed safeguards can affect outcomes. Preserve the original evaluator/harness/source provenance.
INSERT INTO model_benchmarks(id,model_slug,category,benchmark_name,benchmark_version,score_numeric,score_display,score_unit,tools,reasoning_effort,harness,evaluator,evaluation_date,source,notes,updated_at)
SELECT 'tq-20260907-035-mythos5-'||substr(md5(src.id),1,20),'claude-mythos-5',src.category,src.benchmark_name,src.benchmark_version,src.score_numeric,src.score_display,src.score_unit,src.tools,src.reasoning_effort,src.harness,src.evaluator,src.evaluation_date,src.source,
 concat_ws(' ', 'Shared underlying model with Claude Fable 5 per Anthropic; inherited ordinary capability evaluation.', src.notes),NOW()
FROM model_benchmarks src
WHERE src.model_slug='claude-fable-5' AND src.benchmark_name NOT ILIKE 'OSWorld%' AND src.benchmark_name<>'AutomationBench'
ON CONFLICT(id) DO UPDATE SET model_slug=EXCLUDED.model_slug,category=EXCLUDED.category,benchmark_name=EXCLUDED.benchmark_name,benchmark_version=EXCLUDED.benchmark_version,score_numeric=EXCLUDED.score_numeric,score_display=EXCLUDED.score_display,score_unit=EXCLUDED.score_unit,tools=EXCLUDED.tools,reasoning_effort=EXCLUDED.reasoning_effort,harness=EXCLUDED.harness,evaluator=EXCLUDED.evaluator,evaluation_date=EXCLUDED.evaluation_date,source=EXCLUDED.source,notes=EXCLUDED.notes,updated_at=NOW();

INSERT INTO model_benchmarks(id,model_slug,category,benchmark_name,benchmark_version,score_numeric,score_display,score_unit,tools,reasoning_effort,harness,evaluator,evaluation_date,source,notes,updated_at)
SELECT 'tq-20260907-035-mythos51-'||substr(md5(src.id),1,20),'claude-mythos-5-1',src.category,src.benchmark_name,src.benchmark_version,src.score_numeric,src.score_display,src.score_unit,src.tools,src.reasoning_effort,src.harness,src.evaluator,src.evaluation_date,src.source,
 concat_ws(' ', 'Shared underlying model with Claude Fable 5.1 per Anthropic; inherited ordinary capability evaluation.', src.notes),NOW()
FROM model_benchmarks src
WHERE src.model_slug='claude-fable-5-1' AND src.benchmark_name NOT ILIKE 'OSWorld%' AND src.benchmark_name<>'AutomationBench'
ON CONFLICT(id) DO UPDATE SET model_slug=EXCLUDED.model_slug,category=EXCLUDED.category,benchmark_name=EXCLUDED.benchmark_name,benchmark_version=EXCLUDED.benchmark_version,score_numeric=EXCLUDED.score_numeric,score_display=EXCLUDED.score_display,score_unit=EXCLUDED.score_unit,tools=EXCLUDED.tools,reasoning_effort=EXCLUDED.reasoning_effort,harness=EXCLUDED.harness,evaluator=EXCLUDED.evaluator,evaluation_date=EXCLUDED.evaluation_date,source=EXCLUDED.source,notes=EXCLUDED.notes,updated_at=NOW();

WITH r AS (
 SELECT b.model_slug,b.benchmark_name,b.evaluation_date,b.id,b.score_display||CASE WHEN concat_ws('; ',CASE WHEN b.benchmark_version IS NOT NULL AND lower(trim(b.benchmark_version))<>'public' AND position(lower(b.benchmark_version) in lower(b.benchmark_name))=0 THEN b.benchmark_version END,CASE WHEN b.tools IS TRUE THEN 'tools' WHEN b.tools IS FALSE THEN 'no tools' END,b.reasoning_effort)<>'' THEN ' ('||concat_ws('; ',CASE WHEN b.benchmark_version IS NOT NULL AND lower(trim(b.benchmark_version))<>'public' AND position(lower(b.benchmark_version) in lower(b.benchmark_name))=0 THEN b.benchmark_version END,CASE WHEN b.tools IS TRUE THEN 'tools' WHEN b.tools IS FALSE THEN 'no tools' END,b.reasoning_effort)||')' ELSE '' END rendered
 FROM model_benchmarks b WHERE b.model_slug IN ('claude-mythos-preview','claude-mythos-5','claude-mythos-5-1')
),g AS (SELECT model_slug,benchmark_name,string_agg(rendered,' · ' ORDER BY evaluation_date NULLS LAST,id) rendered FROM r GROUP BY model_slug,benchmark_name),x AS (
 SELECT c.id,jsonb_agg(CASE WHEN jsonb_typeof(be.block->'rows')='array' THEN jsonb_set(be.block,'{rows}',COALESCE((SELECT jsonb_agg(CASE WHEN jsonb_typeof(re.row_value)='array' AND jsonb_array_length(re.row_value)>=3 THEN jsonb_set(jsonb_set(re.row_value,'{1}',to_jsonb(CASE WHEN COALESCE(re.row_value->>1,'')='' AND a.rendered IS NOT NULL THEN a.rendered ELSE COALESCE(re.row_value->>1,'') END),false),'{2}',to_jsonb(CASE WHEN COALESCE(re.row_value->>2,'')='' AND d.rendered IS NOT NULL THEN d.rendered ELSE COALESCE(re.row_value->>2,'') END),false) ELSE re.row_value END ORDER BY re.ord) FROM jsonb_array_elements(be.block->'rows') WITH ORDINALITY re(row_value,ord) LEFT JOIN g a ON a.model_slug=c.metadata->>'modelA' AND lower(a.benchmark_name)=lower(COALESCE(re.row_value->>0,'')) LEFT JOIN g d ON d.model_slug=c.metadata->>'modelB' AND lower(d.benchmark_name)=lower(COALESCE(re.row_value->>0,''))),'[]'::jsonb),true) ELSE be.block END ORDER BY be.ord) blocks
 FROM content_items c CROSS JOIN LATERAL jsonb_array_elements(COALESCE(c.blocks,'[]'::jsonb)) WITH ORDINALITY be(block,ord)
 WHERE c.kind='comparison' AND (c.metadata->>'modelA' IN ('claude-mythos-preview','claude-mythos-5','claude-mythos-5-1') OR c.metadata->>'modelB' IN ('claude-mythos-preview','claude-mythos-5','claude-mythos-5-1')) GROUP BY c.id,c.metadata)
UPDATE content_items c SET blocks=x.blocks,updated_at=NOW() FROM x WHERE c.id=x.id AND c.blocks IS DISTINCT FROM x.blocks;
