-- Add Haiku 5.5 specifications, both prompt-length pricing tiers, and
-- independently sourced benchmarks. Composite Intelligence Index and API
-- performance measurements stay in model metadata. Only Haiku benchmark
-- rows are seeded; unknown tool settings and evaluation dates remain NULL.
INSERT INTO models (
  slug, name, developer, release_date, ga_date, access, family,
  comparison_data, sources, notes, metadata, verified_at
)
SELECT
  seed.slug, seed.name, seed.developer, seed.release_date::date,
  seed.ga_date::date, seed.access, seed.family,
  seed.comparison_data, seed.sources, seed.notes, seed.metadata, NOW()
FROM jsonb_to_recordset($models$
[
  {
    "slug": "claude-haiku-5-5",
    "name": "Claude Haiku 5.5",
    "developer": "Anthropic",
    "release_date": "2026-10-07",
    "ga_date": "2026-10-07",
    "access": "proprietary",
    "family": "Claude Haiku 5",
    "comparison_data": {
      "Developer": "Anthropic",
      "Release date": "2026-10-07",
      "API model ID": "claude-haiku-5-5",
      "Context window": "1M tokens",
      "Max output": "128K tokens (300K on Message Batches API beta)",
      "Knowledge cutoff": "June 2026",
      "Reasoning / effort": "Adaptive thinking; low / medium / high / xhigh / max, medium default; thinking can be disabled. Manual extended thinking is not accepted",
      "Input / 1M tokens": "$0.10 for prompts up to 100K tokens; $0.50 above 100K",
      "Cached input / 1M": "$0.01 for prompts up to 100K tokens; $0.05 above 100K",
      "Cache write / 1M": "$0.125 for prompts up to 100K tokens; $0.625 above 100K",
      "Output / 1M tokens": "$0.50 for prompts up to 100K tokens; $2.50 above 100K",
      "Batch / flex discount": "Batch API: 50% off input and output",
      "Long-context surcharge": "Above 100K prompt tokens, all four token rates are 5x the lower tier. Cache reads remain 10% of the input rate",
      "Text input": "Yes",
      "Image / vision input": "Yes",
      "Audio input": "No - Artificial Analysis lists text and image inputs only",
      "Video input": "No - Artificial Analysis lists text and image inputs only",
      "Text output": "Yes",
      "Image output": "No",
      "Audio output": "No",
      "Video output": "No",
      "Tool / function calling": "Yes",
      "Computer use": "Yes; computer-use and browser-use support in the Python and TypeScript SDKs is in beta",
      "API access": "Claude API, Google Cloud, Microsoft Foundry, Claude Platform on AWS, and Amazon Bedrock. Bedrock model ID: anthropic.claude-haiku-5-5",
      "Product access": "Claude Free, Pro, Max, Team and Enterprise on web, iOS and Android; Claude Code",
      "Weights / license": "Proprietary",
      "Primary focus": "High-volume summaries, compaction, database queries, classification, live customer support and browser use",
      "Long-horizon work": "Computer-use and browser tasks. Sonnet 5.5 and Opus 5.5 remain the recommended choices for complex agentic coding",
      "Agent orchestration": "Can serve as a subagent alongside Sonnet 5.5 or Opus 5.5 on coding work",
      "Efficiency / generation change": "Anthropic reports about 75% lower average operating cost than Haiku 4.5 after tokenizer changes. Per-token prices fall 90% up to 100K prompt tokens and 50% above 100K. The updated tokenizer uses slightly more tokens per task",
      "Safety / approvals": "No new Responsible Scaling Policy thresholds; CB-1 and Autonomy-1 mitigations, low assessed catastrophic misalignment risk. Narrower cyber classifiers have no fallback model and still block penetration testing. The system card records API self-harm and child-safety regressions, hallucinations, and undisclosed use of leaked answers"
    },
    "sources": [
      {
        "title": "Introducing Claude Haiku 5.5",
        "url": "https://www.anthropic.com/claude-haiku-5-5"
      },
      {
        "title": "Claude Haiku 5.5 system card",
        "url": "https://www.anthropic.com/claude-haiku-5-5-system-card"
      },
      {
        "title": "TheQuery: Claude Haiku 5.5 model card",
        "url": "https://www.thequery.in/glossary/claude-haiku-5-5"
      },
      {
        "title": "Artificial Analysis: Claude Haiku 5.5 (low)",
        "url": "https://artificialanalysis.ai/models/claude-haiku-5-5-low"
      },
      {
        "title": "Artificial Analysis: Claude Haiku 5.5 (medium)",
        "url": "https://artificialanalysis.ai/models/claude-haiku-5-5-medium"
      },
      {
        "title": "Artificial Analysis: Claude Haiku 5.5 (high)",
        "url": "https://artificialanalysis.ai/models/claude-haiku-5-5-high"
      },
      {
        "title": "Artificial Analysis: Claude Haiku 5.5 (xhigh)",
        "url": "https://artificialanalysis.ai/models/claude-haiku-5-5-xhigh"
      },
      {
        "title": "Artificial Analysis: Claude Haiku 5.5 (max)",
        "url": "https://artificialanalysis.ai/models/claude-haiku-5-5"
      }
    ],
    "notes": "Third release in the Claude 5.5 family, following Opus and Sonnet. Retirement on Anthropic-operated platforms is committed not sooner than October 7, 2027; cloud partners set their own dates. Artificial Analysis Intelligence Index v4.3.2 ranges from 29.45 at low through 34.46 at the default medium setting to 43.40 at max. Its measured index-task cost rises from $0.047 at medium to $0.213 at max, while time to first answer token rises from 13.40 to 432.21 seconds. Output speed is 137.1 tokens/s at medium and 241.9 at max, so generation speed alone does not describe response latency. AA's max-effort Terminal-Bench 4.0 result is 32.8%, below Anthropic's 39.2% launch figure, and the different evaluator and settings are retained rather than treated as the same run. GDPval-AA and AA-Briefcase launch figures round to AA's own max-effort results, so those are stored once from AA. Composite intelligence scores and API speed, latency and cost measurements stay in metadata rather than being mislabeled as individual benchmark results. AA marks SciCode and CritPt under review. All independent figures were observed on October 8, 2026; their exact evaluation dates are not stated.",
    "metadata": {
      "verification_pass": "haiku-5-5-catalog-2026-10-08",
      "catalog_status": "current",
      "default_effort": "medium",
      "retirement_not_before": "2027-10-07",
      "input_modalities": "text, image",
      "output_modalities": "text",
      "independent_intelligence_index": 34.4646519474657,
      "independent_intelligence_index_effort": "medium",
      "artificial_analysis_intelligence_index_version": "v4.3.2",
      "artificial_analysis_observed_at": "2026-10-08",
      "artificial_analysis_effort_profiles": [
        {
          "effort": "low",
          "intelligence_index": 29.4494981304947,
          "output_tokens_per_second": 178.216201483806,
          "time_to_first_answer_token_seconds": 9.93109892900001,
          "index_cost_per_task_usd": 0.02445936101890973,
          "index_output_tokens": 32289694,
          "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-low"
        },
        {
          "effort": "medium",
          "intelligence_index": 34.4646519474657,
          "output_tokens_per_second": 137.050817833707,
          "time_to_first_answer_token_seconds": 13.4043635765,
          "index_cost_per_task_usd": 0.04703084793955566,
          "index_output_tokens": 53785057,
          "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-medium"
        },
        {
          "effort": "high",
          "intelligence_index": 37.8240211671094,
          "output_tokens_per_second": 160.189974136809,
          "time_to_first_answer_token_seconds": 28.005903681,
          "index_cost_per_task_usd": 0.07942671568737021,
          "index_output_tokens": 97096318,
          "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-high"
        },
        {
          "effort": "xhigh",
          "intelligence_index": 41.2489304677024,
          "output_tokens_per_second": 187.17016978754,
          "time_to_first_answer_token_seconds": 86.970932716,
          "index_cost_per_task_usd": 0.12378561092096102,
          "index_output_tokens": 179986858,
          "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-xhigh"
        },
        {
          "effort": "max",
          "intelligence_index": 43.3950199670746,
          "output_tokens_per_second": 241.913830264623,
          "time_to_first_answer_token_seconds": 432.2091159655,
          "index_cost_per_task_usd": 0.21276971216992022,
          "index_output_tokens": 435183286,
          "source": "https://artificialanalysis.ai/models/claude-haiku-5-5"
        }
      ],
      "artificial_analysis_performance_notes": "First-party Anthropic API measurements. Output speed is measured after generation starts; time to first answer token includes reasoning time. Index task cost is a weighted mean across the index evaluations, not a universal workload price.",
      "pricing_tiers": [
        {
          "max_prompt_tokens": 100000,
          "input_per_million_usd": 0.1,
          "output_per_million_usd": 0.5,
          "cache_read_per_million_usd": 0.01,
          "cache_write_per_million_usd": 0.125
        },
        {
          "min_prompt_tokens": 100001,
          "input_per_million_usd": 0.5,
          "output_per_million_usd": 2.5,
          "cache_read_per_million_usd": 0.05,
          "cache_write_per_million_usd": 0.625
        }
      ]
    }
  }
]
$models$::jsonb) AS seed(
  slug TEXT, name TEXT, developer TEXT, release_date TEXT, ga_date TEXT,
  access TEXT, family TEXT, comparison_data JSONB, sources JSONB,
  notes TEXT, metadata JSONB
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  developer = EXCLUDED.developer,
  release_date = EXCLUDED.release_date,
  ga_date = EXCLUDED.ga_date,
  access = EXCLUDED.access,
  family = EXCLUDED.family,
  comparison_data = EXCLUDED.comparison_data,
  sources = EXCLUDED.sources,
  notes = EXCLUDED.notes,
  metadata = COALESCE(models.metadata, '{}'::jsonb) || EXCLUDED.metadata,
  verified_at = NOW(),
  updated_at = NOW();

INSERT INTO model_benchmarks (
  id, model_slug, category, benchmark_name, benchmark_version,
  score_numeric, score_display, score_unit, tools, reasoning_effort,
  harness, evaluator, evaluation_date, source, notes
)
SELECT
  evidence.id, evidence.model_slug, evidence.category,
  evidence.benchmark_name, evidence.benchmark_version,
  evidence.score_numeric, evidence.score_display, evidence.score_unit,
  evidence.tools, evidence.reasoning_effort, evidence.harness,
  evidence.evaluator, evidence.evaluation_date::date, evidence.source, evidence.notes
FROM jsonb_to_recordset($benchmarks$
[
  {
    "id": "tq-20261008-haiku55-aa-low-briefcase",
    "model_slug": "claude-haiku-5-5",
    "category": "agentic_computer_use",
    "benchmark_name": "AA-Briefcase",
    "benchmark_version": "v1.1",
    "score_numeric": 1111.58,
    "score_display": "1111.58 Elo (AA)",
    "score_unit": "Elo",
    "tools": null,
    "reasoning_effort": "low",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-low",
    "notes": "Independent Artificial Analysis model-page result at low effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-low-gdpval",
    "model_slug": "claude-haiku-5-5",
    "category": "agentic_computer_use",
    "benchmark_name": "GDPval-AA",
    "benchmark_version": "v2.1",
    "score_numeric": 1124.94,
    "score_display": "1124.94 Elo (AA)",
    "score_unit": "Elo",
    "tools": null,
    "reasoning_effort": "low",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-low",
    "notes": "Independent Artificial Analysis model-page result at low effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-low-automation",
    "model_slug": "claude-haiku-5-5",
    "category": "agentic_computer_use",
    "benchmark_name": "AutomationBench-AA",
    "benchmark_version": null,
    "score_numeric": 22.910812181110643,
    "score_display": "22.9% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "low",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-low",
    "notes": "Independent Artificial Analysis model-page result at low effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-low-terminal40",
    "model_slug": "claude-haiku-5-5",
    "category": "coding",
    "benchmark_name": "Terminal-Bench 4.0",
    "benchmark_version": null,
    "score_numeric": 12.6262626262626,
    "score_display": "12.6% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "low",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-low",
    "notes": "Independent Artificial Analysis model-page result at low effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-low-scicode",
    "model_slug": "claude-haiku-5-5",
    "category": "coding",
    "benchmark_name": "SciCode",
    "benchmark_version": null,
    "score_numeric": 49.189814814814795,
    "score_display": "49.2% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "low",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-low",
    "notes": "Independent Artificial Analysis model-page result at low effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data. Artificial Analysis marks this evaluation under review."
  },
  {
    "id": "tq-20261008-haiku55-aa-low-hle",
    "model_slug": "claude-haiku-5-5",
    "category": "knowledge",
    "benchmark_name": "Humanity's Last Exam",
    "benchmark_version": null,
    "score_numeric": 27.0157553290083,
    "score_display": "27.0% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "low",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-low",
    "notes": "Independent Artificial Analysis model-page result at low effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-low-gdppdf",
    "model_slug": "claude-haiku-5-5",
    "category": "professional",
    "benchmark_name": "GDP.pdf",
    "benchmark_version": null,
    "score_numeric": 11.200000000000001,
    "score_display": "11.2% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "low",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-low",
    "notes": "Independent Artificial Analysis model-page result at low effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-low-critpt",
    "model_slug": "claude-haiku-5-5",
    "category": "math_reasoning",
    "benchmark_name": "CritPt",
    "benchmark_version": null,
    "score_numeric": 9.14285714285714,
    "score_display": "9.1% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "low",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-low",
    "notes": "Independent Artificial Analysis model-page result at low effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data. Artificial Analysis marks this evaluation under review."
  },
  {
    "id": "tq-20261008-haiku55-aa-low-omniscience-index",
    "model_slug": "claude-haiku-5-5",
    "category": "knowledge",
    "benchmark_name": "AA-Omniscience Index",
    "benchmark_version": null,
    "score_numeric": 3.25,
    "score_display": "3.2 points (AA)",
    "score_unit": "points",
    "tools": null,
    "reasoning_effort": "low",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-low",
    "notes": "Independent Artificial Analysis model-page result at low effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data. Knowledge reliability index on a -100 to 100 scale, not a percentage or hallucination rate."
  },
  {
    "id": "tq-20261008-haiku55-aa-low-omniscience-accuracy",
    "model_slug": "claude-haiku-5-5",
    "category": "knowledge",
    "benchmark_name": "AA-Omniscience Accuracy",
    "benchmark_version": null,
    "score_numeric": 33.25,
    "score_display": "33.2% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "low",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-low",
    "notes": "Independent Artificial Analysis model-page result at low effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-low-omniscience-hallucination",
    "model_slug": "claude-haiku-5-5",
    "category": "knowledge",
    "benchmark_name": "AA-Omniscience Hallucination Rate",
    "benchmark_version": null,
    "score_numeric": 44.9438202247191,
    "score_display": "44.9% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "low",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-low",
    "notes": "Independent Artificial Analysis model-page result at low effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data. Lower is better. This is hallucination rate, not accuracy or the -100 to 100 Omniscience Index."
  },
  {
    "id": "tq-20261008-haiku55-aa-low-lcr",
    "model_slug": "claude-haiku-5-5",
    "category": "other",
    "benchmark_name": "AA-LCR",
    "benchmark_version": "v1.1",
    "score_numeric": 0.72,
    "score_display": "0.720 (AA)",
    "score_unit": "score",
    "tools": null,
    "reasoning_effort": "low",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-low",
    "notes": "Independent Artificial Analysis model-page result at low effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data. Stored on its original 0 to 1 scale to match the existing AA-LCR catalog rows."
  },
  {
    "id": "tq-20261008-haiku55-aa-low-harvey",
    "model_slug": "claude-haiku-5-5",
    "category": "professional",
    "benchmark_name": "Harvey LAB-AA",
    "benchmark_version": null,
    "score_numeric": 87.85641916341001,
    "score_display": "87.9% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "low",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-low",
    "notes": "Independent Artificial Analysis model-page result at low effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data. Criterion pass rate for legal agentic work."
  },
  {
    "id": "tq-20261008-haiku55-aa-low-terminal-science",
    "model_slug": "claude-haiku-5-5",
    "category": "coding",
    "benchmark_name": "Terminal-Bench Science 0.1",
    "benchmark_version": null,
    "score_numeric": 1.9047619047619,
    "score_display": "1.9% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "low",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-low",
    "notes": "Independent Artificial Analysis model-page result at low effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-medium-briefcase",
    "model_slug": "claude-haiku-5-5",
    "category": "agentic_computer_use",
    "benchmark_name": "AA-Briefcase",
    "benchmark_version": "v1.1",
    "score_numeric": 1371.7,
    "score_display": "1371.70 Elo (AA)",
    "score_unit": "Elo",
    "tools": null,
    "reasoning_effort": "medium",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-medium",
    "notes": "Independent Artificial Analysis model-page result at medium effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-medium-gdpval",
    "model_slug": "claude-haiku-5-5",
    "category": "agentic_computer_use",
    "benchmark_name": "GDPval-AA",
    "benchmark_version": "v2.1",
    "score_numeric": 1276.84,
    "score_display": "1276.84 Elo (AA)",
    "score_unit": "Elo",
    "tools": null,
    "reasoning_effort": "medium",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-medium",
    "notes": "Independent Artificial Analysis model-page result at medium effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-medium-automation",
    "model_slug": "claude-haiku-5-5",
    "category": "agentic_computer_use",
    "benchmark_name": "AutomationBench-AA",
    "benchmark_version": null,
    "score_numeric": 28.589614814293164,
    "score_display": "28.6% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "medium",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-medium",
    "notes": "Independent Artificial Analysis model-page result at medium effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-medium-terminal40",
    "model_slug": "claude-haiku-5-5",
    "category": "coding",
    "benchmark_name": "Terminal-Bench 4.0",
    "benchmark_version": null,
    "score_numeric": 15.151515151515198,
    "score_display": "15.2% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "medium",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-medium",
    "notes": "Independent Artificial Analysis model-page result at medium effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-medium-scicode",
    "model_slug": "claude-haiku-5-5",
    "category": "coding",
    "benchmark_name": "SciCode",
    "benchmark_version": null,
    "score_numeric": 48.9583333333333,
    "score_display": "49.0% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "medium",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-medium",
    "notes": "Independent Artificial Analysis model-page result at medium effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data. Artificial Analysis marks this evaluation under review."
  },
  {
    "id": "tq-20261008-haiku55-aa-medium-hle",
    "model_slug": "claude-haiku-5-5",
    "category": "knowledge",
    "benchmark_name": "Humanity's Last Exam",
    "benchmark_version": null,
    "score_numeric": 33.7812789620019,
    "score_display": "33.8% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "medium",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-medium",
    "notes": "Independent Artificial Analysis model-page result at medium effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-medium-gdppdf",
    "model_slug": "claude-haiku-5-5",
    "category": "professional",
    "benchmark_name": "GDP.pdf",
    "benchmark_version": null,
    "score_numeric": 15.2,
    "score_display": "15.2% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "medium",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-medium",
    "notes": "Independent Artificial Analysis model-page result at medium effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-medium-critpt",
    "model_slug": "claude-haiku-5-5",
    "category": "math_reasoning",
    "benchmark_name": "CritPt",
    "benchmark_version": null,
    "score_numeric": 12.8571428571429,
    "score_display": "12.9% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "medium",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-medium",
    "notes": "Independent Artificial Analysis model-page result at medium effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data. Artificial Analysis marks this evaluation under review."
  },
  {
    "id": "tq-20261008-haiku55-aa-medium-omniscience-index",
    "model_slug": "claude-haiku-5-5",
    "category": "knowledge",
    "benchmark_name": "AA-Omniscience Index",
    "benchmark_version": null,
    "score_numeric": 4.466666666666667,
    "score_display": "4.5 points (AA)",
    "score_unit": "points",
    "tools": null,
    "reasoning_effort": "medium",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-medium",
    "notes": "Independent Artificial Analysis model-page result at medium effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data. Knowledge reliability index on a -100 to 100 scale, not a percentage or hallucination rate."
  },
  {
    "id": "tq-20261008-haiku55-aa-medium-omniscience-accuracy",
    "model_slug": "claude-haiku-5-5",
    "category": "knowledge",
    "benchmark_name": "AA-Omniscience Accuracy",
    "benchmark_version": null,
    "score_numeric": 34.03333333333333,
    "score_display": "34.0% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "medium",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-medium",
    "notes": "Independent Artificial Analysis model-page result at medium effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-medium-omniscience-hallucination",
    "model_slug": "claude-haiku-5-5",
    "category": "knowledge",
    "benchmark_name": "AA-Omniscience Hallucination Rate",
    "benchmark_version": null,
    "score_numeric": 44.820616472966144,
    "score_display": "44.8% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "medium",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-medium",
    "notes": "Independent Artificial Analysis model-page result at medium effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data. Lower is better. This is hallucination rate, not accuracy or the -100 to 100 Omniscience Index."
  },
  {
    "id": "tq-20261008-haiku55-aa-medium-lcr",
    "model_slug": "claude-haiku-5-5",
    "category": "other",
    "benchmark_name": "AA-LCR",
    "benchmark_version": "v1.1",
    "score_numeric": 0.773333333333333,
    "score_display": "0.773 (AA)",
    "score_unit": "score",
    "tools": null,
    "reasoning_effort": "medium",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-medium",
    "notes": "Independent Artificial Analysis model-page result at medium effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data. Stored on its original 0 to 1 scale to match the existing AA-LCR catalog rows."
  },
  {
    "id": "tq-20261008-haiku55-aa-medium-harvey",
    "model_slug": "claude-haiku-5-5",
    "category": "professional",
    "benchmark_name": "Harvey LAB-AA",
    "benchmark_version": null,
    "score_numeric": 89.2314372557534,
    "score_display": "89.2% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "medium",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-medium",
    "notes": "Independent Artificial Analysis model-page result at medium effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data. Criterion pass rate for legal agentic work."
  },
  {
    "id": "tq-20261008-haiku55-aa-medium-terminal-science",
    "model_slug": "claude-haiku-5-5",
    "category": "coding",
    "benchmark_name": "Terminal-Bench Science 0.1",
    "benchmark_version": null,
    "score_numeric": 7.14285714285714,
    "score_display": "7.1% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "medium",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-medium",
    "notes": "Independent Artificial Analysis model-page result at medium effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-high-briefcase",
    "model_slug": "claude-haiku-5-5",
    "category": "agentic_computer_use",
    "benchmark_name": "AA-Briefcase",
    "benchmark_version": "v1.1",
    "score_numeric": 1442.55,
    "score_display": "1442.55 Elo (AA)",
    "score_unit": "Elo",
    "tools": null,
    "reasoning_effort": "high",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-high",
    "notes": "Independent Artificial Analysis model-page result at high effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-high-gdpval",
    "model_slug": "claude-haiku-5-5",
    "category": "agentic_computer_use",
    "benchmark_name": "GDPval-AA",
    "benchmark_version": "v2.1",
    "score_numeric": 1420.03,
    "score_display": "1420.03 Elo (AA)",
    "score_unit": "Elo",
    "tools": null,
    "reasoning_effort": "high",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-high",
    "notes": "Independent Artificial Analysis model-page result at high effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-high-automation",
    "model_slug": "claude-haiku-5-5",
    "category": "agentic_computer_use",
    "benchmark_name": "AutomationBench-AA",
    "benchmark_version": null,
    "score_numeric": 33.72685311767238,
    "score_display": "33.7% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "high",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-high",
    "notes": "Independent Artificial Analysis model-page result at high effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-high-terminal40",
    "model_slug": "claude-haiku-5-5",
    "category": "coding",
    "benchmark_name": "Terminal-Bench 4.0",
    "benchmark_version": null,
    "score_numeric": 21.7171717171717,
    "score_display": "21.7% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "high",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-high",
    "notes": "Independent Artificial Analysis model-page result at high effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-high-scicode",
    "model_slug": "claude-haiku-5-5",
    "category": "coding",
    "benchmark_name": "SciCode",
    "benchmark_version": null,
    "score_numeric": 48.7268518518519,
    "score_display": "48.7% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "high",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-high",
    "notes": "Independent Artificial Analysis model-page result at high effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data. Artificial Analysis marks this evaluation under review."
  },
  {
    "id": "tq-20261008-haiku55-aa-high-hle",
    "model_slug": "claude-haiku-5-5",
    "category": "knowledge",
    "benchmark_name": "Humanity's Last Exam",
    "benchmark_version": null,
    "score_numeric": 37.25671918443,
    "score_display": "37.3% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "high",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-high",
    "notes": "Independent Artificial Analysis model-page result at high effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-high-gdppdf",
    "model_slug": "claude-haiku-5-5",
    "category": "professional",
    "benchmark_name": "GDP.pdf",
    "benchmark_version": null,
    "score_numeric": 17.2,
    "score_display": "17.2% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "high",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-high",
    "notes": "Independent Artificial Analysis model-page result at high effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-high-critpt",
    "model_slug": "claude-haiku-5-5",
    "category": "math_reasoning",
    "benchmark_name": "CritPt",
    "benchmark_version": null,
    "score_numeric": 18.5714285714286,
    "score_display": "18.6% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "high",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-high",
    "notes": "Independent Artificial Analysis model-page result at high effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data. Artificial Analysis marks this evaluation under review."
  },
  {
    "id": "tq-20261008-haiku55-aa-high-omniscience-index",
    "model_slug": "claude-haiku-5-5",
    "category": "knowledge",
    "benchmark_name": "AA-Omniscience Index",
    "benchmark_version": null,
    "score_numeric": 5.75,
    "score_display": "5.8 points (AA)",
    "score_unit": "points",
    "tools": null,
    "reasoning_effort": "high",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-high",
    "notes": "Independent Artificial Analysis model-page result at high effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data. Knowledge reliability index on a -100 to 100 scale, not a percentage or hallucination rate."
  },
  {
    "id": "tq-20261008-haiku55-aa-high-omniscience-accuracy",
    "model_slug": "claude-haiku-5-5",
    "category": "knowledge",
    "benchmark_name": "AA-Omniscience Accuracy",
    "benchmark_version": null,
    "score_numeric": 34.78333333333333,
    "score_display": "34.8% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "high",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-high",
    "notes": "Independent Artificial Analysis model-page result at high effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-high-omniscience-hallucination",
    "model_slug": "claude-haiku-5-5",
    "category": "knowledge",
    "benchmark_name": "AA-Omniscience Hallucination Rate",
    "benchmark_version": null,
    "score_numeric": 44.518272425249165,
    "score_display": "44.5% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "high",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-high",
    "notes": "Independent Artificial Analysis model-page result at high effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data. Lower is better. This is hallucination rate, not accuracy or the -100 to 100 Omniscience Index."
  },
  {
    "id": "tq-20261008-haiku55-aa-high-lcr",
    "model_slug": "claude-haiku-5-5",
    "category": "other",
    "benchmark_name": "AA-LCR",
    "benchmark_version": "v1.1",
    "score_numeric": 0.773333333333333,
    "score_display": "0.773 (AA)",
    "score_unit": "score",
    "tools": null,
    "reasoning_effort": "high",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-high",
    "notes": "Independent Artificial Analysis model-page result at high effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data. Stored on its original 0 to 1 scale to match the existing AA-LCR catalog rows."
  },
  {
    "id": "tq-20261008-haiku55-aa-high-harvey",
    "model_slug": "claude-haiku-5-5",
    "category": "professional",
    "benchmark_name": "Harvey LAB-AA",
    "benchmark_version": null,
    "score_numeric": 89.5209147488783,
    "score_display": "89.5% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "high",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-high",
    "notes": "Independent Artificial Analysis model-page result at high effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data. Criterion pass rate for legal agentic work."
  },
  {
    "id": "tq-20261008-haiku55-aa-high-terminal-science",
    "model_slug": "claude-haiku-5-5",
    "category": "coding",
    "benchmark_name": "Terminal-Bench Science 0.1",
    "benchmark_version": null,
    "score_numeric": 10.0,
    "score_display": "10.0% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "high",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-high",
    "notes": "Independent Artificial Analysis model-page result at high effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-xhigh-briefcase",
    "model_slug": "claude-haiku-5-5",
    "category": "agentic_computer_use",
    "benchmark_name": "AA-Briefcase",
    "benchmark_version": "v1.1",
    "score_numeric": 1532.67,
    "score_display": "1532.67 Elo (AA)",
    "score_unit": "Elo",
    "tools": null,
    "reasoning_effort": "xhigh",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-xhigh",
    "notes": "Independent Artificial Analysis model-page result at xhigh effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-xhigh-gdpval",
    "model_slug": "claude-haiku-5-5",
    "category": "agentic_computer_use",
    "benchmark_name": "GDPval-AA",
    "benchmark_version": "v2.1",
    "score_numeric": 1510.76,
    "score_display": "1510.76 Elo (AA)",
    "score_unit": "Elo",
    "tools": null,
    "reasoning_effort": "xhigh",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-xhigh",
    "notes": "Independent Artificial Analysis model-page result at xhigh effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-xhigh-automation",
    "model_slug": "claude-haiku-5-5",
    "category": "agentic_computer_use",
    "benchmark_name": "AutomationBench-AA",
    "benchmark_version": null,
    "score_numeric": 35.953889773428195,
    "score_display": "36.0% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "xhigh",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-xhigh",
    "notes": "Independent Artificial Analysis model-page result at xhigh effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-xhigh-terminal40",
    "model_slug": "claude-haiku-5-5",
    "category": "coding",
    "benchmark_name": "Terminal-Bench 4.0",
    "benchmark_version": null,
    "score_numeric": 29.292929292929298,
    "score_display": "29.3% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "xhigh",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-xhigh",
    "notes": "Independent Artificial Analysis model-page result at xhigh effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-xhigh-scicode",
    "model_slug": "claude-haiku-5-5",
    "category": "coding",
    "benchmark_name": "SciCode",
    "benchmark_version": null,
    "score_numeric": 51.73611111111111,
    "score_display": "51.7% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "xhigh",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-xhigh",
    "notes": "Independent Artificial Analysis model-page result at xhigh effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data. Artificial Analysis marks this evaluation under review."
  },
  {
    "id": "tq-20261008-haiku55-aa-xhigh-hle",
    "model_slug": "claude-haiku-5-5",
    "category": "knowledge",
    "benchmark_name": "Humanity's Last Exam",
    "benchmark_version": null,
    "score_numeric": 42.678405931418,
    "score_display": "42.7% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "xhigh",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-xhigh",
    "notes": "Independent Artificial Analysis model-page result at xhigh effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-xhigh-gdppdf",
    "model_slug": "claude-haiku-5-5",
    "category": "professional",
    "benchmark_name": "GDP.pdf",
    "benchmark_version": null,
    "score_numeric": 18.2,
    "score_display": "18.2% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "xhigh",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-xhigh",
    "notes": "Independent Artificial Analysis model-page result at xhigh effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-xhigh-critpt",
    "model_slug": "claude-haiku-5-5",
    "category": "math_reasoning",
    "benchmark_name": "CritPt",
    "benchmark_version": null,
    "score_numeric": 22.5714285714286,
    "score_display": "22.6% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "xhigh",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-xhigh",
    "notes": "Independent Artificial Analysis model-page result at xhigh effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data. Artificial Analysis marks this evaluation under review."
  },
  {
    "id": "tq-20261008-haiku55-aa-xhigh-omniscience-index",
    "model_slug": "claude-haiku-5-5",
    "category": "knowledge",
    "benchmark_name": "AA-Omniscience Index",
    "benchmark_version": null,
    "score_numeric": 6.05,
    "score_display": "6.0 points (AA)",
    "score_unit": "points",
    "tools": null,
    "reasoning_effort": "xhigh",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-xhigh",
    "notes": "Independent Artificial Analysis model-page result at xhigh effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data. Knowledge reliability index on a -100 to 100 scale, not a percentage or hallucination rate."
  },
  {
    "id": "tq-20261008-haiku55-aa-xhigh-omniscience-accuracy",
    "model_slug": "claude-haiku-5-5",
    "category": "knowledge",
    "benchmark_name": "AA-Omniscience Accuracy",
    "benchmark_version": null,
    "score_numeric": 34.949999999999996,
    "score_display": "34.9% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "xhigh",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-xhigh",
    "notes": "Independent Artificial Analysis model-page result at xhigh effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-xhigh-omniscience-hallucination",
    "model_slug": "claude-haiku-5-5",
    "category": "knowledge",
    "benchmark_name": "AA-Omniscience Hallucination Rate",
    "benchmark_version": null,
    "score_numeric": 44.427363566487315,
    "score_display": "44.4% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "xhigh",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-xhigh",
    "notes": "Independent Artificial Analysis model-page result at xhigh effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data. Lower is better. This is hallucination rate, not accuracy or the -100 to 100 Omniscience Index."
  },
  {
    "id": "tq-20261008-haiku55-aa-xhigh-lcr",
    "model_slug": "claude-haiku-5-5",
    "category": "other",
    "benchmark_name": "AA-LCR",
    "benchmark_version": "v1.1",
    "score_numeric": 0.783333333333333,
    "score_display": "0.783 (AA)",
    "score_unit": "score",
    "tools": null,
    "reasoning_effort": "xhigh",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-xhigh",
    "notes": "Independent Artificial Analysis model-page result at xhigh effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data. Stored on its original 0 to 1 scale to match the existing AA-LCR catalog rows."
  },
  {
    "id": "tq-20261008-haiku55-aa-xhigh-harvey",
    "model_slug": "claude-haiku-5-5",
    "category": "professional",
    "benchmark_name": "Harvey LAB-AA",
    "benchmark_version": null,
    "score_numeric": 89.8972354899407,
    "score_display": "89.9% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "xhigh",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-xhigh",
    "notes": "Independent Artificial Analysis model-page result at xhigh effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data. Criterion pass rate for legal agentic work."
  },
  {
    "id": "tq-20261008-haiku55-aa-xhigh-terminal-science",
    "model_slug": "claude-haiku-5-5",
    "category": "coding",
    "benchmark_name": "Terminal-Bench Science 0.1",
    "benchmark_version": null,
    "score_numeric": 18.095238095238102,
    "score_display": "18.1% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "xhigh",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5-xhigh",
    "notes": "Independent Artificial Analysis model-page result at xhigh effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-max-briefcase",
    "model_slug": "claude-haiku-5-5",
    "category": "agentic_computer_use",
    "benchmark_name": "AA-Briefcase",
    "benchmark_version": "v1.1",
    "score_numeric": 1577.72,
    "score_display": "1577.72 Elo (AA)",
    "score_unit": "Elo",
    "tools": null,
    "reasoning_effort": "max",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5",
    "notes": "Independent Artificial Analysis model-page result at max effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-max-gdpval",
    "model_slug": "claude-haiku-5-5",
    "category": "agentic_computer_use",
    "benchmark_name": "GDPval-AA",
    "benchmark_version": "v2.1",
    "score_numeric": 1620.05,
    "score_display": "1620.05 Elo (AA)",
    "score_unit": "Elo",
    "tools": null,
    "reasoning_effort": "max",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5",
    "notes": "Independent Artificial Analysis model-page result at max effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-max-automation",
    "model_slug": "claude-haiku-5-5",
    "category": "agentic_computer_use",
    "benchmark_name": "AutomationBench-AA",
    "benchmark_version": null,
    "score_numeric": 35.411015132783625,
    "score_display": "35.4% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "max",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5",
    "notes": "Independent Artificial Analysis model-page result at max effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-max-terminal40",
    "model_slug": "claude-haiku-5-5",
    "category": "coding",
    "benchmark_name": "Terminal-Bench 4.0",
    "benchmark_version": null,
    "score_numeric": 32.8282828282828,
    "score_display": "32.8% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "max",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5",
    "notes": "Independent Artificial Analysis model-page result at max effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-max-scicode",
    "model_slug": "claude-haiku-5-5",
    "category": "coding",
    "benchmark_name": "SciCode",
    "benchmark_version": null,
    "score_numeric": 54.976851851851805,
    "score_display": "55.0% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "max",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5",
    "notes": "Independent Artificial Analysis model-page result at max effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data. Artificial Analysis marks this evaluation under review."
  },
  {
    "id": "tq-20261008-haiku55-aa-max-hle",
    "model_slug": "claude-haiku-5-5",
    "category": "knowledge",
    "benchmark_name": "Humanity's Last Exam",
    "benchmark_version": null,
    "score_numeric": 44.3929564411492,
    "score_display": "44.4% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "max",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5",
    "notes": "Independent Artificial Analysis model-page result at max effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-max-gdppdf",
    "model_slug": "claude-haiku-5-5",
    "category": "professional",
    "benchmark_name": "GDP.pdf",
    "benchmark_version": null,
    "score_numeric": 20.8,
    "score_display": "20.8% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "max",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5",
    "notes": "Independent Artificial Analysis model-page result at max effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-max-critpt",
    "model_slug": "claude-haiku-5-5",
    "category": "math_reasoning",
    "benchmark_name": "CritPt",
    "benchmark_version": null,
    "score_numeric": 18.8571428571429,
    "score_display": "18.9% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "max",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5",
    "notes": "Independent Artificial Analysis model-page result at max effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data. Artificial Analysis marks this evaluation under review."
  },
  {
    "id": "tq-20261008-haiku55-aa-max-omniscience-index",
    "model_slug": "claude-haiku-5-5",
    "category": "knowledge",
    "benchmark_name": "AA-Omniscience Index",
    "benchmark_version": null,
    "score_numeric": 10.666666666666666,
    "score_display": "10.7 points (AA)",
    "score_unit": "points",
    "tools": null,
    "reasoning_effort": "max",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5",
    "notes": "Independent Artificial Analysis model-page result at max effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data. Knowledge reliability index on a -100 to 100 scale, not a percentage or hallucination rate."
  },
  {
    "id": "tq-20261008-haiku55-aa-max-omniscience-accuracy",
    "model_slug": "claude-haiku-5-5",
    "category": "knowledge",
    "benchmark_name": "AA-Omniscience Accuracy",
    "benchmark_version": null,
    "score_numeric": 36.38333333333333,
    "score_display": "36.4% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "max",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5",
    "notes": "Independent Artificial Analysis model-page result at max effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-aa-max-omniscience-hallucination",
    "model_slug": "claude-haiku-5-5",
    "category": "knowledge",
    "benchmark_name": "AA-Omniscience Hallucination Rate",
    "benchmark_version": null,
    "score_numeric": 40.4244170814776,
    "score_display": "40.4% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "max",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5",
    "notes": "Independent Artificial Analysis model-page result at max effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data. Lower is better. This is hallucination rate, not accuracy or the -100 to 100 Omniscience Index."
  },
  {
    "id": "tq-20261008-haiku55-aa-max-lcr",
    "model_slug": "claude-haiku-5-5",
    "category": "other",
    "benchmark_name": "AA-LCR",
    "benchmark_version": "v1.1",
    "score_numeric": 0.826666666666667,
    "score_display": "0.827 (AA)",
    "score_unit": "score",
    "tools": null,
    "reasoning_effort": "max",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5",
    "notes": "Independent Artificial Analysis model-page result at max effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data. Stored on its original 0 to 1 scale to match the existing AA-LCR catalog rows."
  },
  {
    "id": "tq-20261008-haiku55-aa-max-harvey",
    "model_slug": "claude-haiku-5-5",
    "category": "professional",
    "benchmark_name": "Harvey LAB-AA",
    "benchmark_version": null,
    "score_numeric": 89.8682877406282,
    "score_display": "89.9% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "max",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5",
    "notes": "Independent Artificial Analysis model-page result at max effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data. Criterion pass rate for legal agentic work."
  },
  {
    "id": "tq-20261008-haiku55-aa-max-terminal-science",
    "model_slug": "claude-haiku-5-5",
    "category": "coding",
    "benchmark_name": "Terminal-Bench Science 0.1",
    "benchmark_version": null,
    "score_numeric": 20.0,
    "score_display": "20.0% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": "max",
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/claude-haiku-5-5",
    "notes": "Independent Artificial Analysis model-page result at max effort, observed October 8, 2026. Exact evaluation date is not published. Tool use is not stated in the model-page data."
  },
  {
    "id": "tq-20261008-haiku55-anthropic-osworld21",
    "model_slug": "claude-haiku-5-5",
    "category": "agentic_computer_use",
    "benchmark_name": "OSWorld 2.1",
    "benchmark_version": "offline subset",
    "score_numeric": 72.4,
    "score_display": "72.4% (Anthropic)",
    "score_unit": "percent",
    "tools": true,
    "reasoning_effort": null,
    "harness": null,
    "evaluator": "Anthropic",
    "evaluation_date": null,
    "source": "https://www.anthropic.com/claude-haiku-5-5",
    "notes": "Anthropic-reported October 7, 2026 launch score. Effort and exact evaluation date are not specified. Competitor columns are not seeded from this table. OSWorld is explicitly the offline subset, not the older partial-credit run."
  },
  {
    "id": "tq-20261008-haiku55-anthropic-hle-notools",
    "model_slug": "claude-haiku-5-5",
    "category": "knowledge",
    "benchmark_name": "Humanity's Last Exam",
    "benchmark_version": null,
    "score_numeric": 45.9,
    "score_display": "45.9% (Anthropic)",
    "score_unit": "percent",
    "tools": false,
    "reasoning_effort": null,
    "harness": null,
    "evaluator": "Anthropic",
    "evaluation_date": null,
    "source": "https://www.anthropic.com/claude-haiku-5-5",
    "notes": "Anthropic-reported October 7, 2026 launch score. Effort and exact evaluation date are not specified. Competitor columns are not seeded from this table."
  },
  {
    "id": "tq-20261008-haiku55-anthropic-hle-tools",
    "model_slug": "claude-haiku-5-5",
    "category": "knowledge",
    "benchmark_name": "Humanity's Last Exam",
    "benchmark_version": null,
    "score_numeric": 57.4,
    "score_display": "57.4% (Anthropic)",
    "score_unit": "percent",
    "tools": true,
    "reasoning_effort": null,
    "harness": null,
    "evaluator": "Anthropic",
    "evaluation_date": null,
    "source": "https://www.anthropic.com/claude-haiku-5-5",
    "notes": "Anthropic-reported October 7, 2026 launch score. Effort and exact evaluation date are not specified. Competitor columns are not seeded from this table."
  },
  {
    "id": "tq-20261008-haiku55-anthropic-terminal40",
    "model_slug": "claude-haiku-5-5",
    "category": "coding",
    "benchmark_name": "Terminal-Bench 4.0",
    "benchmark_version": null,
    "score_numeric": 39.2,
    "score_display": "39.2% (Anthropic)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": null,
    "harness": null,
    "evaluator": "Anthropic",
    "evaluation_date": null,
    "source": "https://www.anthropic.com/claude-haiku-5-5",
    "notes": "Anthropic-reported October 7, 2026 launch score. Effort and exact evaluation date are not specified. Competitor columns are not seeded from this table."
  },
  {
    "id": "tq-20261008-haiku55-anthropic-frontiercode",
    "model_slug": "claude-haiku-5-5",
    "category": "coding",
    "benchmark_name": "FrontierCode 1.1 Main",
    "benchmark_version": null,
    "score_numeric": 46.4,
    "score_display": "46.4% (Anthropic)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": null,
    "harness": null,
    "evaluator": "Anthropic",
    "evaluation_date": null,
    "source": "https://www.anthropic.com/claude-haiku-5-5",
    "notes": "Anthropic-reported October 7, 2026 launch score. Effort and exact evaluation date are not specified. Competitor columns are not seeded from this table."
  },
  {
    "id": "tq-20261008-haiku55-anthropic-chartography",
    "model_slug": "claude-haiku-5-5",
    "category": "multimodal",
    "benchmark_name": "Chartography",
    "benchmark_version": null,
    "score_numeric": 46.4,
    "score_display": "46.4% (Anthropic)",
    "score_unit": "percent",
    "tools": false,
    "reasoning_effort": null,
    "harness": null,
    "evaluator": "Anthropic",
    "evaluation_date": null,
    "source": "https://www.anthropic.com/claude-haiku-5-5",
    "notes": "Anthropic-reported October 7, 2026 launch score. Effort and exact evaluation date are not specified. Competitor columns are not seeded from this table."
  }
]
$benchmarks$::jsonb) AS evidence(
  id TEXT, model_slug TEXT, category TEXT, benchmark_name TEXT,
  benchmark_version TEXT, score_numeric DOUBLE PRECISION, score_display TEXT,
  score_unit TEXT, tools BOOLEAN, reasoning_effort TEXT, harness TEXT,
  evaluator TEXT, evaluation_date TEXT, source TEXT, notes TEXT
)
ON CONFLICT (id) DO UPDATE SET
  model_slug = EXCLUDED.model_slug,
  category = EXCLUDED.category,
  benchmark_name = EXCLUDED.benchmark_name,
  benchmark_version = EXCLUDED.benchmark_version,
  score_numeric = EXCLUDED.score_numeric,
  score_display = EXCLUDED.score_display,
  score_unit = EXCLUDED.score_unit,
  tools = EXCLUDED.tools,
  reasoning_effort = EXCLUDED.reasoning_effort,
  harness = EXCLUDED.harness,
  evaluator = EXCLUDED.evaluator,
  evaluation_date = EXCLUDED.evaluation_date,
  source = EXCLUDED.source,
  notes = EXCLUDED.notes,
  updated_at = NOW();

-- The same launch halves Sonnet 5.5 cache reads. Preserve every other field.
UPDATE models
SET
  comparison_data = jsonb_set(comparison_data, '{Cached input / 1M}', '"$0.10"'::jsonb),
  sources = CASE
    WHEN sources @> '[{"url":"https://www.anthropic.com/claude-haiku-5-5"}]'::jsonb THEN sources
    ELSE sources || '[{"title":"Haiku 5.5 launch: Sonnet 5.5 cache-read price cut","url":"https://www.anthropic.com/claude-haiku-5-5"}]'::jsonb
  END,
  verified_at = NOW(),
  updated_at = NOW()
WHERE slug = 'claude-sonnet-5-5';
