-- Publish Mistral Large 4's model card and current hosted-preview catalog.
-- Weights and the final license are planned, not currently downloadable.
-- Official and independently evaluated specifications differ, and both are
-- recorded. Composite indexes stay in metadata rather than benchmark rows.
INSERT INTO content_items (
  id, kind, slug, parent_slug, path, title, summary, body, blocks, sources, metadata,
  cover_image_url, cover_image_alt, status, published_at, sort_order, updated_at
)
SELECT
  entry.id, 'glossary', entry.slug, '', 'glossary/' || entry.slug,
  entry.title, entry.summary, entry.body,
  jsonb_build_array(jsonb_build_object('id', 'markdown-1', 'type', 'markdown', 'content', entry.body)),
  entry.sources, entry.metadata, NULL, NULL, 'published', DATE '2026-10-08', 0,
  TIMESTAMPTZ '2026-10-08 00:00:00+00'
FROM jsonb_to_recordset($glossary$
[
  {
    "id": "glossary:mistral-large-4",
    "slug": "mistral-large-4",
    "title": "Mistral Large 4",
    "summary": "Mistral AI's October 2026 public research preview for reasoning, coding and multimodal agents, with 1M context in current docs, $0.68/$2.09 launch pricing and downloadable weights planned for late October.",
    "body": "Mistral Large 4 is Mistral AI's October 2026 [large language model](/glossary/large-language-model) for reasoning, coding, document understanding and agentic work. Released on October 6, 2026, it is available through a public research-preview API under `mistral-large-4`. Mistral plans to release downloadable weights by the end of October. As of October 8, the usable product is the hosted preview; the promised weights and their final license are not established by the sources reviewed here.\n\nThe launch combines a larger multimodal architecture with a substantial investment in European training infrastructure. Mistral says it trained the model from scratch on 3,800 NVIDIA Grace Blackwell GPUs in its own European datacenters, which also serve the preview. Artificial Analysis independently scores the evaluated preview at 38.38 on its Intelligence Index and 50 on its Cyber Index. Those are different composite indexes, not interchangeable percentages or a claim that the model wins every task.\n\n## Core profile\n\nMistral's current model documentation describes a granular [mixture-of-experts](/glossary/mixture-of-experts) architecture with 1.05 trillion total parameters, 52 billion active parameters and a 1.6-billion-parameter vision encoder. The launch announcement rounds the total to one trillion and also gives 52 billion active. A mixture-of-experts model resembles a workshop with many specialist teams: a router sends each piece of work to a subset of the teams. Total parameters describe the whole workshop; active parameters describe the part working on a particular token.\n\nThe official model page lists a 1M-token [context window](/glossary/context-window). Artificial Analysis's evaluated preview profile instead lists 524,288 tokens, one trillion total parameters and 49 billion active parameters. These sources disagree, and they do not explain the discrepancy. This entry uses the current official specification for the model's API profile and keeps AA's numbers attached to its evaluated preview. A context window is a working desk: it sets how much material the model can keep in front of it during a request.\n\nThe model accepts text and image input and produces text. AA does not list native audio or video input, or image, audio or video output. Mistral's documentation advertises document Q&A, function calling, structured outputs, agents, conversations and batching. Vals lists a 256K output limit, while the official model page reviewed here does not state that limit. A reliable knowledge-cutoff date is also not published in these sources. The documentation's 1M context figure should therefore not be read as a confirmed 1M output allowance.\n\n## Benchmark profile\n\nThe table distinguishes Mistral's launch claims from independent results reported by Artificial Analysis and Vals. Values were reviewed on October 8, 2026. Matching benchmark names alone do not establish matching checkpoints, prompts, tool settings or evaluation harnesses.\n\n| Evaluation | Reported result | Source and conditions |\n| --- | ---: | --- |\n| DeepSWE v1.1 | 61.7% | Mistral launch report |\n| SWE-Atlas Codebase QnA | 59.4% | Mistral launch report |\n| Terminal-Bench 4.0 | 28.3% | Mistral launch report |\n| Terminal-Bench 4.0 | 26.8% | Artificial Analysis evaluated preview |\n| Terminal-Bench 4.0 | 22.73% | Vals model profile |\n| AutomationBench-AA | 59.9% | Artificial Analysis |\n| GDPval-AA v2.1 | 1423.91 Elo | Artificial Analysis |\n| AA-Briefcase v1.1 | 1392.53 Elo | Artificial Analysis |\n| GDP.pdf | 18.6% | Artificial Analysis, all-pass metric |\n| SciCode | 54.2% | Artificial Analysis, evaluation marked under review |\n| CritPt | 10.6% | Artificial Analysis, evaluation marked under review |\n| Humanity's Last Exam | 35.0% | Artificial Analysis |\n| MMMU-Pro | 76.4% | Artificial Analysis |\n| AA-Omniscience accuracy | 25.8% | Artificial Analysis |\n| AA-Omniscience hallucination rate | 41.9% | Artificial Analysis, lower is better |\n| Vals Finance Agent v2 | 54.68% | Vals |\n| Harvey's Legal Agent Benchmark | 15.83% | Vals, held-out task pass rate |\n| CyberGym-E2E-AA | 82% | Artificial Analysis launch analysis |\n| Cybench | 93% | Mistral launch report |\n\nThe three Terminal-Bench readings are preserved rather than averaged or treated as the same run. Mistral's headline is the highest, while the two independent profiles report lower values. AA's long-context reasoning result is 0.813 on AA-LCR v1.1. Its Omniscience Index is -5.3 on a scale from -100 to 100. That index measures knowledge reliability and is separate from both accuracy and hallucination rate, so the three Omniscience readings should not be substituted for one another.\n\nA composite index works like an exam average across several subjects. AA's Intelligence Index is 38.38 for this preview, while Vals reports 48.05% on its own Vals Index. The indexes use different constituent evaluations and scoring rules. Vals' legal result is also a task pass rate: a task must satisfy the benchmark's completion criteria. It is not the same measurement as the criterion pass rate used in AA's Harvey LAB-AA implementation. AA does not publish a Harvey LAB-AA result for this model in its profile, and this entry does not fill that gap with the Vals number.\n\n## Pricing and efficiency\n\nThe official documentation lists standard pricing of $1.36 per million input tokens, $0.14 per million cached input tokens and $4.18 per million output tokens. It also shows launch prices at half those rates. AA's October 6 analysis describes the discount as lasting for the first two weeks. These are promotional rates with a stated duration, not a permanent reduction in the standard price.\n\n| Token type | Launch price per million | Standard price per million |\n| --- | ---: | ---: |\n| Input | $0.68 | $1.36 |\n| Cached input | $0.07 | $0.14 |\n| Output | $2.09 | $4.18 |\n\nA prompt cache resembles a kitchen preparing a sauce base once and reusing it across orders. Repeated input can become cheaper when it qualifies for the cached rate. AA's cost breakdown uses a cache-write rate of $1.36 per million tokens, but the official pricing summary reviewed here does not separately list a cache-write price. The exact treatment of cache writes and the launch offer should be checked before estimating a production workload.\n\nAA measures 116.1 output tokens per second on Mistral's API. Its public data separates roughly 1.46 seconds to the first response chunk from 18.69 seconds to the first answer token, including reasoning. That distinction matters for a reasoning model: a stream can begin before the user receives the answer. AA's weighted Intelligence Index cost is about $1.13 per task at standard pricing and about $0.57 under the launch discount. Those costs describe AA's evaluation mix, not every customer's task.\n\n## Safeguards\n\nMistral says the public model refuses malicious cyber requests more often than the open-model competitors in its comparison. It also reports 93.3% attack resistance on Lakera's B3 benchmark and a KORA score of 1.691, against a maximum of 2. These are vendor-reported safety results. A [prompt injection](/glossary/prompt-injection) is like an instruction hidden inside a file an assistant was only supposed to read; resistance to that attack does not establish reliability on every other kind of misuse or error.\n\nThe release also describes a separate red-teaming phase with cybersecurity leaders, vetted partners and state authorities. Those participants can access reduced moderation and expanded cyber capabilities before the weights ship. That is a distinct access arrangement from the public API, and the public preview's safeguards should not be assumed to describe every partner deployment.\n\nCyber capability and cyber refusal are different measurements. The 82% CyberGym-E2E-AA result concerns reproducing and patching real vulnerabilities, while the refusal evaluations concern whether the model complies with malicious requests. Mistral's announcement makes a case for defenders being able to run the model under their own policies after the weights become available. It does not make downloadable weights available during the preview or publish a final license in the materials reviewed here.\n\n## API and behavior changes\n\nThe documented API name is `mistral-large-4`. Official examples use `reasoning_effort=\"high\"`, and AA identifies the evaluated preview as a reasoning model. The full supported effort range and default are not established by these sources, so the catalog does not invent a max-effort label for the independent scores. Reasoning effort is like the time allowed for a difficult homework problem: more working time can change the quality, latency and cost of the answer.\n\nMistral lists chat completions, function calling, structured outputs, document Q&A, batching, agents and conversations as supported features. Function calling resembles an assistant completing a work order for another system to execute. Structured output resembles a form with fixed fields, which helps a program consume the answer consistently. These features describe the API interface; they do not guarantee that a selected tool, extracted figure or generated legal conclusion is correct.\n\nThe preview is still changing. Mistral says its reinforcement-learning run remains in progress and that further architecture and post-training details will accompany the weights. [Reinforcement learning](/glossary/reinforcement-learning) resembles repeated practice with a coach who scores the outcome. Mistral combines code sandboxes, web search, external APIs, reward models, unit tests and other checks in that training. Developers should record the request date, model name and reasoning settings when comparing preview results.\n\n## Applications and workflow fit\n\nLarge 4 is positioned for coding agents, document-heavy professional work, visual inspection and cyber defense. Its image input can support diagrams, charts and engineering drawings, while document Q&A can help retrieve evidence from PDFs. A vision encoder acts like a translator turning the contents of an image into material the language model can reason about. AA reports that the API can accept 100 images per request, compared with eight for previous Mistral models.\n\nThe independent results suggest evaluating specific workloads instead of relying on a single overall score. Vals' 54.68% Finance Agent v2 result and 15.83% legal task pass rate offer different tests of enterprise work. AA's 18.6% all-pass result on GDP.pdf measures a stricter document task outcome than ordinary extraction demos. Mistral's demos and internal human evaluations are useful descriptions of intended workflows, but they do not replace an evaluation using the customer's own documents, permissions and acceptance criteria.\n\nOrganizations seeking European-operated infrastructure can use the hosted preview, which Mistral says is served in its own European datacenters. Organizations requiring self-hosting must wait for the announced weight release and review the actual license and deployment requirements when published. The size of the model, including its much smaller active-parameter count, does not by itself establish a tested hardware configuration or inference cost for a private deployment.\n\n## Bottom line\n\nMistral Large 4 brings a larger multimodal MoE architecture, a public reasoning API and independent evidence of useful coding, document and cyber capabilities. Its preview benchmark results, introductory prices and promised weight release are three separate facts. The current official specification also differs from the evaluated metadata that AA publishes, so that disagreement remains visible here.\n\nThe API is available. The weights have a release target.",
    "sources": [
      {
        "title": "Introducing Mistral Large 4",
        "url": "https://mistral.ai/news/mistral-large-4/"
      },
      {
        "title": "Mistral Large 4 official model documentation",
        "url": "https://docs.mistral.ai/models/mistral-large-4-0"
      },
      {
        "title": "Artificial Analysis: Mistral Large 4 Preview",
        "url": "https://artificialanalysis.ai/models/mistral-large-4"
      },
      {
        "title": "Artificial Analysis: Mistral Large 4 release analysis",
        "url": "https://artificialanalysis.ai/articles/mistral-large-4-france-ai"
      },
      {
        "title": "Vals: Mistral Large 4 benchmarks",
        "url": "https://www.vals.ai/models/mistralai_mistral-large-4"
      },
      {
        "title": "Vals: Harvey's Legal Agent Benchmark methodology",
        "url": "https://www.vals.ai/benchmarks/hlab"
      }
    ],
    "metadata": {
      "category": "Models & Architectures",
      "relatedTerms": [
        "mistral-medium-3",
        "mixture-of-experts",
        "large-language-model",
        "context-window",
        "reinforcement-learning",
        "prompt-injection",
        "gpt-6-luna"
      ],
      "seoDescription": "Mistral Large 4 model card: public preview, 1M context in current docs, planned open weights, launch pricing, and AA and Vals benchmark results.",
      "seoKeywords": [
        "Mistral Large 4 model card",
        "Mistral Large 4 specs",
        "Mistral Large 4 benchmarks",
        "Mistral Large 4 pricing",
        "Mistral Large 4 weights",
        "Mistral Large 4 preview",
        "mistral-large-4"
      ]
    }
  }
]
$glossary$::jsonb) AS entry(
  id TEXT, slug TEXT, title TEXT, summary TEXT, body TEXT, sources JSONB, metadata JSONB
)
ON CONFLICT (kind, slug, parent_slug) DO UPDATE SET
  path = EXCLUDED.path, title = EXCLUDED.title, summary = EXCLUDED.summary,
  body = EXCLUDED.body, blocks = EXCLUDED.blocks, sources = EXCLUDED.sources,
  metadata = EXCLUDED.metadata, status = EXCLUDED.status,
  published_at = EXCLUDED.published_at, updated_at = EXCLUDED.updated_at;

INSERT INTO models (
  slug, name, developer, release_date, ga_date, access, family,
  comparison_data, sources, notes, metadata, verified_at
)
SELECT
  seed.slug, seed.name, seed.developer, seed.release_date::date,
  seed.ga_date::date, seed.access, seed.family,
  seed.comparison_data, seed.sources, seed.notes, seed.metadata, NOW()
FROM jsonb_to_recordset($models$
[
  {
    "slug": "mistral-large-4",
    "name": "Mistral Large 4",
    "developer": "Mistral AI",
    "release_date": "2026-10-06",
    "ga_date": null,
    "access": "proprietary",
    "family": "Mistral Large",
    "comparison_data": {
      "Developer": "Mistral AI",
      "Release date": "2026-10-06",
      "API model ID": "mistral-large-4",
      "Context window": "1M tokens in current official docs; AA evaluated a 512K-token preview",
      "Max output": "256K tokens reported by Vals; not stated in the official model page reviewed",
      "Knowledge cutoff": "Not published in the reviewed sources",
      "Reasoning / effort": "Reasoning supported. Official API example uses high; complete effort range and default are not specified. AA does not state its effort setting",
      "Input / 1M tokens": "$0.68 launch offer; $1.36 standard",
      "Cached input / 1M": "$0.07 launch offer; $0.14 standard",
      "Cache write / 1M": "$1.36 standard in AA cost accounting; not separately quoted in the official model pricing summary",
      "Output / 1M tokens": "$2.09 launch offer; $4.18 standard",
      "Batch / flex discount": "Batching supported. Launch discount applies for the first two weeks; stacking with other discounts is not established here",
      "Long-context surcharge": "Not specified in the reviewed sources",
      "Text input": "Yes",
      "Image / vision input": "Yes; AA reports up to 100 images per request",
      "Audio input": "No native audio input listed by AA",
      "Video input": "No native video input listed by AA",
      "File / document input": "Document Q&A integration in the official API documentation",
      "Text output": "Yes",
      "Image output": "No",
      "Audio output": "No",
      "Video output": "No",
      "Tool / function calling": "Yes; function calling, structured outputs, agents and conversations",
      "Computer use": "Through external agent/tool integrations; no native computer-use benchmark result verified",
      "API access": "Public research preview through Mistral Studio/API; also listed on OpenRouter",
      "Product access": "Mistral Studio playground, hosted API, agents and conversations",
      "Weights / license": "Hosted preview as of October 8, 2026. Downloadable weights planned for late October; final weight license not specified",
      "Primary focus": "Reasoning, coding, multimodal document work, visual inspection, finance, legal workflows and cyber defense",
      "Long-horizon work": "Granular MoE with 1.05T total, 52B active and a 1.6B vision encoder in current docs. AA evaluated metadata instead reports 1T total, 49B active and 512K context",
      "Agent orchestration": "Function calling and built-in tools through the Agents and Conversations APIs; structured outputs for programmatic workflows",
      "Efficiency / generation change": "AA Intelligence Index 38.38; Cyber Index 50. Standard index-task cost $1.13, about $0.57 during the launch offer. AA measured 116.1 output tokens/s, 1.46s to first chunk and 18.69s to first answer including reasoning",
      "Safety / approvals": "Mistral reports 93.3% B3 attack resistance and KORA 1.691/2. The public preview has cyber refusals; vetted partners receive reduced moderation and expanded cyber capabilities for red-teaming before the weight release"
    },
    "sources": [
      {
        "title": "Introducing Mistral Large 4",
        "url": "https://mistral.ai/news/mistral-large-4/"
      },
      {
        "title": "Mistral Large 4 official model documentation",
        "url": "https://docs.mistral.ai/models/mistral-large-4-0"
      },
      {
        "title": "Artificial Analysis: Mistral Large 4 Preview",
        "url": "https://artificialanalysis.ai/models/mistral-large-4"
      },
      {
        "title": "Artificial Analysis: Mistral Large 4 release analysis",
        "url": "https://artificialanalysis.ai/articles/mistral-large-4-france-ai"
      },
      {
        "title": "Vals: Mistral Large 4 benchmarks",
        "url": "https://www.vals.ai/models/mistralai_mistral-large-4"
      },
      {
        "title": "Vals: Harvey's Legal Agent Benchmark methodology",
        "url": "https://www.vals.ai/benchmarks/hlab"
      },
      {
        "title": "OpenRouter: Mistral Large 4 listing",
        "url": "https://openrouter.ai/mistralai/mistral-large-4-0"
      }
    ],
    "notes": "Public research preview released October 6, 2026. Current official docs list 1.05T total parameters, 52B active, a 1.6B vision encoder and 1M context; AA's evaluated preview instead lists 1T total, 49B active and 524,288 context tokens. This discrepancy is preserved, not silently reconciled. Official docs and Vals label the model open, but Mistral's launch says weights ship at the end of October and AA marks the currently served preview proprietary, with no weight URL or license. Catalog access therefore describes what is available now. Mistral reports 28.3% on Terminal-Bench 4.0, AA 26.8%, and Vals 22.73%; all three records retain their sources and unknown effort settings. Vals' legal score is held-out task pass rate, not the AA Harvey LAB-AA criterion pass rate; AA has no Harvey LAB-AA row for this model. Composite Intelligence, Cyber, Coding Agent and Vals Index readings remain in metadata and model-behavior notes rather than being mislabeled as individual benchmarks. Launch token prices are 50% below standard for the first two weeks, and batching/promotion interactions are not established. AA's 1.46-second first-chunk latency excludes most reasoning time; time to the first answer is 18.69 seconds. SciCode and CritPt are marked under review by AA.",
    "metadata": {
      "verification_pass": "mistral-large-4-2026-10-08",
      "catalog_status": "preview",
      "launch_stage": "public_research_preview",
      "weights_available": false,
      "weights_release_plan": "End of October 2026",
      "weight_license": null,
      "official_parameters_total": 1050000000000,
      "official_parameters_active": 52000000000,
      "vision_encoder_parameters": 1600000000,
      "official_context_window_label": "1M",
      "artificial_analysis_context_window_tokens": 524288,
      "artificial_analysis_parameters_total_billions": 1000,
      "artificial_analysis_parameters_active_billions": 49,
      "specification_discrepancy": "Official documentation and the independently evaluated preview report different context and active parameter counts; no reconciliation is supplied",
      "reported_max_output_label": "256K (Vals)",
      "reasoning_supported": true,
      "documented_effort_example": "high",
      "default_effort": null,
      "independent_intelligence_index": 38.3770408917494,
      "artificial_analysis_intelligence_index_version": "v4.3.2",
      "independent_cyber_index": 50,
      "vendor_coding_agent_index": 49.8,
      "vals_index": 48.05,
      "vals_index_confidence_interval_pp": 1.11,
      "artificial_analysis_observed_at": "2026-10-08",
      "artificial_analysis_output_tokens_per_second": 116.080085205733,
      "artificial_analysis_time_to_first_chunk_seconds": 1.463365106,
      "artificial_analysis_time_to_first_answer_token_seconds": 18.692849357801908,
      "artificial_analysis_index_cost_per_task_usd": 1.1317590533008346,
      "artificial_analysis_intro_index_cost_per_task_usd": 0.5658795266504173,
      "artificial_analysis_standard_cache_write_per_million_usd": 1.36,
      "pricing_standard": {
        "input_per_million_usd": 1.36,
        "cache_read_per_million_usd": 0.14,
        "output_per_million_usd": 4.18
      },
      "pricing_intro": {
        "input_per_million_usd": 0.68,
        "cache_read_per_million_usd": 0.07,
        "output_per_million_usd": 2.09
      },
      "intro_offer_announced": "2026-10-06",
      "intro_offer_duration": "First two weeks",
      "input_modalities": "text, image",
      "output_modalities": "text",
      "training_gpus_reported": 3800,
      "training_gpu_family": "NVIDIA Grace Blackwell"
    }
  }
]
$models$::jsonb) AS seed(
  slug TEXT, name TEXT, developer TEXT, release_date TEXT, ga_date TEXT,
  access TEXT, family TEXT, comparison_data JSONB, sources JSONB, notes TEXT, metadata JSONB
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, developer = EXCLUDED.developer,
  release_date = EXCLUDED.release_date, ga_date = EXCLUDED.ga_date,
  access = EXCLUDED.access, family = EXCLUDED.family,
  comparison_data = EXCLUDED.comparison_data, sources = EXCLUDED.sources,
  notes = EXCLUDED.notes, metadata = COALESCE(models.metadata, '{}'::jsonb) || EXCLUDED.metadata,
  verified_at = NOW(), updated_at = NOW();

INSERT INTO model_benchmarks (
  id, model_slug, category, benchmark_name, benchmark_version,
  score_numeric, score_display, score_unit, tools, reasoning_effort,
  harness, evaluator, evaluation_date, source, notes
)
SELECT
  evidence.id, evidence.model_slug, evidence.category,
  evidence.benchmark_name, evidence.benchmark_version,
  evidence.score_numeric, evidence.score_display, evidence.score_unit,
  evidence.tools, evidence.reasoning_effort, evidence.harness,
  evidence.evaluator, evidence.evaluation_date::date, evidence.source, evidence.notes
FROM jsonb_to_recordset($benchmarks$
[
  {
    "id": "tq-20261008-mistral-large4-aa-briefcase",
    "model_slug": "mistral-large-4",
    "category": "agentic_computer_use",
    "benchmark_name": "AA-Briefcase",
    "benchmark_version": "v1.1",
    "score_numeric": 1392.53,
    "score_display": "1392.53 Elo (AA)",
    "score_unit": "Elo",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/mistral-large-4",
    "notes": "Direct independent Artificial Analysis model-page chart data for the evaluated preview (524,288 context tokens and 49B active parameters), whose metadata differs from the current official 1M/52B specification. Tool settings are not stated. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  },
  {
    "id": "tq-20261008-mistral-large4-aa-gdpval",
    "model_slug": "mistral-large-4",
    "category": "agentic_computer_use",
    "benchmark_name": "GDPval-AA",
    "benchmark_version": "v2.1",
    "score_numeric": 1423.91,
    "score_display": "1423.91 Elo (AA)",
    "score_unit": "Elo",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/mistral-large-4",
    "notes": "Direct independent Artificial Analysis model-page chart data for the evaluated preview (524,288 context tokens and 49B active parameters), whose metadata differs from the current official 1M/52B specification. Tool settings are not stated. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  },
  {
    "id": "tq-20261008-mistral-large4-aa-automation",
    "model_slug": "mistral-large-4",
    "category": "agentic_computer_use",
    "benchmark_name": "AutomationBench-AA",
    "benchmark_version": null,
    "score_numeric": 59.90136246808686,
    "score_display": "59.9% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/mistral-large-4",
    "notes": "Direct independent Artificial Analysis model-page chart data for the evaluated preview (524,288 context tokens and 49B active parameters), whose metadata differs from the current official 1M/52B specification. Tool settings are not stated. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  },
  {
    "id": "tq-20261008-mistral-large4-aa-terminal40",
    "model_slug": "mistral-large-4",
    "category": "coding",
    "benchmark_name": "Terminal-Bench 4.0",
    "benchmark_version": null,
    "score_numeric": 26.7676767676768,
    "score_display": "26.8% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/mistral-large-4",
    "notes": "Direct independent Artificial Analysis model-page chart data for the evaluated preview (524,288 context tokens and 49B active parameters), whose metadata differs from the current official 1M/52B specification. Tool settings are not stated. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  },
  {
    "id": "tq-20261008-mistral-large4-aa-scicode",
    "model_slug": "mistral-large-4",
    "category": "coding",
    "benchmark_name": "SciCode",
    "benchmark_version": null,
    "score_numeric": 54.1666666666667,
    "score_display": "54.2% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/mistral-large-4",
    "notes": "Direct independent Artificial Analysis model-page chart data for the evaluated preview (524,288 context tokens and 49B active parameters), whose metadata differs from the current official 1M/52B specification. Tool settings are not stated. Artificial Analysis marks this evaluation under review. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  },
  {
    "id": "tq-20261008-mistral-large4-aa-critpt",
    "model_slug": "mistral-large-4",
    "category": "math_reasoning",
    "benchmark_name": "CritPt",
    "benchmark_version": null,
    "score_numeric": 10.5714285714286,
    "score_display": "10.6% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/mistral-large-4",
    "notes": "Direct independent Artificial Analysis model-page chart data for the evaluated preview (524,288 context tokens and 49B active parameters), whose metadata differs from the current official 1M/52B specification. Tool settings are not stated. Artificial Analysis marks this evaluation under review. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  },
  {
    "id": "tq-20261008-mistral-large4-aa-hle",
    "model_slug": "mistral-large-4",
    "category": "knowledge",
    "benchmark_name": "Humanity's Last Exam",
    "benchmark_version": null,
    "score_numeric": 35.032437442075995,
    "score_display": "35.0% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/mistral-large-4",
    "notes": "Direct independent Artificial Analysis model-page chart data for the evaluated preview (524,288 context tokens and 49B active parameters), whose metadata differs from the current official 1M/52B specification. Tool settings are not stated. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  },
  {
    "id": "tq-20261008-mistral-large4-aa-gdppdf",
    "model_slug": "mistral-large-4",
    "category": "professional",
    "benchmark_name": "GDP.pdf",
    "benchmark_version": null,
    "score_numeric": 18.6,
    "score_display": "18.6% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/mistral-large-4",
    "notes": "Direct independent Artificial Analysis model-page chart data for the evaluated preview (524,288 context tokens and 49B active parameters), whose metadata differs from the current official 1M/52B specification. Tool settings are not stated. All-pass metric. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  },
  {
    "id": "tq-20261008-mistral-large4-aa-omniscience-index",
    "model_slug": "mistral-large-4",
    "category": "knowledge",
    "benchmark_name": "AA-Omniscience Index",
    "benchmark_version": null,
    "score_numeric": -5.3,
    "score_display": "-5.3 points (AA)",
    "score_unit": "points",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/mistral-large-4",
    "notes": "Direct independent Artificial Analysis model-page chart data for the evaluated preview (524,288 context tokens and 49B active parameters), whose metadata differs from the current official 1M/52B specification. Tool settings are not stated. Knowledge-reliability index on a -100 to 100 scale; not a percentage. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  },
  {
    "id": "tq-20261008-mistral-large4-aa-omniscience-accuracy",
    "model_slug": "mistral-large-4",
    "category": "knowledge",
    "benchmark_name": "AA-Omniscience Accuracy",
    "benchmark_version": null,
    "score_numeric": 25.816666666666666,
    "score_display": "25.8% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/mistral-large-4",
    "notes": "Direct independent Artificial Analysis model-page chart data for the evaluated preview (524,288 context tokens and 49B active parameters), whose metadata differs from the current official 1M/52B specification. Tool settings are not stated. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  },
  {
    "id": "tq-20261008-mistral-large4-aa-omniscience-hallucination",
    "model_slug": "mistral-large-4",
    "category": "knowledge",
    "benchmark_name": "AA-Omniscience Hallucination Rate",
    "benchmark_version": null,
    "score_numeric": 41.94563019546169,
    "score_display": "41.9% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/mistral-large-4",
    "notes": "Direct independent Artificial Analysis model-page chart data for the evaluated preview (524,288 context tokens and 49B active parameters), whose metadata differs from the current official 1M/52B specification. Tool settings are not stated. Lower is better. This is hallucination rate, not accuracy or the Omniscience Index. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  },
  {
    "id": "tq-20261008-mistral-large4-aa-lcr",
    "model_slug": "mistral-large-4",
    "category": "other",
    "benchmark_name": "AA-LCR",
    "benchmark_version": "v1.1",
    "score_numeric": 0.813333333333333,
    "score_display": "0.813 (AA)",
    "score_unit": "score",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/mistral-large-4",
    "notes": "Direct independent Artificial Analysis model-page chart data for the evaluated preview (524,288 context tokens and 49B active parameters), whose metadata differs from the current official 1M/52B specification. Tool settings are not stated. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  },
  {
    "id": "tq-20261008-mistral-large4-aa-mmmupro",
    "model_slug": "mistral-large-4",
    "category": "multimodal",
    "benchmark_name": "MMMU-Pro",
    "benchmark_version": null,
    "score_numeric": 76.4161849710983,
    "score_display": "76.4% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/models/mistral-large-4",
    "notes": "Direct independent Artificial Analysis model-page chart data for the evaluated preview (524,288 context tokens and 49B active parameters), whose metadata differs from the current official 1M/52B specification. Tool settings are not stated. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  },
  {
    "id": "tq-20261008-mistral-large4-aa-cybergym-e2e",
    "model_slug": "mistral-large-4",
    "category": "coding",
    "benchmark_name": "CyberGym-E2E-AA",
    "benchmark_version": null,
    "score_numeric": 82,
    "score_display": "82.0% (AA)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Artificial Analysis",
    "evaluator": "Artificial Analysis",
    "evaluation_date": null,
    "source": "https://artificialanalysis.ai/articles/mistral-large-4-france-ai",
    "notes": "Independent result reported in AA's October 6 launch analysis. Reproducing and patching real vulnerabilities; distinct from the older CyberGym benchmark. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  },
  {
    "id": "tq-20261008-mistral-large4-vals-code-migration",
    "model_slug": "mistral-large-4",
    "category": "coding",
    "benchmark_name": "Code Migration",
    "benchmark_version": null,
    "score_numeric": 30.56,
    "score_display": "30.56% (Vals)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Vals AI",
    "evaluator": "Vals AI",
    "evaluation_date": null,
    "source": "https://www.vals.ai/models/mistralai_mistral-large-4",
    "notes": "Independent Vals model-profile result. This source labels weights open, but the vendor says downloads are planned for late October, so that label does not change current catalog availability. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  },
  {
    "id": "tq-20261008-mistral-large4-vals-emb",
    "model_slug": "mistral-large-4",
    "category": "other",
    "benchmark_name": "EMB",
    "benchmark_version": null,
    "score_numeric": 56.21,
    "score_display": "56.21% (Vals)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Vals AI",
    "evaluator": "Vals AI",
    "evaluation_date": null,
    "source": "https://www.vals.ai/models/mistralai_mistral-large-4",
    "notes": "Independent Vals model-profile result. This source labels weights open, but the vendor says downloads are planned for late October, so that label does not change current catalog availability. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  },
  {
    "id": "tq-20261008-mistral-large4-vals-finance",
    "model_slug": "mistral-large-4",
    "category": "professional",
    "benchmark_name": "Vals Finance Agent",
    "benchmark_version": "v2",
    "score_numeric": 54.68,
    "score_display": "54.68% (Vals)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Vals AI",
    "evaluator": "Vals AI",
    "evaluation_date": null,
    "source": "https://www.vals.ai/models/mistralai_mistral-large-4",
    "notes": "Independent Vals model-profile result. This source labels weights open, but the vendor says downloads are planned for late October, so that label does not change current catalog availability. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  },
  {
    "id": "tq-20261008-mistral-large4-vals-legal-research",
    "model_slug": "mistral-large-4",
    "category": "professional",
    "benchmark_name": "Legal Research Bench",
    "benchmark_version": null,
    "score_numeric": 31.73,
    "score_display": "31.73% (Vals)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Vals AI",
    "evaluator": "Vals AI",
    "evaluation_date": null,
    "source": "https://www.vals.ai/models/mistralai_mistral-large-4",
    "notes": "Independent Vals model-profile result. This source labels weights open, but the vendor says downloads are planned for late October, so that label does not change current catalog availability. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  },
  {
    "id": "tq-20261008-mistral-large4-vals-medcode",
    "model_slug": "mistral-large-4",
    "category": "professional",
    "benchmark_name": "MedCode",
    "benchmark_version": null,
    "score_numeric": 40.69,
    "score_display": "40.69% (Vals)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Vals AI",
    "evaluator": "Vals AI",
    "evaluation_date": null,
    "source": "https://www.vals.ai/models/mistralai_mistral-large-4",
    "notes": "Independent Vals model-profile result. This source labels weights open, but the vendor says downloads are planned for late October, so that label does not change current catalog availability. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  },
  {
    "id": "tq-20261008-mistral-large4-vals-medscribe",
    "model_slug": "mistral-large-4",
    "category": "professional",
    "benchmark_name": "MedScribe",
    "benchmark_version": null,
    "score_numeric": 80.43,
    "score_display": "80.43% (Vals)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Vals AI",
    "evaluator": "Vals AI",
    "evaluation_date": null,
    "source": "https://www.vals.ai/models/mistralai_mistral-large-4",
    "notes": "Independent Vals model-profile result. This source labels weights open, but the vendor says downloads are planned for late October, so that label does not change current catalog availability. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  },
  {
    "id": "tq-20261008-mistral-large4-vals-mystery",
    "model_slug": "mistral-large-4",
    "category": "other",
    "benchmark_name": "MysteryMechanism",
    "benchmark_version": null,
    "score_numeric": 12.16,
    "score_display": "12.16% (Vals)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Vals AI",
    "evaluator": "Vals AI",
    "evaluation_date": null,
    "source": "https://www.vals.ai/models/mistralai_mistral-large-4",
    "notes": "Independent Vals model-profile result. This source labels weights open, but the vendor says downloads are planned for late October, so that label does not change current catalog availability. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  },
  {
    "id": "tq-20261008-mistral-large4-vals-proof",
    "model_slug": "mistral-large-4",
    "category": "math_reasoning",
    "benchmark_name": "ProofBench",
    "benchmark_version": "v1.1",
    "score_numeric": 10.0,
    "score_display": "10.00% (Vals)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Vals AI",
    "evaluator": "Vals AI",
    "evaluation_date": null,
    "source": "https://www.vals.ai/models/mistralai_mistral-large-4",
    "notes": "Independent Vals model-profile result. This source labels weights open, but the vendor says downloads are planned for late October, so that label does not change current catalog availability. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  },
  {
    "id": "tq-20261008-mistral-large4-vals-tax",
    "model_slug": "mistral-large-4",
    "category": "professional",
    "benchmark_name": "Tax Agent Bench",
    "benchmark_version": null,
    "score_numeric": 63.29,
    "score_display": "63.29% (Vals)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Vals AI",
    "evaluator": "Vals AI",
    "evaluation_date": null,
    "source": "https://www.vals.ai/models/mistralai_mistral-large-4",
    "notes": "Independent Vals model-profile result. This source labels weights open, but the vendor says downloads are planned for late October, so that label does not change current catalog availability. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  },
  {
    "id": "tq-20261008-mistral-large4-vals-vibe-1-100",
    "model_slug": "mistral-large-4",
    "category": "coding",
    "benchmark_name": "Vibe Code Bench 1-100",
    "benchmark_version": null,
    "score_numeric": 14.26,
    "score_display": "14.26% (Vals)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Vals AI",
    "evaluator": "Vals AI",
    "evaluation_date": null,
    "source": "https://www.vals.ai/models/mistralai_mistral-large-4",
    "notes": "Independent Vals model-profile result. This source labels weights open, but the vendor says downloads are planned for late October, so that label does not change current catalog availability. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  },
  {
    "id": "tq-20261008-mistral-large4-vals-vibe11",
    "model_slug": "mistral-large-4",
    "category": "coding",
    "benchmark_name": "Vibe Code Bench",
    "benchmark_version": "v1.1",
    "score_numeric": 78.4,
    "score_display": "78.40% (Vals)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Vals AI",
    "evaluator": "Vals AI",
    "evaluation_date": null,
    "source": "https://www.vals.ai/models/mistralai_mistral-large-4",
    "notes": "Independent Vals model-profile result. This source labels weights open, but the vendor says downloads are planned for late October, so that label does not change current catalog availability. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  },
  {
    "id": "tq-20261008-mistral-large4-vals-biomystery",
    "model_slug": "mistral-large-4",
    "category": "other",
    "benchmark_name": "BioMysteryBench",
    "benchmark_version": null,
    "score_numeric": 67.04,
    "score_display": "67.04% (Vals)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Vals AI",
    "evaluator": "Vals AI",
    "evaluation_date": null,
    "source": "https://www.vals.ai/models/mistralai_mistral-large-4",
    "notes": "Independent Vals model-profile result. This source labels weights open, but the vendor says downloads are planned for late October, so that label does not change current catalog availability. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  },
  {
    "id": "tq-20261008-mistral-large4-vals-harvey",
    "model_slug": "mistral-large-4",
    "category": "professional",
    "benchmark_name": "Harvey's Legal Agent Benchmark",
    "benchmark_version": "held-out, task pass rate",
    "score_numeric": 15.83,
    "score_display": "15.83% (Vals)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Vals AI",
    "evaluator": "Vals AI",
    "evaluation_date": null,
    "source": "https://www.vals.ai/models/mistralai_mistral-large-4",
    "notes": "Independent Vals model-profile result. This source labels weights open, but the vendor says downloads are planned for late October, so that label does not change current catalog availability. Held-out task pass rate from Harvey's benchmark; not the AA Harvey LAB-AA criterion pass rate. Methodology: https://www.vals.ai/benchmarks/hlab. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  },
  {
    "id": "tq-20261008-mistral-large4-vals-ioi",
    "model_slug": "mistral-large-4",
    "category": "coding",
    "benchmark_name": "IOI",
    "benchmark_version": null,
    "score_numeric": 45.28,
    "score_display": "45.28% (Vals)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Vals AI",
    "evaluator": "Vals AI",
    "evaluation_date": null,
    "source": "https://www.vals.ai/models/mistralai_mistral-large-4",
    "notes": "Independent Vals model-profile result. This source labels weights open, but the vendor says downloads are planned for late October, so that label does not change current catalog availability. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  },
  {
    "id": "tq-20261008-mistral-large4-vals-terminal40",
    "model_slug": "mistral-large-4",
    "category": "coding",
    "benchmark_name": "Terminal-Bench 4.0",
    "benchmark_version": null,
    "score_numeric": 22.73,
    "score_display": "22.73% (Vals)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Vals AI",
    "evaluator": "Vals AI",
    "evaluation_date": null,
    "source": "https://www.vals.ai/models/mistralai_mistral-large-4",
    "notes": "Independent Vals model-profile result. This source labels weights open, but the vendor says downloads are planned for late October, so that label does not change current catalog availability. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  },
  {
    "id": "tq-20261008-mistral-large4-mistral-deepswe",
    "model_slug": "mistral-large-4",
    "category": "coding",
    "benchmark_name": "DeepSWE v1.1",
    "benchmark_version": null,
    "score_numeric": 61.7,
    "score_display": "61.7% (Mistral)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Mistral AI",
    "evaluator": "Mistral AI",
    "evaluation_date": null,
    "source": "https://mistral.ai/news/mistral-large-4/",
    "notes": "Vendor-reported numeric result in the launch text. Checkpoint, harness details and tool settings are not fully specified. Competitor columns are not seeded. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  },
  {
    "id": "tq-20261008-mistral-large4-mistral-sweatlas",
    "model_slug": "mistral-large-4",
    "category": "coding",
    "benchmark_name": "SWE-Atlas Codebase QnA",
    "benchmark_version": null,
    "score_numeric": 59.4,
    "score_display": "59.4% (Mistral)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Mistral AI",
    "evaluator": "Mistral AI",
    "evaluation_date": null,
    "source": "https://mistral.ai/news/mistral-large-4/",
    "notes": "Vendor-reported numeric result in the launch text. Checkpoint, harness details and tool settings are not fully specified. Competitor columns are not seeded. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  },
  {
    "id": "tq-20261008-mistral-large4-mistral-terminal40",
    "model_slug": "mistral-large-4",
    "category": "coding",
    "benchmark_name": "Terminal-Bench 4.0",
    "benchmark_version": null,
    "score_numeric": 28.3,
    "score_display": "28.3% (Mistral)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Mistral AI",
    "evaluator": "Mistral AI",
    "evaluation_date": null,
    "source": "https://mistral.ai/news/mistral-large-4/",
    "notes": "Vendor-reported numeric result in the launch text. Checkpoint, harness details and tool settings are not fully specified. Competitor columns are not seeded. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  },
  {
    "id": "tq-20261008-mistral-large4-mistral-cybench",
    "model_slug": "mistral-large-4",
    "category": "coding",
    "benchmark_name": "Cybench",
    "benchmark_version": null,
    "score_numeric": 93,
    "score_display": "93.0% (Mistral)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Mistral AI",
    "evaluator": "Mistral AI",
    "evaluation_date": null,
    "source": "https://mistral.ai/news/mistral-large-4/",
    "notes": "Vendor-reported numeric result in the launch text. Checkpoint, harness details and tool settings are not fully specified. Competitor columns are not seeded. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  },
  {
    "id": "tq-20261008-mistral-large4-mistral-b3",
    "model_slug": "mistral-large-4",
    "category": "other",
    "benchmark_name": "B3 attack resistance",
    "benchmark_version": null,
    "score_numeric": 93.3,
    "score_display": "93.3% (Mistral)",
    "score_unit": "percent",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Mistral AI",
    "evaluator": "Mistral AI",
    "evaluation_date": null,
    "source": "https://mistral.ai/news/mistral-large-4/",
    "notes": "Vendor-reported numeric result in the launch text. Checkpoint, harness details and tool settings are not fully specified. Competitor columns are not seeded. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  },
  {
    "id": "tq-20261008-mistral-large4-mistral-kora",
    "model_slug": "mistral-large-4",
    "category": "other",
    "benchmark_name": "KORA Benchmark",
    "benchmark_version": null,
    "score_numeric": 1.691,
    "score_display": "1.691 / 2 (Mistral)",
    "score_unit": "score",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Mistral AI",
    "evaluator": "Mistral AI",
    "evaluation_date": null,
    "source": "https://mistral.ai/news/mistral-large-4/",
    "notes": "Vendor-reported score with a stated maximum of 2; not a percentage. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  },
  {
    "id": "tq-20261008-mistral-large4-mistral-surge",
    "model_slug": "mistral-large-4",
    "category": "coding",
    "benchmark_name": "Surge AI coding quality",
    "benchmark_version": null,
    "score_numeric": 3.74,
    "score_display": "3.74 / 5 (Mistral/Surge)",
    "score_unit": "score",
    "tools": null,
    "reasoning_effort": null,
    "harness": "Mistral AI",
    "evaluator": "Mistral AI",
    "evaluation_date": null,
    "source": "https://mistral.ai/news/mistral-large-4/",
    "notes": "Vendor reports a blind professional-annotator evaluation run with Surge AI on a 1 to 5 scale; not a coding-task pass rate. Observed October 8, 2026. Exact evaluation date and reasoning effort are not specified."
  }
]
$benchmarks$::jsonb) AS evidence(
  id TEXT, model_slug TEXT, category TEXT, benchmark_name TEXT,
  benchmark_version TEXT, score_numeric DOUBLE PRECISION, score_display TEXT,
  score_unit TEXT, tools BOOLEAN, reasoning_effort TEXT, harness TEXT,
  evaluator TEXT, evaluation_date TEXT, source TEXT, notes TEXT
)
ON CONFLICT (id) DO UPDATE SET
  model_slug = EXCLUDED.model_slug, category = EXCLUDED.category,
  benchmark_name = EXCLUDED.benchmark_name, benchmark_version = EXCLUDED.benchmark_version,
  score_numeric = EXCLUDED.score_numeric, score_display = EXCLUDED.score_display,
  score_unit = EXCLUDED.score_unit, tools = EXCLUDED.tools,
  reasoning_effort = EXCLUDED.reasoning_effort, harness = EXCLUDED.harness,
  evaluator = EXCLUDED.evaluator, evaluation_date = EXCLUDED.evaluation_date,
  source = EXCLUDED.source, notes = EXCLUDED.notes, updated_at = NOW();
